$c = Get-Content 'lib\features\premium\presentation\pages\premium_screen.dart' -Raw
$c = [regex]::Replace($c, '\b_isProcessing\b', '_isProcessingVal')
$c = [regex]::Replace($c, '\b_paymentCompleted\b', '_paymentCompletedVal')
$c = [regex]::Replace($c, '\b_paymentSuccess\b', '_paymentSuccessVal')
$c = [regex]::Replace($c, '\b_errorMessage\b', '_errorMessageVal')
$c = [regex]::Replace($c, '\b_transactionId\b', '_transactionIdVal')
$c = [regex]::Replace($c, '\b_activePlans\b', '_activePlansVal')
$c = [regex]::Replace($c, '\b_selectedPlanIndex\b', '_selectedPlanIndexVal')
$c = [regex]::Replace($c, 'setState\(\(\) \{\s*_isProcessingVal = false;\s*_paymentCompletedVal = true;\s*_paymentSuccessVal = false;\s*_errorMessageVal = context\.tr\(\s*''premium\.error_timeout'',\s*fallback: ''Request timed out'',\s*\);\s*\}\);', "_isProcessingVal = false;`r`n        _paymentCompletedVal = true;`r`n        _paymentSuccessVal = false;`r`n        _errorMessageVal = context.tr(`r`n          'premium.error_timeout',`r`n          fallback: 'Request timed out',`r`n        );`r`n        _updateState();")
$c = [regex]::Replace($c, 'setState\(\(\) \{\s*_isProcessingVal = false;\s*_paymentCompletedVal = true;\s*_paymentSuccessVal = true;\s*_transactionIdVal = response\.paymentId;\s*_errorMessageVal = null;\s*\}\);', "_isProcessingVal = false;`r`n            _paymentCompletedVal = true;`r`n            _paymentSuccessVal = true;`r`n            _transactionIdVal = response.paymentId;`r`n            _errorMessageVal = null;`r`n            _updateState();")
$c = [regex]::Replace($c, 'setState\(\(\) \{\s*_isProcessingVal = false;\s*_paymentCompletedVal = true;\s*_paymentSuccessVal = false;\s*_errorMessageVal = context\.tr\(\s*''premium\.error_upgrade_failed'',\s*fallback: ''Upgrade Failed'',\s*\);\s*\}\);', "_isProcessingVal = false;`r`n          _paymentCompletedVal = true;`r`n          _paymentSuccessVal = false;`r`n          _errorMessageVal = context.tr(`r`n            'premium.error_upgrade_failed',`r`n            fallback: 'Upgrade Failed',`r`n          );`r`n          _updateState();")
$c = [regex]::Replace($c, 'setState\(\(\) \{\s*_isProcessingVal = false;\s*_paymentCompletedVal = true;\s*_paymentSuccessVal = false;\s*// Razorpay''s `response\.message` is already a user-safe,\s*// gateway-provided description \(not a raw exception\), so it is\s*// fine to surface directly, with a localized fallback\.\s*_errorMessageVal =\s*response\.message \?\?\s*context\.tr\(''premium\.error_generic'', fallback: ''An error occurred''\);\s*\}\);', "_isProcessingVal = false;`r`n        _paymentCompletedVal = true;`r`n        _paymentSuccessVal = false;`r`n        // Razorpay's ``response.message`` is already a user-safe,`r`n        // gateway-provided description (not a raw exception), so it is`r`n        // fine to surface directly, with a localized fallback.`r`n        _errorMessageVal =`r`n            response.message ??`r`n            context.tr('premium.error_generic', fallback: 'An error occurred');`r`n        _updateState();")
$c = [regex]::Replace($c, 'setState\(\(\) \{\s*_paymentCompletedVal = false;\s*_paymentSuccessVal = null;\s*_errorMessageVal = null;\s*_transactionIdVal = null;\s*\}\);', "_paymentCompletedVal = false;`r`n                        _paymentSuccessVal = null;`r`n                        _errorMessageVal = null;`r`n                        _transactionIdVal = null;`r`n                        _updateState();")
Set-Content 'lib\features\premium\presentation\pages\premium_screen.dart' $c
