const fs = require('fs');
let p = 'lib/features/accent/vowel_distinction/presentation/pages/vowel_distinction_screen.dart';
let c = fs.readFileSync(p, 'utf8');
c = c.replace(/void _submitChoice\(int index, int correct\)/, 'void _submitChoice(int index, int correct, GameQuest quest)');
c = c.replace(/_submitChoice\(i, correctIndex\)/g, '_submitChoice(i, correctIndex, quest)');
c = c.replace(/submitWrongAnswer\(quest: currentQuestOrNull!/g, 'submitWrongAnswer(quest: quest');
c = c.replace(/void _submitVerbalEvaluation\(bool nailedIt\)/, 'void _submitVerbalEvaluation(bool nailedIt, GameQuest quest)');
c = c.replace(/_submitVerbalEvaluation\(true\)/g, '_submitVerbalEvaluation(true, quest)');
c = c.replace(/_submitVerbalEvaluation\(false\)/g, '_submitVerbalEvaluation(false, quest)');
fs.writeFileSync(p, c);
