const fs = require('fs');

const filesToFix = [
    'lib/features/writing/summarize_story_writing/presentation/pages/summarize_story_writing_screen.dart',
    'lib/features/writing/essay_drafting/presentation/pages/essay_drafting_screen.dart'
];

for (const file of filesToFix) {
    let content = fs.readFileSync(file, 'utf8');

    content = content.replace(/(useScrolling:\s*false,)/g, "$1\n          disablePadding: true,");

    if (!content.includes('void _scrollToBottom()')) {
        content = content.replace(/\s*@override\s*Widget build\(BuildContext context\) \{/, "\n  void _scrollToBottom() {\n    WidgetsBinding.instance.addPostFrameCallback((_) {\n      if (_scrollController.hasClients) {\n        _scrollController.animateTo(\n          _scrollController.position.maxScrollExtent,\n          duration: const Duration(milliseconds: 400),\n          curve: Curves.easeOutCubic,\n        );\n      }\n    });\n  }\n\n  @override\n  Widget build(BuildContext context) {");
    }

    content = content.replace(/(_pendingSubmit\.value = true;\s*\})/g, "_pendingSubmit.value = true;\n    _scrollToBottom();\n  }");

    if (!content.includes('AbsorbPointer(absorbing: _pendingSubmit.value')) {
        content = content.replace(/child:\s*Column\(/, "child: AbsorbPointer(absorbing: _pendingSubmit.value && !isAnswered, child: Column(");
    }

    content = content.replace(/:\s*Stack\(\s*children:\s*\[\s*LayoutBuilder\(/, ": LayoutBuilder(");
    content = content.replace(/:\s*Stack\(\s*children:\s*\[\s*RawScrollbar\(/, ": RawScrollbar(");

    if (file.includes('summarize_story')) {
        const targetOld = "                                          SizedBox(\n                                            height: !isAnswered ? 380.h : 160.h,\n                                          ),\n                                        ],\n                                      ),\n                                    ),\n                                  ),\n                                ],\n                              ),\n                            );\n                          },\n                        ),\n                        if (_pendingSubmit.value && !isAnswered)\n                          TypeToConfirmOverlay(\n                            expectedText: _slots.value.isNotEmpty\n                                ? (_slots.value[0].sentence ?? \"\")\n                                : \"\",\n                            displayText:\n                                \"Type the first sentence to finalize your summary\",\n                            primaryColor: theme.primaryColor,\n                            onConfirmed: () => _submitFinalAnswer(true),\n                            onSkipped: () => _submitFinalAnswer(false),\n                            allowSkip: true,\n                          ),\n                      ],";
        const targetNew = "                                          if (_pendingSubmit.value && !isAnswered)\n                                            TypeToConfirmOverlay(\n                                              expectedText: _slots.value.isNotEmpty\n                                                  ? (_slots.value[0].sentence ?? \"\")\n                                                  : \"\",\n                                              displayText:\n                                                  \"Type the first sentence to finalize your summary\",\n                                              primaryColor: theme.primaryColor,\n                                              onConfirmed: () => _submitFinalAnswer(true),\n                                              onSkipped: () => _submitFinalAnswer(false),\n                                              allowSkip: true,\n                                              isPositioned: false,\n                                            ),\n                                          SizedBox(\n                                            height: !isAnswered ? MediaQuery.viewInsetsOf(context).bottom + 40.h : 160.h,\n                                          ),\n                                        ],\n                                      ),\n                                    ),\n                                  ),\n                                ],\n                              ),\n                            );\n                          },\n                        ),";
        content = content.replace(targetOld, targetNew);
    } else {
        const targetOld = "                                        SizedBox(\n                                          height: !isAnswered ? 380.h : 160.h,\n                                        ),\n                                      ],\n                                    ),\n                                  ),\n                                ),\n                              ],\n                            ),\n                          ),\n                          if (_pendingSubmit.value && !isAnswered)\n                            TypeToConfirmOverlay(\n                              expectedText:\n                                  _blueprintSlots.value.isNotEmpty &&\n                                      _blueprintSlots.value.values.first != null\n                                  ? _blueprintSlots.value.values.first!\n                                  : \"\",\n                              displayText:\n                                  \"Type the first point to finalize the outline\",\n                              primaryColor: theme.primaryColor,\n                              onConfirmed: () => _submitFinalAnswer(true),\n                              onSkipped: () => _submitFinalAnswer(false),\n                              allowSkip: true,\n                            ),\n                        ],";
        const targetNew = "                                        if (_pendingSubmit.value && !isAnswered)\n                                          TypeToConfirmOverlay(\n                                            expectedText:\n                                                _blueprintSlots.value.isNotEmpty &&\n                                                    _blueprintSlots.value.values.first != null\n                                                ? _blueprintSlots.value.values.first!\n                                                : \"\",\n                                            displayText:\n                                                \"Type the first point to finalize the outline\",\n                                            primaryColor: theme.primaryColor,\n                                            onConfirmed: () => _submitFinalAnswer(true),\n                                            onSkipped: () => _submitFinalAnswer(false),\n                                            allowSkip: true,\n                                            isPositioned: false,\n                                          ),\n                                        SizedBox(\n                                          height: !isAnswered ? MediaQuery.viewInsetsOf(context).bottom + 40.h : 160.h,\n                                        ),\n                                      ],\n                                    ),\n                                  ),\n                                ),\n                              ],\n                            ),\n                          ),";
        content = content.replace(targetOld, targetNew);
    }

    fs.writeFileSync(file, content, 'utf8');
}
