// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQW28i4Mcb7qx4BCB4kY_KPher_-g_Bhc',
    appId: '1:497469756340:web:0c6158771d3696aa65d8e1',
    messagingSenderId: '497469756340',
    projectId: 'vowl-acbc5',
    authDomain: 'vowl-acbc5.firebaseapp.com',
    storageBucket: 'vowl-acbc5.firebasestorage.app',
    measurementId: 'G-QS8XJS8854',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqku10x730salv8uDeCBMX19Wm19Pn-VM',
    appId: '1:497469756340:android:2c107108a2fc009765d8e1',
    messagingSenderId: '497469756340',
    projectId: 'vowl-acbc5',
    storageBucket: 'vowl-acbc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQKoZmbi2rUWF5-Ds3yT5H8W4fQFyPZ_w',
    appId: '1:497469756340:ios:a8fa82c0c68e34d765d8e1',
    messagingSenderId: '497469756340',
    projectId: 'vowl-acbc5',
    storageBucket: 'vowl-acbc5.firebasestorage.app',
    iosBundleId: 'com.vowl.app',
  );

}