/**
 * Pool Expander — adds programmatically generated entries to reach 600
 * for pools that are data-heavy and need more unique entries.
 * This modifies the pool functions to self-expand using combinatorial patterns.
 */

// Consonant Clarity: add 40 more words
// Word Linking: add 95 more phrases  
// Shadowing: add 294 more sentences
// Syllable Stress: add 297 more words
// Minimal Pairs: add 300 more pairs
// Vowel Distinction: add 360 more pairs
// Dialect Drill: add 378 more words

// Strategy: For each pool, we'll append entries using word-generation patterns.

const fs = require('fs');
const path = require('path');

// === ADDITIONAL CONSONANT CLARITY WORDS (40+) ===
const extraConsonantClarity = [
  // More voiced/unvoiced contrasts
  ['PRISM','/z/ (z)','/s/ (s)',0],['WISDOM','/z/ (z)','/s/ (s)',0],
  ['HUSBAND','/z/ (z)','/s/ (s)',0],['PRISON','/z/ (z)','/s/ (s)',0],
  ['COUSIN','/z/ (z)','/s/ (s)',0],['DESERT','/z/ (z)','/s/ (s)',0],
  ['PRESENT','/z/ (z)','/s/ (s)',0],['MUSEUM','/z/ (z)','/s/ (s)',0],
  ['MUSIC','/z/ (z)','/s/ (s)',0],['REASON','/z/ (z)','/s/ (s)',0],
  ['SEASON','/z/ (z)','/s/ (s)',0],['POISON','/z/ (z)','/s/ (s)',0],
  ['DOZEN','/z/ (z)','/s/ (s)',0],['FROZEN','/z/ (z)','/s/ (s)',0],
  ['CHOSEN','/z/ (z)','/s/ (s)',0],['RESIGN','/z/ (z)','/s/ (s)',0],
  ['DESIGN','/z/ (z)','/s/ (s)',0],['OBSERVE','/z/ (z)','/s/ (s)',0],
  ['ABSORB','/b/ (b)','/p/ (p)',0],['DESCRIBE','/b/ (b)','/p/ (p)',0],
  ['DISTURB','/b/ (b)','/p/ (p)',0],['GLOBE','/b/ (b)','/p/ (p)',0],
  ['PROBE','/b/ (b)','/p/ (p)',0],['ROBE','/b/ (b)','/p/ (p)',0],
  ['TUBE','/b/ (b)','/p/ (p)',0],['CUBE','/b/ (b)','/p/ (p)',0],
  ['VERB','/b/ (b)','/p/ (p)',0],['HERB','/b/ (b)','/p/ (p)',0],
  ['CURB','/b/ (b)','/p/ (p)',0],['SUBURB','/b/ (b)','/p/ (p)',0],
  ['BLEND','/b/ (b)','/p/ (p)',0],['BRAND','/b/ (b)','/p/ (p)',0],
  ['BREED','/b/ (b)','/p/ (p)',0],['BRIEF','/b/ (b)','/p/ (p)',0],
  ['BROAD','/b/ (b)','/p/ (p)',0],['BRONZE','/b/ (b)','/p/ (p)',0],
  ['BROTH','/b/ (b)','/p/ (p)',0],['BRUISE','/b/ (b)','/p/ (p)',0],
  ['BURDEN','/b/ (b)','/p/ (p)',0],['BURST','/b/ (b)','/p/ (p)',0],
  ['BUSTLE','/b/ (b)','/p/ (p)',0],['BLISTER','/b/ (b)','/p/ (p)',0],
];

// === ADDITIONAL WORD LINKING PHRASES (95+) ===
const extraWordLinking = [
  // More C→V phrases
  'turn off all lights','pick up some flowers','put on your jacket','take out the trash',
  'give up bad habits','come in right now','sit down right here','stand up straight please',
  'move on from this','look out for danger','calm down a moment','speak up louder please',
  'slow down a little','speed up the process','clean up your desk','clear out old files',
  'head off to work','branch out from here','reach out for help','step aside for now',
  'climb up the stairs','jump over the fence','swim across the lake','walk along the path',
  'drive around the block','fly over the mountains','run along the beach','sail across the bay',
  'hike up the trail','crawl under the fence','wade through the stream','dash across the road',
  'stroll along the pier','march down the street','sprint across the field','wander around town',
  'glide across the ice','paddle along the river','trek through the jungle','coast along the shore',
  // More V→V phrases
  'go on ahead now','do it again tomorrow','so I understand','also I agree with',
  'she always asks why','he often eats alone','we usually arrive early','they always argue about',
  'I only asked once','do all of them','go over it again','see if anyone knows',
  // More assimilation
  'white board marker','that person there','good morning class','great band tonight',
  'would be nice','could be better','should be ready','might be wrong',
  'want more food','need more time','find more space','make more plans',
  'last month ago','next month ahead','first month here','worst month ever',
  // More elision
  'asked them politely','reached down carefully','watched them quietly','touched down softly',
  'pushed forward bravely','crashed down loudly','launched quickly today','searched everywhere here',
  'switched off suddenly','ditched class today','hitched a ride home','stitched up the wound',
  'fetched the supplies','sketched a drawing','stretched out fully','wretched old building',
  'hatched a new plan','matched perfectly well','dispatched immediately now','snatched away quickly',
  'clutched tightly shut','crutched along slowly','thatched roof cottage','patched up nicely',
  'botched the attempt','notched another win','scotched the rumor','botched another try',
];

// === ADDITIONAL SHADOWING SENTENCES (294+) ===
const extraShadowing = [
  'The morning sunlight filtered through the kitchen window.',
  'She carefully arranged the flowers in a crystal vase.',
  'The old bookstore around the corner has a wonderful selection.',
  'We need to finish this project before the end of the week.',
  'The children were playing happily in the neighborhood park.',
  'He decided to take public transportation to save money.',
  'The new restaurant downtown serves authentic Mediterranean cuisine.',
  'She graduated with honors from the school of engineering.',
  'The museum exhibit showcases art from the Renaissance period.',
  'We should schedule a meeting with the marketing department.',
  'The weather forecast predicts heavy rain throughout the weekend.',
  'He enjoys reading historical fiction novels before bedtime.',
  'The local farmers market opens every Saturday morning at eight.',
  'She volunteers at the community center on Wednesday evenings.',
  'The professor explained the complex theory in simple terms.',
  'We are planning a family reunion for next summer.',
  'The architect designed a sustainable building with solar panels.',
  'He completed the marathon in under four hours.',
  'The documentary about ocean conservation was deeply moving.',
  'She received a scholarship to study abroad in France.',
  'The technology conference attracted thousands of participants.',
  'We need to update our software to the latest version.',
  'The garden looks beautiful with all the spring flowers blooming.',
  'He taught himself to play guitar using online tutorials.',
  'The hospital implemented new safety protocols last month.',
  'She organized a charity event to raise funds for education.',
  'The train arrives at platform three in approximately ten minutes.',
  'We should consider alternative energy sources for our building.',
  'The library has extended its hours during exam season.',
  'He started his own business after years of corporate work.',
  'The national park covers over two million acres of wilderness.',
  'She presented her research findings at the international conference.',
  'The city council approved plans for a new community center.',
  'We celebrated the team victory with a special dinner.',
  'The airline offers direct flights to over fifty destinations.',
  'He volunteered to coach the youth basketball team this season.',
  'The art gallery features works by contemporary local artists.',
  'She completed her doctorate in molecular biology last spring.',
  'The neighborhood association organized a cleanup day for Saturday.',
  'We adopted a rescue dog from the local animal shelter.',
  'The software update includes several important security patches.',
  'He learned three languages before turning twenty-five years old.',
  'The botanical garden has over five thousand plant species.',
  'She manages a team of twenty software developers at work.',
  'The bridge was designed to withstand severe earthquake conditions.',
  'We enjoyed a wonderful vacation on the Mediterranean coast.',
  'The orchestra performed Beethoven\'s Fifth Symphony last evening.',
  'He published his first novel at the age of thirty.',
  'The university campus includes a state-of-the-art research facility.',
  'She developed an innovative approach to renewable energy storage.',
  'The company donated millions to environmental conservation efforts.',
  'We watched the sunrise from the top of the mountain.',
  'The chef prepared a five-course meal for the special occasion.',
  'He repaired the vintage motorcycle in his garage workshop.',
  'The school district implemented a new reading program this fall.',
  'She trained for six months before running her first marathon.',
  'The conference room can accommodate up to fifty participants.',
  'We planted fifty trees in the community garden last weekend.',
  'The film festival showcased independent movies from around the world.',
  'He discovered a passion for photography during his travels abroad.',
  'The research team made a breakthrough in cancer treatment methods.',
  'She designed an ergonomic workspace that improved team productivity.',
  'The farmers market features organic produce from local farms.',
  'We upgraded the heating system to reduce energy consumption costs.',
  'The symphony orchestra is performing a special holiday concert.',
  'He built a custom computer for video editing and design work.',
  'The wildlife sanctuary provides refuge for endangered animal species.',
  'She created a comprehensive training program for new employees.',
  'The renovation project transformed the old warehouse into modern offices.',
  'We participated in the annual charity walk for heart disease.',
  'The science fair attracted students from across the entire region.',
  'He maintained a daily journal of observations and reflections.',
  'The company expanded its operations to three new international markets.',
  'She designed a mobile application that helps track daily habits.',
  'The environmental agency released new guidelines for clean water standards.',
  'We organized a book club that meets every other Thursday.',
  'The basketball team won the championship for the third consecutive year.',
  'He completed an online certification in data science and analytics.',
  'The historic building was carefully restored to its original condition.',
  'She coordinated relief efforts during the recent flooding emergency.',
  'The transportation committee proposed several improvements to public transit.',
  'We arranged a surprise celebration for the retiring department head.',
  'The research paper was cited by over two hundred other publications.',
  'He introduced a mentorship program connecting seniors with new students.',
  'The zoo recently opened a new exhibit featuring Arctic animals.',
  'She established a foundation to support underprivileged students education.',
  'The manufacturing plant reduced its carbon emissions by forty percent.',
  'We implemented a customer loyalty program that increased retention rates.',
  'The jazz band performed at the downtown music festival last weekend.',
  'He designed a rainwater harvesting system for the community garden.',
  'The health clinic offers free screenings every first Saturday morning.',
  'She negotiated a partnership deal with a major technology company.',
  'The city introduced bicycle lanes on several major downtown streets.',
  'We completed the kitchen renovation ahead of the planned schedule.',
  'The hiking trail winds through ancient redwood forests for miles.',
  'He organized monthly workshops on personal finance and investment strategies.',
  'The dance academy has produced several nationally recognized performers.',
  'She developed a curriculum for teaching coding to young children.',
  'The power grid was upgraded to handle increased renewable energy capacity.',
  'We launched an online platform for connecting volunteers with organizations.',
  'The veterinary clinic provides emergency services around the clock.',
  'He restored the classic car to its original factory specifications.',
  'The university offers several fully online graduate degree programs.',
  'She curated a photography exhibition featuring underwater marine landscapes.',
  'The food bank distributed over ten thousand meals during the holidays.',
  'We installed energy-efficient lighting throughout the entire office building.',
  'The astronomy club organized a stargazing event at the observatory.',
  'He mentored young entrepreneurs through the business incubator program.',
  'The aquarium introduced a new interactive exhibit for young visitors.',
  'She analyzed market trends to develop a competitive pricing strategy.',
  'The community theater group is performing a classic Shakespeare play.',
  'We redesigned the company website to improve user experience and navigation.',
  'The graduation ceremony will be held outdoors in the main courtyard.',
  'He leads a weekly meditation group at the wellness center.',
  'The robotics team qualified for the national competition finals.',
  'She pioneered a new technique for minimally invasive heart surgery.',
  'The firefighters responded to the emergency within three minutes.',
  'We submitted the grant proposal before the application deadline.',
  'The marine biologist discovered a previously unknown deep-sea species.',
  'He organized a neighborhood watch program to improve community safety.',
  'The solar panels generate enough electricity to power fifty homes.',
  'She founded a nonprofit organization dedicated to promoting literacy.',
  'The bridge construction project was completed two months ahead of schedule.',
  'We adopted sustainable packaging practices to reduce environmental waste.',
  'The debate team won first place at the regional competition.',
  'He developed a mobile game that became popular worldwide overnight.',
  'The physical therapy program helped patients recover from sports injuries.',
  'She published a groundbreaking study on the effects of climate change.',
  'The orchestra conductor received a standing ovation after the performance.',
  'We transformed the unused lot into a vibrant community playground.',
  'The airline introduced new routes connecting rural areas to cities.',
  'He taught a free online course that attracted thousands of students.',
  'The geological survey revealed significant mineral deposits underground.',
  'She created an artificial intelligence system that can translate sign language.',
  'The emergency management team conducted a citywide disaster preparedness drill.',
  'We partnered with local schools to provide after-school tutoring programs.',
  'The renewable energy project will create hundreds of new local jobs.',
  'He performed a complex surgery that lasted over twelve consecutive hours.',
  'The archaeological dig uncovered artifacts from an ancient civilization.',
  'She designed a water purification system for communities without clean water.',
  'The national team celebrated their first gold medal at the Olympics.',
  'We organized a blood drive that collected over five hundred donations.',
  'The electric bus fleet reduced the city air pollution by thirty percent.',
  'He invented a device that converts ocean waves into usable electricity.',
  'The literacy program has taught over three thousand adults to read.',
  'She engineered a prosthetic limb with enhanced sensory feedback capabilities.',
  'The coral reef restoration project showed encouraging signs of recovery.',
  'We established an exchange program with universities in six different countries.',
  'The vaccination campaign reached over ninety percent of the population.',
  'He composed a symphony that premiered at the national concert hall.',
  'The earthquake-resistant building design saved numerous lives during the tremor.',
  'She won the prestigious award for her contributions to medical research.',
  'The autonomous vehicle successfully completed a cross-country test drive.',
  'We renovated the community swimming pool to meet modern safety standards.',
  'The satellite provided detailed images of previously unmapped ocean terrain.',
  'He donated his entire art collection to the national museum permanently.',
  'The high-speed train reduced travel time between the cities by half.',
  'She founded a tech startup that focuses on accessible education tools.',
  'The climate summit brought together leaders from over one hundred nations.',
  'We raised enough money to build a new school in the village.',
  'The genome sequencing project identified genetic markers for rare diseases.',
  'He wrote a memoir about his experiences traveling through remote regions.',
  'The desalination plant provides fresh drinking water to coastal communities.',
  'She developed a machine learning model that predicts natural disaster patterns.',
  'The peace negotiations resulted in a historic ceasefire agreement today.',
  'We converted the factory into affordable housing for local residents.',
  'The wind farm generates enough clean energy to power an entire town.',
  'He pioneered a new approach to teaching mathematics using visual methods.',
  'The space telescope captured stunning images of a distant galaxy forming.',
  'She led the initiative to preserve endangered languages through recordings.',
  'The recycling program diverted millions of pounds of waste from landfills.',
  'We established a scholarship fund for first-generation college students.',
  'The volcanic eruption created a new island in the Pacific Ocean.',
  'He broke the world record in the hundred-meter sprint at the Olympics.',
  'The forest conservation project protected thousands of acres of old growth.',
  'She authored a bestselling book about the science of human behavior.',
  'The deep-sea exploration mission discovered previously unknown hydrothermal vents.',
  'We implemented a zero-waste policy across all company operations globally.',
  'The paramedics stabilized the patient before the helicopter arrived quickly.',
  'He designed a sustainable urban farm that produces food year-round.',
  'The international aid organization provided relief to disaster-affected communities.',
  'She conducted a landmark study on the benefits of early childhood education.',
  'The carbon-neutral factory set a new standard for sustainable manufacturing.',
  'We created public green spaces that improved neighborhood quality of life.',
  'The telescope array detected radio signals from a distant star system.',
  'He restored the wetland habitat, bringing back dozens of native bird species.',
  'The mobile health clinic provides medical care to underserved rural areas.',
  'She invented a biodegradable plastic alternative made entirely from seaweed.',
  'The tunnel project connected two previously isolated mountain communities permanently.',
  'We trained local residents in sustainable farming techniques and water conservation.',
  'The quantum computer solved complex protein folding problems in record time.',
  'He established a free legal aid clinic serving low-income families.',
  'The tidal energy project harnesses ocean currents to generate clean electricity.',
  'She created a virtual reality therapy program for treating anxiety disorders.',
  'The reforestation effort has planted over ten million trees in five years.',
  'We launched a community solar project that benefits hundreds of households.',
  'The gene therapy trial showed remarkable results in treating inherited blindness.',
  'He designed an affordable water filtration system for developing nations.',
  'The electric ferry service replaced diesel boats on the harbor route.',
  'She led a team that developed a vaccine in record-breaking time.',
  'The smart grid technology reduced power outages across the entire region.',
  'We organized an international student exchange program spanning twelve countries.',
  'The biodiversity survey documented three hundred previously unknown insect species.',
  'He composed music therapy programs that help patients with memory disorders.',
  'The underground railway extension improved access to employment for thousands.',
  'She established a coding bootcamp that has graduated over five hundred students.',
  'The vertical farm produces leafy greens using ninety percent less water.',
  'We collaborated with indigenous communities to preserve traditional ecological knowledge.',
  'The fusion energy experiment achieved sustained plasma for the first time.',
  'He directed a documentary that raised awareness about ocean plastic pollution.',
  'The flood barrier system protected the coastal city from storm surge damage.',
  'She developed a peer mentoring program that reduced student dropout rates.',
  'The green building certification program has improved energy efficiency standards nationally.',
  'We distributed solar-powered lanterns to families living without electricity access.',
  'The brain-computer interface allowed paralyzed patients to communicate through thought.',
  'He launched a social enterprise that employs refugees in skilled positions.',
  'The coral spawning event was the largest recorded in the past decade.',
  'She pioneered regenerative agriculture practices that restore degraded farmland soil.',
  'The disaster warning system provided critical alerts thirty minutes before impact.',
  'We commissioned a public mural celebrating the cultural diversity of our city.',
  'The hydrogen fuel cell bus fleet began service on three major routes.',
  'He created a scholarship program specifically for students pursuing environmental science.',
  'The marine sanctuary expanded its boundaries to protect additional endangered species.',
  'She built a network of free public Wi-Fi hotspots across the region.',
  'The methane capture technology at the landfill now generates clean electricity.',
  'We established a sister city relationship to promote cultural exchange programs.',
  'The precision medicine approach tailored cancer treatment to individual genetic profiles.',
  'He founded an organization that teaches financial literacy in underserved communities.',
  'The asteroid mining proposal attracted significant international investment and interest.',
  'She designed an accessible playground that accommodates children of all abilities.',
  'The battery recycling facility processes thousands of tons of electronic waste annually.',
  'We created a digital archive preserving thousands of historic photographs and documents.',
  'The autonomous drone delivery service now reaches remote mountain communities regularly.',
  'He spearheaded a campaign that successfully banned single-use plastics citywide.',
  'The geothermal heating system reduced the school district energy costs dramatically.',
  'She developed an early warning system for detecting wildfire outbreaks rapidly.',
  'The ocean cleanup vessel collected over fifty tons of floating plastic debris.',
  'We opened a makerspace where community members can learn digital fabrication skills.',
  'The stem cell research breakthrough offered new hope for spinal cord injuries.',
  'He planted a community orchard that now supplies fruit to local food banks.',
  'The biomimicry design approach created more efficient wind turbine blade shapes.',
  'She trained service dogs that assist veterans coping with post-traumatic stress.',
  'The international treaty established protections for deep-sea biodiversity worldwide.',
  'We launched a citizen science project monitoring migratory bird populations annually.',
  'The 3D-printed housing project provided affordable homes for dozens of families.',
  'He developed an app connecting surplus restaurant food with local shelters.',
  'The restored wetlands now filter millions of gallons of stormwater naturally.',
  'She created a podcast series interviewing scientists about breakthrough discoveries weekly.',
  'The electric aircraft completed its maiden commercial passenger flight successfully today.',
  'We implemented a four-day work week that improved employee satisfaction scores.',
  'The microplastics filtration system removes contaminants from municipal water supplies effectively.',
  'He organized annual beach cleanup events that have removed tons of debris.',
  'The mushroom-based packaging material provides a compostable alternative to styrofoam.',
  'She established a network of urban beehives to support local pollinator populations.',
  'The language preservation project recorded fluent speakers of twelve endangered languages.',
  'We converted abandoned railway lines into popular recreational cycling and walking trails.',
];

// === ADDITIONAL SYLLABLE STRESS WORDS (297+) ===
const extraSyllableStress = [
  // More first-syllable stressed 2-syllable words
  ['ABSENT','AB-sent','ab-SENT',0],['ACTION','AC-tion','ac-TION',0],['ANGEL','AN-gel','an-GEL',0],
  ['ANKLE','AN-kle','an-KLE',0],['ARROW','AR-row','ar-ROW',0],['AWFUL','AW-ful','aw-FUL',0],
  ['BACKUP','BACK-up','back-UP',0],['BALANCE','BAL-ance','bal-ANCE',0],['BARREL','BAR-rel','bar-REL',0],
  ['BITTER','BIT-ter','bit-TER',0],['BLANKET','BLAN-ket','blan-KET',0],['BLESSING','BLES-sing','bles-SING',0],
  ['BOTTOM','BOT-tom','bot-TOM',0],['BOUNTY','BOUN-ty','boun-TY',0],['BUBBLE','BUB-ble','bub-BLE',0],
  ['BURDEN','BUR-den','bur-DEN',0],['BUTTON','BUT-ton','but-TON',0],['CANDLE','CAN-dle','can-DLE',0],
  ['CAPTURE','CAP-ture','cap-TURE',0],['CAUTION','CAU-tion','cau-TION',0],['CERTAIN','CER-tain','cer-TAIN',0],
  ['CHANNEL','CHAN-nel','chan-NEL',0],['CHARTER','CHAR-ter','char-TER',0],['CHIPMUNK','CHIP-munk','chip-MUNK',0],
  ['CLIMATE','CLI-mate','cli-MATE',0],['COASTAL','COAST-al','coast-AL',0],['CONTEST','CON-test','con-TEST',0],
  ['CONTRAST','CON-trast','con-TRAST',0],['COPPER','COP-per','cop-PER',0],['CORNER','COR-ner','cor-NER',0],
  ['COTTAGE','COT-tage','cot-TAGE',0],['COUNTER','COUN-ter','coun-TER',0],['COURAGE','COUR-age','cour-AGE',0],
  ['CREATURE','CREA-ture','crea-TURE',0],['CRICKET','CRICK-et','crick-ET',0],['CRYSTAL','CRYS-tal','crys-TAL',0],
  ['CULTURE','CUL-ture','cul-TURE',0],['CURTAIN','CUR-tain','cur-TAIN',0],['CUSTOM','CUS-tom','cus-TOM',0],
  ['DAGGER','DAG-ger','dag-GER',0],['DAMAGE','DAM-age','dam-AGE',0],['DARKNESS','DARK-ness','dark-NESS',0],
  ['DISTANT','DIS-tant','dis-TANT',0],['DOLPHIN','DOL-phin','dol-PHIN',0],['DOUBLE','DOU-ble','dou-BLE',0],
  ['DRAGON','DRA-gon','dra-GON',0],['EAGLE','EA-gle','ea-GLE',0],['ELBOW','EL-bow','el-BOW',0],
  ['EMPIRE','EM-pire','em-PIRE',0],['ENGINE','EN-gine','en-GINE',0],['EQUAL','E-qual','e-QUAL',0],
  ['EXTRA','EX-tra','ex-TRA',0],['FAILURE','FAI-lure','fai-LURE',0],['FALCON','FAL-con','fal-CON',0],
  ['FEATHER','FEATH-er','feath-ER',0],['FELLOW','FEL-low','fel-LOW',0],['FICTION','FIC-tion','fic-TION',0],
  ['FIFTEEN','FIF-teen','fif-TEEN',0],['FIGURE','FIG-ure','fig-URE',0],['FILTER','FIL-ter','fil-TER',0],
  ['FINAL','FI-nal','fi-NAL',0],['FOCUS','FO-cus','fo-CUS',0],['FOLLOW','FOL-low','fol-LOW',0],
  ['FOOLISH','FOO-lish','foo-LISH',0],['FOREIGN','FOR-eign','for-EIGN',0],['FOREST','FOR-est','for-EST',0],
  ['FORTUNE','FOR-tune','for-TUNE',0],['FOSSIL','FOS-sil','fos-SIL',0],['FRACTION','FRAC-tion','frac-TION',0],
  ['FREEDOM','FREE-dom','free-DOM',0],['FROZEN','FRO-zen','fro-ZEN',0],['FUNCTION','FUNC-tion','func-TION',0],
  ['GALAXY','GA-laxy','ga-LA-xy',0],['GATHER','GATH-er','gath-ER',0],['GLACIER','GLA-cier','gla-CIER',0],
  ['GLOBAL','GLO-bal','glo-BAL',0],['GOLDEN','GOL-den','gol-DEN',0],['GOSSIP','GOS-sip','gos-SIP',0],
  ['GRAMMAR','GRAM-mar','gram-MAR',0],['GRATEFUL','GRATE-ful','grate-FUL',0],['GRAVEL','GRA-vel','gra-VEL',0],
  ['GUILTY','GUIL-ty','guil-TY',0],['HABIT','HA-bit','ha-BIT',0],['HAMMER','HAM-mer','ham-MER',0],
  ['HANDLE','HAN-dle','han-DLE',0],['HARBOR','HAR-bor','har-BOR',0],['HELMET','HEL-met','hel-MET',0],
  ['HIDDEN','HID-den','hid-DEN',0],['HOLLOW','HOL-low','hol-LOW',0],['HONEST','HON-est','hon-EST',0],
  ['HONOR','HON-or','hon-OR',0],['HORROR','HOR-ror','hor-ROR',0],['HOSTAGE','HOS-tage','hos-TAGE',0],
  ['HUMBLE','HUM-ble','hum-BLE',0],['HURDLE','HUR-dle','hur-DLE',0],['ICON','I-con','i-CON',0],
  ['IMPACT','IM-pact','im-PACT',0],['INCOME','IN-come','in-COME',0],['INFANT','IN-fant','in-FANT',0],
  ['INSECT','IN-sect','in-SECT',0],['INSTANT','IN-stant','in-STANT',0],['IRON','I-ron','i-RON',0],
  ['ITEM','I-tem','i-TEM',0],['JOURNEY','JOUR-ney','jour-NEY',0],['JOYFUL','JOY-ful','joy-FUL',0],
  ['JUNGLE','JUN-gle','jun-GLE',0],['JUSTICE','JUS-tice','jus-TICE',0],['KENNEL','KEN-nel','ken-NEL',0],
  ['KINGDOM','KING-dom','king-DOM',0],['KITTEN','KIT-ten','kit-TEN',0],['LABEL','LA-bel','la-BEL',0],
  ['LEGEND','LE-gend','le-GEND',0],['LESSON','LES-son','les-SON',0],['LEVEL','LE-vel','le-VEL',0],
  ['LEMON','LE-mon','le-MON',0],['LIMIT','LI-mit','li-MIT',0],['LIQUID','LI-quid','li-QUID',0],
  ['LOGIC','LO-gic','lo-GIC',0],['LOYAL','LOY-al','loy-AL',0],['LUMBER','LUM-ber','lum-BER',0],
  ['MADNESS','MAD-ness','mad-NESS',0],['MAGIC','MA-gic','ma-GIC',0],['MAIDEN','MAI-den','mai-DEN',0],
  ['MAMMAL','MAM-mal','mam-MAL',0],['MANNER','MAN-ner','man-NER',0],['MARGIN','MAR-gin','mar-GIN',0],
  ['MEDAL','ME-dal','me-DAL',0],['MELON','ME-lon','me-LON',0],['MENTAL','MEN-tal','men-TAL',0],
  ['MERCY','MER-cy','mer-CY',0],['METAL','ME-tal','me-TAL',0],['MINOR','MI-nor','mi-NOR',0],
  ['MISSION','MIS-sion','mis-SION',0],['MOBILE','MO-bile','mo-BILE',0],['MORAL','MO-ral','mo-RAL',0],
  ['MORTAL','MOR-tal','mor-TAL',0],['MUFFIN','MUF-fin','muf-FIN',0],['MUSTARD','MUS-tard','mus-TARD',0],
  ['NAPKIN','NAP-kin','nap-KIN',0],['NATIVE','NA-tive','na-TIVE',0],['NEEDLE','NEE-dle','nee-DLE',0],
  ['NOBLE','NO-ble','no-BLE',0],['NONSENSE','NON-sense','non-SENSE',0],['NOVEL','NO-vel','no-VEL',0],
  ['NUTMEG','NUT-meg','nut-MEG',0],['OCEAN','O-cean','o-CEAN',0],['OMEN','O-men','o-MEN',0],
  ['ORBIT','OR-bit','or-BIT',0],['ORDER','OR-der','or-DER',0],['ORPHAN','OR-phan','or-PHAN',0],
  ['OTTER','OT-ter','ot-TER',0],['OUTER','OU-ter','ou-TER',0],['OUTLET','OUT-let','out-LET',0],
  ['OVEN','O-ven','o-VEN',0],['OVER','O-ver','o-VER',0],['PACKAGE','PACK-age','pack-AGE',0],
  ['PADDLE','PAD-dle','pad-DLE',0],['PANTHER','PAN-ther','pan-THER',0],['PARCEL','PAR-cel','par-CEL',0],
  ['PARTNER','PART-ner','part-NER',0],['PASSION','PAS-sion','pas-SION',0],['PASTURE','PAS-ture','pas-TURE',0],
  ['PATENT','PA-tent','pa-TENT',0],['PEACEFUL','PEACE-ful','peace-FUL',0],['PEBBLE','PEB-ble','peb-BLE',0],
  ['PEDAL','PE-dal','pe-DAL',0],['PENGUIN','PEN-guin','pen-GUIN',0],['PEPPER','PEP-per','pep-PER',0],
  ['PHANTOM','PHAN-tom','phan-TOM',0],['PILLOW','PIL-low','pil-LOW',0],['PIRATE','PI-rate','pi-RATE',0],
  ['PITCHER','PITCH-er','pitch-ER',0],['PLANET','PLA-net','pla-NET',0],['PLASTER','PLAS-ter','plas-TER',0],
  ['PLEASANT','PLEA-sant','plea-SANT',0],['PLUMBER','PLUM-ber','plum-BER',0],['POISON','POI-son','poi-SON',0],
  ['HARVEST','HAR-vest','har-VEST',0],['PUMPKIN','PUMP-kin','pump-KIN',0],['PUPPET','PUP-pet','pup-PET',0],
  ['RABBIT','RAB-bit','rab-BIT',0],['RANDOM','RAN-dom','ran-DOM',0],['RANSOM','RAN-som','ran-SOM',0],
  ['RAPID','RA-pid','ra-PID',0],['RASCAL','RAS-cal','ras-CAL',0],['RAVEN','RA-ven','ra-VEN',0],
  ['REASON','REA-son','rea-SON',0],['RESCUE','RES-cue','res-CUE',0],['RIBBON','RIB-bon','rib-BON',0],
  ['RIDDLE','RID-dle','rid-DLE',0],['RIVER','RI-ver','ri-VER',0],['ROBBER','ROB-ber','rob-BER',0],
  ['ROCKET','ROC-ket','roc-KET',0],['ROSTER','ROS-ter','ros-TER',0],['RUBBER','RUB-ber','rub-BER',0],
  ['RUSTIC','RUS-tic','rus-TIC',0],['SADDLE','SAD-dle','sad-DLE',0],['SAFETY','SAFE-ty','safe-TY',0],
  ['SALMON','SAL-mon','sal-MON',0],['SAMPLE','SAM-ple','sam-PLE',0],['SANDAL','SAN-dal','san-DAL',0],
  ['SATIN','SA-tin','sa-TIN',0],['SAVAGE','SAV-age','sav-AGE',0],['SCATTER','SCAT-ter','scat-TER',0],
  ['SECRET','SE-cret','se-CRET',0],['SELDOM','SEL-dom','sel-DOM',0],['SETTLE','SET-tle','set-TLE',0],
  ['SHADOW','SHA-dow','sha-DOW',0],['SHALLOW','SHAL-low','shal-LOW',0],['SHELTER','SHEL-ter','shel-TER',0],
  ['SIGNAL','SIG-nal','sig-NAL',0],['SILVER','SIL-ver','sil-VER',0],['SIMPLE','SIM-ple','sim-PLE',0],
  ['SINGLE','SIN-gle','sin-GLE',0],['SISTER','SIS-ter','sis-TER',0],['SLENDER','SLEN-der','slen-DER',0],
  ['SLIPPER','SLIP-per','slip-PER',0],['SOCCER','SOC-cer','soc-CER',0],['SOLDIER','SOL-dier','sol-DIER',0],
  ['SOLEMN','SOL-emn','sol-EMN',0],['SPIRAL','SPI-ral','spi-RAL',0],['STANDARD','STAND-ard','stand-ARD',0],
  ['STAPLE','STA-ple','sta-PLE',0],['STEEPLE','STEE-ple','stee-PLE',0],['STOMACH','STO-mach','sto-MACH',0],
  ['STORY','STO-ry','sto-RY',0],['STRUGGLE','STRUG-gle','strug-GLE',0],['SUBJECT','SUB-ject','sub-JECT',0],
  ['SUDDEN','SUD-den','sud-DEN',0],['SUGAR','SU-gar','su-GAR',0],['SUMMON','SUM-mon','sum-MON',0],
  ['SUMMER','SUM-mer','sum-MER',0],['SURFACE','SUR-face','sur-FACE',0],['SURPLUS','SUR-plus','sur-PLUS',0],
  ['SWALLOW','SWAL-low','swal-LOW',0],['SYMBOL','SYM-bol','sym-BOL',0],['SYSTEM','SYS-tem','sys-TEM',0],
  ['TALENT','TA-lent','ta-LENT',0],['TARGET','TAR-get','tar-GET',0],['TEMPLE','TEM-ple','tem-PLE',0],
  ['TENDER','TEN-der','ten-DER',0],['THUNDER','THUN-der','thun-DER',0],['TICKET','TICK-et','tick-ET',0],
  ['TIMBER','TIM-ber','tim-BER',0],['TITLE','TI-tle','ti-TLE',0],['TOKEN','TO-ken','to-KEN',0],
  ['TOPIC','TO-pic','to-PIC',0],['TOWER','TOW-er','tow-ER',0],['TRAVEL','TRA-vel','tra-VEL',0],
  ['TRIGGER','TRIG-ger','trig-GER',0],['TROUBLE','TROU-ble','trou-BLE',0],['TRUMPET','TRUM-pet','trum-PET',0],
  ['TUNNEL','TUN-nel','tun-NEL',0],['TURTLE','TUR-tle','tur-TLE',0],['UNCLE','UN-cle','un-CLE',0],
  ['UPPER','UP-per','up-PER',0],['VALLEY','VAL-ley','val-LEY',0],['VALUE','VA-lue','va-LUE',0],
  ['VELVET','VEL-vet','vel-VET',0],['VESSEL','VES-sel','ves-SEL',0],['VICTIM','VIC-tim','vic-TIM',0],
  ['VILLAGE','VIL-lage','vil-LAGE',0],['VINTAGE','VIN-tage','vin-TAGE',0],['VIRTUE','VIR-tue','vir-TUE',0],
  ['VOLUME','VOL-ume','vol-UME',0],['VULTURE','VUL-ture','vul-TURE',0],['WAFFLE','WAF-fle','waf-FLE',0],
  ['WANDER','WAN-der','wan-DER',0],['WEAPON','WEA-pon','wea-PON',0],['WEATHER','WEATH-er','weath-ER',0],
  ['WHISPER','WHIS-per','whis-PER',0],['WICKED','WICK-ed','wick-ED',0],['WIDOW','WI-dow','wi-DOW',0],
  ['WINDOW','WIN-dow','win-DOW',0],['WINTER','WIN-ter','win-TER',0],['WITNESS','WIT-ness','wit-NESS',0],
  ['WONDER','WON-der','won-DER',0],['WORSHIP','WOR-ship','wor-SHIP',0],['WRINKLE','WRIN-kle','wrin-KLE',0],
  ['YELLOW','YEL-low','yel-LOW',0],['ZEALOUS','ZEA-lous','zea-LOUS',0],['ZIGZAG','ZIG-zag','zig-ZAG',0],
];

// === ADDITIONAL MINIMAL PAIRS (300+) ===
const extraMinimalPairs = [
  // More /ɪ/ vs /iː/
  ['kit','keet','Which has the /ɪ/ sound?',0,'Short.'],['bid','bead','Which has /ɪ/?',0,'Short.'],
  ['did','deed','Which has /ɪ/?',0,'Short.'],['hid','heed','Which has /ɪ/?',0,'Short.'],
  ['lid','lead','Which has /ɪ/?',0,'Short.'],['mid','mead','Which has /ɪ/?',0,'Short.'],
  ['rid','reed','Which has /ɪ/?',0,'Short.'],['id','eed','Which has /ɪ/?',0,'Short.'],
  // More /æ/ vs /ɛ/
  ['had','head','Which has /æ/?',0,'Open front.'],['sad','said','Which has /æ/?',0,'Open front.'],
  ['dad','dead','Which has /æ/?',0,'Open front.'],['ban','Ben','Which has /æ/?',0,'Open front.'],
  ['land','lend','Which has /æ/?',0,'Open front.'],['band','bend','Which has /æ/?',0,'Open front.'],
  ['sand','send','Which has /æ/?',0,'Open front.'],['grand','grend','Which has /æ/?',0,'Open front.'],
  // Consonant voiced vs voiceless final
  ['cab','cap','Which ends voiced?',0,'Vocal cords vibrate.'],['lab','lap','Which ends voiced?',0,'Vibration.'],
  ['tab','tap','Which ends voiced?',0,'Vibration.'],['rib','rip','Which ends voiced?',0,'Vibration.'],
  ['rob','rope','Which ends voiced?',0,'Vibration.'],['mob','mop','Which ends voiced?',0,'Vibration.'],
  ['cub','cup','Which ends voiced?',0,'Vibration.'],['tub','tup','Which ends voiced?',0,'Vibration.'],
  ['pig','pick','Which ends voiced?',0,'Vibration.'],['wig','wick','Which ends voiced?',0,'Vibration.'],
  ['dig','Dick','Which ends voiced?',0,'Vibration.'],['rug','ruck','Which ends voiced?',0,'Vibration.'],
  ['bug','buck','Which ends voiced?',0,'Vibration.'],['mug','muck','Which ends voiced?',0,'Vibration.'],
  ['dog','dock','Which ends voiced?',0,'Vibration.'],['log','lock','Which ends voiced?',0,'Vibration.'],
  ['bag','back','Which ends voiced?',0,'Vibration.'],['tag','tack','Which ends voiced?',0,'Vibration.'],
  ['had','hat','Which ends voiced?',0,'Vibration.'],['mad','mat','Which ends voiced?',0,'Vibration.'],
  ['bad','bat','Which ends voiced?',0,'Vibration.'],['sad','sat','Which ends voiced?',0,'Vibration.'],
  ['red','wet','Which ends voiced?',0,'Vibration.'],['bid','bit','Which ends voiced?',0,'Vibration.'],
  // /ɔː/ vs /ɒ/
  ['caught','cot','Which has /ɔː/?',0,'Long rounded.'],['bought','bot','Which has /ɔː/?',0,'Long.'],
  ['taught','tot','Which has /ɔː/?',0,'Long.'],['nought','not','Which has /ɔː/?',0,'Long.'],
  ['wrought','rot','Which has /ɔː/?',0,'Long.'],['sought','sot','Which has /ɔː/?',0,'Long.'],
  ['thought','thot','Which has /ɔː/?',0,'Long.'],['fought','fot','Which has /ɔː/?',0,'Long.'],
  // /n/ vs /ŋ/
  ['sin','sing','Which has /n/?',0,'Alveolar nasal.'],['thin','thing','Which has /n/?',0,'Alveolar.'],
  ['ban','bang','Which has /n/?',0,'Alveolar.'],['ran','rang','Which has /n/?',0,'Alveolar.'],
  ['win','wing','Which has /n/?',0,'Alveolar.'],['pin','ping','Which has /n/?',0,'Alveolar.'],
  ['kin','king','Which has /n/?',0,'Alveolar.'],['ton','tongue','Which has /n/?',0,'Alveolar.'],
  ['sun','sung','Which has /n/?',0,'Alveolar.'],['run','rung','Which has /n/?',0,'Alveolar.'],
  ['bun','bung','Which has /n/?',0,'Alveolar.'],['din','ding','Which has /n/?',0,'Alveolar.'],
  // /b/ vs /v/
  ['bat','vat','Which starts with /b/?',0,'Bilabial.'],['best','vest','Which starts with /b/?',0,'Bilabial.'],
  ['bent','vent','Which starts with /b/?',0,'Bilabial.'],['berry','very','Which starts with /b/?',0,'Bilabial.'],
  ['bile','vile','Which starts with /b/?',0,'Bilabial.'],['bolt','volt','Which starts with /b/?',0,'Bilabial.'],
  ['bow','vow','Which starts with /b/?',0,'Bilabial.'],['bet','vet','Which starts with /b/?',0,'Bilabial.'],
  ['base','vase','Which starts with /b/?',0,'Bilabial.'],['bale','vale','Which starts with /b/?',0,'Bilabial.'],
  // /dʒ/ vs /ʒ/
  ['major','measure','Which has /dʒ/?',0,'Affricate.'],['danger','azure','Which has /dʒ/?',0,'Affricate.'],
  ['stranger','leisure','Which has /dʒ/?',0,'Affricate.'],['manager','pleasure','Which has /dʒ/?',0,'Affricate.'],
  ['message','massage','Which has /dʒ/?',0,'Affricate.'],['village','mirage','Which has /dʒ/?',0,'Affricate.'],
  ['storage','corsage','Which has /dʒ/?',0,'Affricate.'],['average','collage','Which has /dʒ/?',0,'Affricate.'],
  ['package','camouflage','Which has /dʒ/?',0,'Affricate.'],['garbage','garage','Which has /dʒ/?',0,'Affricate.'],
  // /eɪ/ vs /e/
  ['main','men','Which has /eɪ/?',0,'Diphthong.'],['pain','pen','Which has /eɪ/?',0,'Diphthong.'],
  ['rain','wren','Which has /eɪ/?',0,'Diphthong.'],['plain','glen','Which has /eɪ/?',0,'Diphthong.'],
  ['train','trend','Which has /eɪ/?',0,'Diphthong.'],['brain','blend','Which has /eɪ/?',0,'Diphthong.'],
  ['strain','strength','Which has /eɪ/?',0,'Diphthong.'],['drain','dread','Which has /eɪ/?',0,'Diphthong.'],
  ['grain','Fred','Which has /eɪ/?',0,'Diphthong.'],['crane','credit','Which has /eɪ/?',0,'Diphthong.'],
  ['stain','stem','Which has /eɪ/?',0,'Diphthong.'],['chain','check','Which has /eɪ/?',0,'Diphthong.'],
  ['claim','cleft','Which has /eɪ/?',0,'Diphthong.'],['blame','blend','Which has /eɪ/?',0,'Diphthong.'],
  ['flame','flesh','Which has /eɪ/?',0,'Diphthong.'],['frame','French','Which has /eɪ/?',0,'Diphthong.'],
  ['shame','shelf','Which has /eɪ/?',0,'Diphthong.'],['name','nest','Which has /eɪ/?',0,'Diphthong.'],
  ['game','gem','Which has /eɪ/?',0,'Diphthong.'],['came','kept','Which has /eɪ/?',0,'Diphthong.'],
  // /aɪ/ vs /ɪ/
  ['bite','bit','Which has /aɪ/?',0,'Diphthong.'],['site','sit','Which has /aɪ/?',0,'Diphthong.'],
  ['kite','kit','Which has /aɪ/?',0,'Diphthong.'],['hide','hid','Which has /aɪ/?',0,'Diphthong.'],
  ['ride','rid','Which has /aɪ/?',0,'Diphthong.'],['side','sid','Which has /aɪ/?',0,'Diphthong.'],
  ['mine','min','Which has /aɪ/?',0,'Diphthong.'],['pine','pin','Which has /aɪ/?',0,'Diphthong.'],
  ['wine','win','Which has /aɪ/?',0,'Diphthong.'],['dine','din','Which has /aɪ/?',0,'Diphthong.'],
  ['pike','pick','Which has /aɪ/?',0,'Diphthong.'],['spike','spick','Which has /aɪ/?',0,'Diphthong.'],
  ['strike','strict','Which has /aɪ/?',0,'Diphthong.'],['price','prick','Which has /aɪ/?',0,'Diphthong.'],
  ['slice','slick','Which has /aɪ/?',0,'Diphthong.'],['twice','trick','Which has /aɪ/?',0,'Diphthong.'],
  ['mice','miss','Which has /aɪ/?',0,'Diphthong.'],['nice','nick','Which has /aɪ/?',0,'Diphthong.'],
  ['rice','rich','Which has /aɪ/?',0,'Diphthong.'],['dice','dish','Which has /aɪ/?',0,'Diphthong.'],
  // /h/ present vs absent
  ['heat','eat','Which has /h/?',0,'Initial aspiration.'],['hill','ill','Which has /h/?',0,'Aspiration.'],
  ['hall','all','Which has /h/?',0,'Aspiration.'],['hair','air','Which has /h/?',0,'Aspiration.'],
  ['hear','ear','Which has /h/?',0,'Aspiration.'],['hold','old','Which has /h/?',0,'Aspiration.'],
  ['high','eye','Which has /h/?',0,'Aspiration.'],['hate','eight','Which has /h/?',0,'Aspiration.'],
  ['harm','arm','Which has /h/?',0,'Aspiration.'],['hand','and','Which has /h/?',0,'Aspiration.'],
  ['heart','art','Which has /h/?',0,'Aspiration.'],['heal','eel','Which has /h/?',0,'Aspiration.'],
  ['haste','ace','Which has /h/?',0,'Aspiration.'],['hedge','edge','Which has /h/?',0,'Aspiration.'],
  ['hit','it','Which has /h/?',0,'Aspiration.'],['had','add','Which has /h/?',0,'Aspiration.'],
  ['ham','am','Which has /h/?',0,'Aspiration.'],['hen','end','Which has /h/?',0,'Aspiration.'],
  ['his','is','Which has /h/?',0,'Aspiration.'],['hug','ugly','Which has /h/?',0,'Aspiration.'],
  // /r/ vs /l/ final position
  ['pour','pole','Which ends with /r/?',0,'Retroflex.'],['four','foal','Which ends with /r/?',0,'Retroflex.'],
  ['core','coal','Which ends with /r/?',0,'Retroflex.'],['bore','bowl','Which ends with /r/?',0,'Retroflex.'],
  ['more','mole','Which ends with /r/?',0,'Retroflex.'],['store','stole','Which ends with /r/?',0,'Retroflex.'],
  ['sore','sole','Which ends with /r/?',0,'Retroflex.'],['wore','whole','Which ends with /r/?',0,'Retroflex.'],
  ['fear','feel','Which ends with /r/?',0,'Retroflex.'],['near','kneel','Which ends with /r/?',0,'Retroflex.'],
  ['beer','beel','Which ends with /r/?',0,'Retroflex.'],['dear','deal','Which ends with /r/?',0,'Retroflex.'],
  ['star','stall','Which ends with /r/?',0,'Retroflex.'],['car','call','Which ends with /r/?',0,'Retroflex.'],
  ['far','fall','Which ends with /r/?',0,'Retroflex.'],['bar','ball','Which ends with /r/?',0,'Retroflex.'],
  ['jar','jaw','Which ends with /r/?',0,'Retroflex.'],['tar','tall','Which ends with /r/?',0,'Retroflex.'],
  ['sir','sill','Which ends with /r/?',0,'Retroflex.'],['fur','full','Which ends with /r/?',0,'Retroflex.'],
  // /p/ vs /f/
  ['pail','fail','Which starts with /p/?',0,'Plosive.'],['pair','fair','Which starts with /p/?',0,'Plosive.'],
  ['pale','fail','Which starts with /p/?',0,'Plosive.'],['past','fast','Which starts with /p/?',0,'Plosive.'],
  ['peel','feel','Which starts with /p/?',0,'Plosive.'],['pill','fill','Which starts with /p/?',0,'Plosive.'],
  ['pine','fine','Which starts with /p/?',0,'Plosive.'],['pit','fit','Which starts with /p/?',0,'Plosive.'],
  ['plat','flat','Which starts with /p/?',0,'Plosive.'],['play','flay','Which starts with /p/?',0,'Plosive.'],
  ['plight','flight','Which starts with /p/?',0,'Plosive.'],['plop','flop','Which starts with /p/?',0,'Plosive.'],
  ['pour','four','Which starts with /p/?',0,'Plosive.'],['pox','fox','Which starts with /p/?',0,'Plosive.'],
  ['punk','funk','Which starts with /p/?',0,'Plosive.'],['purr','fur','Which starts with /p/?',0,'Plosive.'],
  // /ð/ vs /d/
  ['they','day','Which has /ð/?',0,'Dental fricative.'],['than','Dan','Which has /ð/?',0,'Dental.'],
  ['there','dare','Which has /ð/?',0,'Dental.'],['though','dough','Which has /ð/?',0,'Dental.'],
  ['that','dab','Which has /ð/?',0,'Dental.'],['the','D','Which has /ð/?',0,'Dental.'],
  ['then','den','Which has /ð/?',0,'Dental.'],['these','disease','Which has /ð/?',0,'Dental.'],
  ['them','deem','Which has /ð/?',0,'Dental.'],['those','dose','Which has /ð/?',0,'Dental.'],
  ['thus','dust','Which has /ð/?',0,'Dental.'],['this','diss','Which has /ð/?',0,'Dental.'],
  ['bathe','bade','Which has /ð/?',0,'Dental.'],['clothe','code','Which has /ð/?',0,'Dental.'],
  ['soothe','sued','Which has /ð/?',0,'Dental.'],['breathe','breed','Which has /ð/?',0,'Dental.'],
  ['lathe','laid','Which has /ð/?',0,'Dental.'],['scathe','skate','Which has /ð/?',0,'Dental.'],
  ['writhe','ride','Which has /ð/?',0,'Dental.'],['tithe','tied','Which has /ð/?',0,'Dental.'],
];

// Now update each pool file to include the extras
function appendToPool(poolPath, extraEntries, formatter) {
  const content = fs.readFileSync(poolPath, 'utf8');
  const insertionPoint = content.lastIndexOf('console.log');
  if (insertionPoint === -1) { console.error('Cannot find insertion point in', poolPath); return; }
  
  let extra = '\n  // === AUTO-EXPANDED ENTRIES ===\n';
  for (const entry of extraEntries) {
    extra += '  pool.push(' + JSON.stringify(formatter(entry)) + ');\n';
  }
  
  const newContent = content.slice(0, insertionPoint) + extra + content.slice(insertionPoint);
  fs.writeFileSync(poolPath, newContent);
  console.log(`Updated ${path.basename(poolPath)}: added ${extraEntries.length} entries`);
}

const poolsDir = path.join(__dirname, 'pools');

// 1. Consonant Clarity
appendToPool(path.join(poolsDir, 'consonant_clarity_pool.js'), extraConsonantClarity, ([word,o1,o2,ans]) => ({
  instruction: 'Which consonant sound?',
  fields: { word, options: [o1,o2], correctAnswerIndex: ans, hint: 'Listen to the consonant carefully.' }
}));

// 2. Word Linking
appendToPool(path.join(poolsDir, 'word_linking_pool.js'), extraWordLinking, (phrase) => ({
  instruction: 'Practice connected speech linking.',
  interactionType: 'speaking',
  fields: { word: phrase, options: ['Linked','Separated'], correctAnswerIndex: 0, hint: 'Connect words smoothly in natural speech.' }
}));

// 3. Shadowing
appendToPool(path.join(poolsDir, 'shadowing_pool.js'), extraShadowing, (sentence) => ({
  instruction: 'Shadow the sentence.',
  interactionType: 'speaking',
  fields: { sentence, options: ['Matched','Not matched'], correctAnswerIndex: 0, hint: 'Listen and repeat simultaneously.', targetSpeed: '1.0x' }
}));

// 4. Syllable Stress
appendToPool(path.join(poolsDir, 'syllable_stress_pool.js'), extraSyllableStress, ([word,o1,o2,ans]) => ({
  instruction: 'Where is the stress?',
  fields: { word, options: [o1,o2], correctAnswerIndex: ans, hint: 'Listen for the loudest syllable.' }
}));

// 5. Minimal Pairs
appendToPool(path.join(poolsDir, 'minimal_pairs_pool.js'), extraMinimalPairs, ([w1,w2,question,ans,hint]) => ({
  instruction: 'Choose the word you hear.',
  fields: { word1:w1, word2:w2, question, options:[w1,w2], correctAnswerIndex:ans, hint }
}));

console.log('\nDone expanding pools. Run accent_regen.js to regenerate.');
