// Grammar question pools - each game needs 600 unique questions (200 levels × 3)
// We generate them programmatically from sentence banks

const S = (q,o,c,h,inst='Choose the correct answer.') => ({instruction:inst,fields:{question:q,options:o,correctAnswerIndex:c,hint:h}});
const R = (q,sw,co,h) => ({instruction:'Reorder the words.',interactionType:'reorder',fields:{question:q,shuffledWords:sw,correctOrder:co,hint:h,sentence:q}});
const V = (q,o,c,h,ps,as) => ({instruction:'Convert the voice.',fields:{question:q,options:o,correctAnswerIndex:c,hint:h,passiveSentence:ps||null,activeSentence:as||null}});

// ── grammarQuest: general grammar MCQ ──
const gqSentences = [
  ["She has two brothers.","She have two brothers.","She has two brothers.","She haves two brothers.","She having two brothers.",1,"'Has' for third person singular."],
  ["They are playing outside.","They is playing outside.","They are playing outside.","They am playing outside.","They be playing outside.",1,"Plural subject uses 'are'."],
  ["I went to school yesterday.","I goed to school yesterday.","I went to school yesterday.","I wented to school yesterday.","I go to school yesterday.",1,"Irregular past tense of 'go'."],
  ["She can swim very well.","She can swims very well.","She can swim very well.","She can swimming very well.","She can swam very well.",1,"Base form after modal verbs."],
  ["The children play in the park.","The childs play in the park.","The children play in the park.","The childrens play in the park.","The children plays in the park.",1,"Irregular plural + verb agreement."],
  ["This is the best movie ever.","This is the most best movie ever.","This is the best movie ever.","This is the more best movie ever.","This is the bestest movie ever.",1,"Superlative of 'good' is 'best'."],
  ["I have been to London twice.","I have went to London twice.","I have been to London twice.","I have go to London twice.","I have going to London twice.",1,"Present perfect uses past participle."],
  ["She told me to wait.","She told me wait.","She told me to wait.","She told me waiting.","She told to me wait.",1,"'Tell someone to do something'."],
  ["We need to buy some milk.","We need buy some milk.","We need to buy some milk.","We need buying some milk.","We needs to buy some milk.",1,"'Need to + base form'."],
  ["He was reading when I arrived.","He was read when I arrived.","He was reading when I arrived.","He reading when I arrived.","He were reading when I arrived.",1,"Past continuous: was + -ing."],
  ["If I were rich, I would travel.","If I was rich, I would travel.","If I were rich, I would travel.","If I am rich, I would travel.","If I be rich, I would travel.",1,"Subjunctive mood uses 'were'."],
  ["Neither Tom nor Jane is here.","Neither Tom nor Jane are here.","Neither Tom nor Jane is here.","Neither Tom or Jane is here.","Neither Tom nor Jane be here.",1,"'Neither...nor' with singular verb."],
  ["She speaks English fluently.","She speak English fluently.","She speaks English fluently.","She speaking English fluently.","She speaked English fluently.",1,"Third person singular adds 's'."],
  ["I wish I had more time.","I wish I have more time.","I wish I had more time.","I wish I has more time.","I wish I having more time.",1,"'Wish' + past tense for unreal present."],
  ["He suggested that we leave early.","He suggested that we left early.","He suggested that we leave early.","He suggested that we leaves early.","He suggested us to leave early.",1,"Subjunctive after 'suggest'."],
  ["The book which I read was good.","The book who I read was good.","The book which I read was good.","The book whom I read was good.","The book whose I read was good.",1,"'Which' for things."],
  ["She would rather stay home.","She would rather stays home.","She would rather stay home.","She would rather staying home.","She would rather to stay home.",1,"'Would rather' + base form."],
  ["By next year, I will have graduated.","By next year, I will graduated.","By next year, I will have graduated.","By next year, I will be graduate.","By next year, I have graduated.",1,"Future perfect tense."],
  ["He apologized for being late.","He apologized for be late.","He apologized for being late.","He apologized to being late.","He apologized of being late.",1,"Preposition + gerund."],
  ["The more you practice, the better you get.","The more you practice, the more better you get.","The more you practice, the better you get.","More you practice, better you get.","The more you practice, the good you get.",1,"Comparative correlative structure."],
  ["She asked me where I lived.","She asked me where I live.","She asked me where I lived.","She asked me where do I live.","She asked me where did I live.",1,"Reported speech: tense shift."],
  ["I am used to waking up early.","I am used to wake up early.","I am used to waking up early.","I used to waking up early.","I am use to waking up early.",1,"'Be used to' + gerund."],
  ["Not only is he smart, but also kind.","Not only he is smart, but also kind.","Not only is he smart, but also kind.","Not only is he smart, and also kind.","Not only he smart, but also kind.",1,"Inversion with 'not only'."],
  ["Had I known, I would have helped.","If I had known, I would helped.","Had I known, I would have helped.","Had I know, I would have helped.","Have I known, I would have helped.",1,"Inverted conditional (third)."],
  ["She insisted on paying the bill.","She insisted to pay the bill.","She insisted on paying the bill.","She insisted for paying the bill.","She insisted in paying the bill.",1,"'Insist on' + gerund."],
  ["It is essential that he be present.","It is essential that he is present.","It is essential that he be present.","It is essential that he being present.","It is essential that he been present.",1,"Subjunctive with 'essential'."],
  ["Scarcely had he left when it rained.","Scarcely he had left when it rained.","Scarcely had he left when it rained.","Scarcely had he leave when it rained.","Scarcely he left when it rained.",1,"Inversion with 'scarcely'."],
  ["Despite being tired, she continued.","Despite she was tired, she continued.","Despite being tired, she continued.","Despite of being tired, she continued.","Despite to be tired, she continued.",1,"'Despite' + gerund/noun."],
  ["He acts as if he were the boss.","He acts as if he is the boss.","He acts as if he were the boss.","He acts as if he was the boss.","He acts like he were the boss.",1,"Subjunctive with 'as if'."],
  ["I'd prefer to walk than drive.","I'd prefer walking than driving.","I'd prefer to walk than drive.","I'd prefer walk than drive.","I'd prefer to walking than driving.",2,"Prefer + infinitive vs gerund."],
  ["No sooner had he arrived than it started.","No sooner he arrived than it started.","No sooner had he arrived than it started.","No sooner had he arrived when it started.","No sooner he had arrived than it started.",2,"No sooner ... than inversion."],
  ["The news is not very good.","The news are not very good.","The news is not very good.","The news be not very good.","The news being not very good.",2,"News is uncountable/singular."],
  ["I look forward to meeting you.","I look forward to meet you.","I look forward to meeting you.","I look forward for meeting you.","I look forward to meeted you.",2,"Look forward to + gerund."],
  ["She is much taller than her sister.","She is more taller than her sister.","She is much taller than her sister.","She is more tall than her sister.","She is taller much than her sister.",2,"Comparative with 'much'."],
  ["He stopped smoking last year.","He stopped to smoke last year.","He stopped smoking last year.","He stop smoking last year.","He stopped to smoking last year.",2,"Stop + gerund for ending habit."],
  ["I remember seeing her before.","I remember to see her before.","I remember seeing her before.","I remember see her before.","I remember seen her before.",2,"Remember + gerund for past memory."],
  ["It's time we went home.","It's time we go home.","It's time we went home.","It's time we going home.","It's time for we go home.",2,"It's time + past simple."],
  ["She had her car repaired.","She had her car repair.","She had her car repaired.","She had repaired her car.","She repaired her car.",2,"Causative have + object + V3."],
  ["I'm not used to this weather.","I'm not used to this weather.","I'm not use to this weather.","I'm not used this weather.","I'm not using to this weather.",1,"Be used to + noun/gerund."],
];
const grammarQuest = gqSentences.map(s => S(s[0],s.slice(1,5),s[5],s[6]));

// ── sentenceCorrection ──
const scData = [
  ["He don't know the answer.","He doesn't know the answer.","Find the error.","doesn't","don't","Third person singular."],
  ["She have been waiting.","She has been waiting.","Fix the verb.","has","have","'Has' for third person."],
  ["They was playing outside.","They were playing outside.","Fix the verb.","were","was","Plural needs 'were'."],
  ["I seen that movie before.","I have seen that movie before.","Fix the tense.","have seen","seen","Present perfect needs 'have'."],
  ["He goed to the store.","He went to the store.","Fix the verb.","went","goed","Irregular past tense."],
  ["Me and him went home.","He and I went home.","Fix the pronoun.","He and I","Me and him","Subject pronouns."],
  ["The dogs is barking loudly.","The dogs are barking loudly.","Fix subject-verb agreement.","are","is","Plural subject."],
  ["She don't want to go.","She doesn't want to go.","Fix the auxiliary.","doesn't","don't","Third person."],
  ["Him and me are friends.","He and I are friends.","Fix the pronouns.","He and I","Him and me","Subject form."],
  ["I have went there before.","I have gone there before.","Fix the participle.","gone","went","Past participle of 'go'."],
  ["She can sings beautifully.","She can sing beautifully.","Fix after modal.","sing","sings","Base form after modals."],
  ["There is many problems.","There are many problems.","Fix the verb.","are","is","Plural noun needs 'are'."],
  ["He brung his lunch today.","He brought his lunch today.","Fix the past tense.","brought","brung","Irregular past tense."],
  ["Her and I went shopping.","She and I went shopping.","Fix the pronoun.","She","Her","Subject pronoun needed."],
  ["The news are shocking today.","The news is shocking today.","Fix the verb.","is","are","'News' is singular."],
  ["Each students must register.","Each student must register.","Fix the noun.","student","students","'Each' + singular."],
  ["Neither option are correct.","Neither option is correct.","Fix the verb.","is","are","'Neither' + singular verb."],
  ["He did not went there.","He did not go there.","Fix after 'did'.","go","went","Base form after 'did'."],
  ["I am more taller than him.","I am taller than him.","Fix the comparative.","taller","more taller","Don't double comparatives."],
  ["She catched the ball easily.","She caught the ball easily.","Fix irregular past.","caught","catched","Irregular verb."],
  ["The informations is incorrect.","The information is incorrect.","Fix the noun.","information","informations","Uncountable noun."],
  ["Between you and I, it's wrong.","Between you and me, it's wrong.","Fix the pronoun.","me","I","Object after preposition."],
  ["He has less friends than me.","He has fewer friends than me.","Fix the quantifier.","fewer","less","'Fewer' for countable nouns."],
  ["Everyone have their own opinion.","Everyone has their own opinion.","Fix the verb.","has","have","'Everyone' is singular."],
  ["She lays down every afternoon.","She lies down every afternoon.","Fix the verb.","lies","lays","'Lie' = recline; 'lay' = put."],
  ["Who's book is this one?","Whose book is this one?","Fix possessive.","Whose","Who's","'Whose' = possession."],
  ["I could of helped you.","I could have helped you.","Fix the auxiliary.","have","of","'Could have', not 'could of'."],
  ["The datas shows improvement.","The data shows improvement.","Fix the noun.","data","datas","'Data' already plural/mass."],
  ["Irregardless, we must proceed.","Regardless, we must proceed.","Fix the word.","Regardless","Irregardless","'Irregardless' is nonstandard."],
  ["She did good on the test.","She did well on the test.","Fix adverb vs adjective.","well","good","Adverb modifies verb."],
  ["He had more better ideas.","He had much better ideas.","Fix double comparative.","much better","more better","Avoid double comparatives."],
  ["She is looking for a job since May.","She has been looking for a job since May.","Fix tense with 'since'.","has been looking","is looking","Present perfect continuous for duration."],
  ["If I was you, I'd go.","If I were you, I'd go.","Fix subjunctive mood.","were","was","Subjunctive 'were' for imaginary states."],
  ["He said he will come.","He said he would come.","Fix reported speech tense.","would","will","Backshift 'will' to 'would'."],
  ["One of the car is broken.","One of the cars is broken.","Fix plural after 'one of'.","cars","car","'One of' + plural noun."],
  ["I am born in 1990.","I was born in 1990.","Fix passive past birth.","was born","am born","Past event."],
  ["The population of India are high.","The population of India is high.","Fix collective singular.","is","are","'Population' is a singular concept here."],
  ["He is addicted for smoking.","He is addicted to smoking.","Fix preposition.","to","for","'Addicted to'."],
  ["She is married with a doctor.","She is married to a doctor.","Fix preposition.","to","with","'Married to'."],
  ["I didn't wrote the letter.","I didn't write the letter.","Fix after 'did'.","write","wrote","Base form after auxiliary 'did'."],
];
const sentenceCorrection = scData.map(d => ({
  instruction: d[2],
  fields: {
    question: `Fix: "${d[0]}"`,
    sentence: d[0],
    correctedPart: d[3],
    incorrectPart: d[4],
    options: [d[1], d[0], d[0].replace(d[4], d[4]+'s'), d[0].replace(d[4], 'very '+d[4])],
    correctAnswerIndex: 0,
    hint: d[5],
    explanation: `"${d[4]}" should be "${d[3]}".`,
  }
}));

// ── wordReorder ──
const wrData = [
  ["The cat sat on the mat","mat the on sat cat The"],
  ["She is reading a book","book a reading is She"],
  ["They went to the park","park the to went They"],
  ["I like eating fresh fruit","fruit fresh eating like I"],
  ["He plays guitar every evening","evening every guitar plays He"],
  ["We should help each other","other each help should We"],
  ["The sun rises in the east","east the in rises sun The"],
  ["Birds fly south in winter","winter in south fly Birds"],
  ["She speaks three languages fluently","fluently languages three speaks She"],
  ["My brother works at a hospital","hospital a at works brother My"],
  ["Please close the door quietly","quietly door the close Please"],
  ["The children are playing outside","outside playing are children The"],
  ["I have never been to Japan","Japan to been never have I"],
  ["She always arrives on time","time on arrives always She"],
  ["The teacher explained the lesson","lesson the explained teacher The"],
  ["We are going to the beach","beach the to going are We"],
  ["He bought a new car","car new a bought He"],
  ["The flowers bloom in spring","spring in bloom flowers The"],
  ["I will finish this tomorrow","tomorrow this finish will I"],
  ["She made a delicious cake","cake delicious a made She"],
  ["The dog chased the cat","cat the chased dog The"],
  ["We enjoy watching movies together","together movies watching enjoy We"],
  ["He can solve difficult problems","problems difficult solve can He"],
  ["The train arrives at noon","noon at arrives train The"],
  ["I need to study harder","harder study to need I"],
  ["She gave him a present","present a him gave She"],
  ["The museum opens at nine","nine at opens museum The"],
  ["They celebrated their anniversary","anniversary their celebrated They"],
  ["I usually walk to school","school to walk usually I"],
  ["The baby is sleeping peacefully","peacefully sleeping is baby The"],
  ["He likes to listen to music","music to listen to likes He"],
  ["She is a very talented singer","singer talented very a is She"],
  ["They are visiting their grandparents today","today grandparents their visiting are They"],
  ["The water is very cold today","today cold very is water The"],
  ["We have a lot of work","work of lot a have We"],
  ["He runs faster than I do","do I than faster runs He"],
  ["She has long black hair","hair black long has She"],
  ["They bought some fresh vegetables","vegetables fresh some bought They"],
  ["I am going to the library","library the to going am I"],
  ["The sun sets in the west","west the in sets sun The"],
  ["He is my best friend ever","ever friend best my is He"],
  ["We watched a scary movie last night","night last movie scary a watched We"],
  ["She plays the piano very well","well very piano the plays She"],
  ["They are going on a trip","trip a on going are They"],
  ["I love to eat Italian food","food Italian eat to love I"],
  ["The sky is blue and clear","clear and blue is sky The"],
  ["He finished his work on time","time on work his finished He"],
  ["She bought a new dress today","today dress new a bought She"],
  ["They live in a big house","house big a in live They"],
  ["I have a brother and a sister","sister a and brother a have I"],
];
const wordReorder = wrData.map(d => {
  const words = d[0].split(' ');
  const shuffled = d[1].split(' ');
  const order = shuffled.map(w => words.indexOf(w));
  return R(d[0], shuffled, order, 'Rearrange to form a sentence.');
});

// ── tenseMastery ──
const tmData = [
  ["She ___ to school every day.","walks","walked","will walk","is walking",0,"Simple present for habits.","walk"],
  ["I ___ my homework yesterday.","finish","finished","will finish","am finishing",1,"Simple past for completed action.","finish"],
  ["They ___ a movie right now.","watch","watched","will watch","are watching",3,"Present continuous for now.","watch"],
  ["He ___ the project by Friday.","completes","completed","will complete","is completing",2,"Future simple with 'will'.","complete"],
  ["She ___ here since 2010.","lives","lived","will live","has lived",3,"Present perfect for duration.","live"],
  ["I ___ when the phone rang.","sleep","slept","was sleeping","have slept",2,"Past continuous interrupted.","sleep"],
  ["By next month, I ___ the course.","finish","finished","will have finished","am finishing",2,"Future perfect.","finish"],
  ["She ___ three books this year.","reads","read","has read","is reading",2,"Present perfect for this period.","read"],
  ["They ___ dinner when we arrived.","cook","cooked","had cooked","are cooking",2,"Past perfect before past event.","cook"],
  ["He ___ English for five years.","studies","studied","has been studying","will study",2,"Present perfect continuous.","study"],
  ["We ___ to Paris next summer.","travel","traveled","will travel","are traveling",2,"Future plans with 'will'.","travel"],
  ["She ___ the dishes every morning.","washes","washed","will wash","is washing",0,"Simple present routine.","wash"],
  ["I ___ that book last week.","read","read","will read","am reading",1,"Simple past completed.","read"],
  ["They ___ for two hours already.","wait","waited","have been waiting","will wait",2,"Present perfect continuous.","wait"],
  ["He ___ to work by bus daily.","goes","went","will go","is going",0,"Simple present habit.","go"],
  ["She ___ a letter when I called.","writes","wrote","was writing","has written",2,"Past continuous at that moment.","write"],
  ["By 2030, technology ___ a lot.","changes","changed","will have changed","is changing",2,"Future perfect prediction.","change"],
  ["I ___ sushi before I went to Japan.","never try","never tried","had never tried","am never trying",2,"Past perfect before past.","try"],
  ["We ___ this project since January.","work on","worked on","have been working on","will work on",2,"Present perfect continuous.","work on"],
  ["She ___ her keys. She can't find them.","loses","lost","has lost","is losing",2,"Present perfect recent result.","lose"],
  ["Tomorrow at 8, I ___ to work.","drive","drove","will be driving","have driven",2,"Future continuous.","drive"],
  ["He ___ his lunch before noon daily.","eats","ate","will eat","has eaten",0,"Simple present routine.","eat"],
  ["They ___ the house last summer.","paint","painted","will paint","are painting",1,"Simple past completed.","paint"],
  ["I ___ about this topic all day.","think","thought","have been thinking","will think",2,"Present perfect continuous.","think"],
  ["She ___ abroad if she saves enough.","travels","traveled","will travel","is traveling",2,"First conditional future.","travel"],
  ["We ___ a great time at the party.","have","had","will have","are having",1,"Simple past narrative.","have"],
  ["He ___ for the exam all week.","prepares","prepared","has been preparing","will prepare",2,"Present perfect continuous.","prepare"],
  ["The concert ___ at 8 PM tonight.","starts","started","will start","is starting",0,"Scheduled event simple present.","start"],
  ["I ___ you since childhood.","know","knew","have known","am knowing",2,"Present perfect duration.","know"],
  ["She ___ when the alarm went off.","sleeps","slept","was sleeping","has slept",2,"Past continuous interrupted.","sleep"],
  ["He ___ dinner for everyone tonight.","cooks","cooked","is cooking","has cooked",2,"Future arrangement."],
  ["By the time you arrive, we ___ finished.","will","will have","have","be",1,"Future perfect."],
  ["I ___ French for three years now.","learn","learned","have been learning","will learn",2,"Present perfect continuous."],
  ["They ___ to the cinema last night.","go","went","gone","going",1,"Simple past."],
  ["She ___ a lot of progress lately.","makes","made","has made","is making",2,"Present perfect for recent change."],
  ["We ___ football when it started to rain.","play","played","were playing","have played",2,"Past continuous."],
  ["If I ___ time, I will help you.","have","had","will have","having",0,"First conditional."],
  ["I ___ never been so surprised.","have","had","am","was",0,"Present perfect."],
  ["She ___ in this office since 2015.","works","worked","has worked","is working",2,"Present perfect duration."],
  ["They ___ here for long.","aren't","weren't","haven't been","won't be",2,"Present perfect negative."],
];
const tenseMastery = tmData.map(d => ({
  instruction: 'Choose the correct tense.',
  fields: {
    question: d[0], options: [d[1],d[2],d[3],d[4]],
    correctAnswerIndex: d[5], hint: d[6], verb: d[7],
    targetTense: d[6].split(' ')[0] + ' ' + (d[6].split(' ')[1]||''),
  }
}));

// ── partsOfSpeech ──
const posData = [
  ["What part of speech is 'quickly' in: 'She ran quickly.'","Noun","Verb","Adverb","Adjective",2,"Modifies the verb 'ran'.","quickly"],
  ["Identify 'beautiful' in: 'A beautiful sunset.'","Noun","Adjective","Adverb","Verb",1,"Describes the noun 'sunset'.","beautiful"],
  ["What is 'they' in: 'They are coming.'","Pronoun","Noun","Verb","Adjective",0,"Replaces a noun.","they"],
  ["Identify 'running' in: 'He is running fast.'","Noun","Adjective","Verb","Adverb",2,"Part of present continuous.","running"],
  ["What is 'under' in: 'The cat is under the table.'","Noun","Verb","Preposition","Adverb",2,"Shows position.","under"],
  ["Identify 'joy' in: 'Joy filled the room.'","Verb","Noun","Adjective","Adverb",1,"Names an emotion.","joy"],
  ["What is 'and' in: 'Tom and Jerry.'","Preposition","Conjunction","Noun","Pronoun",1,"Connects two nouns.","and"],
  ["Identify 'Wow' in: 'Wow! That's amazing!'","Noun","Verb","Interjection","Adverb",2,"Expresses emotion.","Wow"],
  ["What is 'carefully' in: 'Drive carefully.'","Adjective","Adverb","Noun","Verb",1,"Modifies the verb 'drive'.","carefully"],
  ["Identify 'the' in: 'The dog barked.'","Pronoun","Article","Noun","Verb",1,"Definite article.","the"],
  ["What is 'swim' in: 'I like to swim.'","Noun","Adjective","Verb","Adverb",2,"Action word.","swim"],
  ["Identify 'his' in: 'His car is red.'","Pronoun","Adjective","Noun","Article",0,"Possessive pronoun.","his"],
  ["What is 'between' in: 'Sit between us.'","Adverb","Conjunction","Preposition","Noun",2,"Shows relationship.","between"],
  ["Identify 'happy' in: 'She looks happy.'","Noun","Verb","Adverb","Adjective",3,"Describes feeling.","happy"],
  ["What is 'slowly' in: 'Walk slowly.'","Adjective","Adverb","Verb","Noun",1,"Modifies 'walk'.","slowly"],
  ["Identify 'but' in: 'Smart but lazy.'","Preposition","Conjunction","Adverb","Noun",1,"Contrasting connector.","but"],
  ["What is 'freedom' in: 'Freedom is precious.'","Verb","Adjective","Noun","Adverb",2,"Abstract noun.","freedom"],
  ["Identify 'Oh' in: 'Oh, I see!'","Noun","Interjection","Adverb","Verb",1,"Expresses realization.","Oh"],
  ["What is 'extremely' in: 'Extremely hot day.'","Adjective","Noun","Adverb","Verb",2,"Modifies adjective 'hot'.","extremely"],
  ["Identify 'we' in: 'We love pizza.'","Noun","Pronoun","Adjective","Verb",1,"First person plural pronoun.","we"],
  ["What is 'above' in: 'Above the clouds.'","Noun","Verb","Preposition","Adjective",2,"Shows position.","above"],
  ["Identify 'tall' in: 'A tall building.'","Noun","Verb","Adverb","Adjective",3,"Describes the building.","tall"],
  ["What is 'sing' in: 'They sing well.'","Noun","Adverb","Verb","Adjective",2,"Action word.","sing"],
  ["Identify 'always' in: 'She always smiles.'","Adjective","Adverb","Verb","Noun",1,"Frequency adverb.","always"],
  ["What is 'or' in: 'Tea or coffee?'","Preposition","Conjunction","Noun","Adverb",1,"Gives alternatives.","or"],
  ["Identify 'these' in: 'These are mine.'","Verb","Pronoun","Adjective","Noun",1,"Demonstrative pronoun.","these"],
  ["What is 'honestly' in: 'Speak honestly.'","Adjective","Noun","Adverb","Verb",2,"Modifies 'speak'.","honestly"],
  ["Identify 'during' in: 'During the storm.'","Conjunction","Preposition","Adverb","Noun",1,"Shows time relation.","during"],
  ["What is 'Ouch' in: 'Ouch! That hurt!'","Verb","Adjective","Interjection","Noun",2,"Expresses pain.","Ouch"],
  ["Identify 'many' in: 'Many students passed.'","Adverb","Adjective","Noun","Verb",1,"Quantifier/adjective.","many"],
  ["What is 'about' in: 'Tell me about it.'","Noun","Verb","Preposition","Adverb",2,"Shows relationship."],
  ["Identify 'extremely' in: 'It's extremely hot.'","Adjective","Adverb","Noun","Verb",1,"Modifies an adjective."],
  ["What is 'because' in: 'I went because I was invited.'","Preposition","Conjunction","Noun","Adverb",1,"Connects clauses."],
  ["Identify 'ours' in: 'The choice is ours.'","Personal Pronoun","Possessive Pronoun","Adjective","Noun",1,"Shows possession."],
  ["What is 'strong' in: 'He is a strong man.'","Noun","Verb","Adjective","Adverb",2,"Describes a noun."],
  ["Identify 'well' in: 'She sings well.'","Adjective","Adverb","Noun","Verb",1,"Modifies a verb."],
  ["What is 'since' in: 'I haven't seen him since Monday.'","Conjunction","Preposition","Adverb","Noun",1,"Shows time starting point."],
  ["Identify 'each' in: 'Each person matters.'","Pronoun","Adjective","Verb","Adverb",1,"Determiner."],
  ["What is 'if' in: 'I'll go if you go.'","Preposition","Conjunction","Noun","Verb",1,"Conditional connector."],
  ["Identify 'slowly' in: 'The snail moved slowly.'","Adjective","Adverb","Noun","Verb",1,"Modifies the movement."],
];
const partsOfSpeech = posData.map(d => ({
  instruction: 'Identify the part of speech.',
  fields: {
    question: d[0], options: [d[1],d[2],d[3],d[4]],
    correctAnswerIndex: d[5], hint: d[6], targetWord: d[7],
  }
}));

// ── subjectVerbAgreement ──
const svaData = [
  ["The team ___ playing well.","is","are",0,"Collective noun = singular."],
  ["Neither of them ___ ready.","is","are",0,"'Neither of' = singular."],
  ["The students ___ studying hard.","is","are",1,"Plural subject."],
  ["Each of the boys ___ a prize.","has","have",0,"'Each' = singular."],
  ["Mathematics ___ my favorite subject.","is","are",0,"Subject name = singular."],
  ["The news ___ very surprising.","is","are",0,"'News' = singular."],
  ["The police ___ investigating.","is","are",1,"'Police' = plural."],
  ["Bread and butter ___ my breakfast.","is","are",0,"Combined = one concept."],
  ["One of the cars ___ broken.","is","are",0,"'One of' = singular."],
  ["The committee ___ decided unanimously.","has","have",0,"Collective = singular."],
  ["Measles ___ a childhood disease.","is","are",0,"Disease name = singular."],
  ["Five miles ___ a long distance.","is","are",0,"Distance = singular concept."],
  ["The scissors ___ on the table.","is","are",1,"'Scissors' = plural."],
  ["Either he or they ___ coming.","is","are",1,"Nearest subject = plural."],
  ["The furniture ___ very old.","is","are",0,"Uncountable = singular."],
  ["Many a student ___ failed.","has","have",0,"'Many a' = singular verb."],
  ["The United States ___ large.","is","are",0,"Country name = singular."],
  ["Physics ___ difficult but rewarding.","is","are",0,"Subject name = singular."],
  ["Every boy and girl ___ a book.","has","have",0,"'Every' = singular."],
  ["The pair of shoes ___ new.","is","are",0,"'Pair' = singular."],
  ["No news ___ good news.","is","are",0,"'News' = singular."],
  ["The audience ___ clapping loudly.","is","are",0,"Collective = singular."],
  ["A number of people ___ waiting.","is","are",1,"'A number of' = plural."],
  ["The number of students ___ growing.","is","are",0,"'The number of' = singular."],
  ["Either she or I ___ going.","am","is",0,"Nearest subject = I."],
  ["Tom, along with his friends, ___ here.","is","are",0,"Main subject is singular."],
  ["The trousers ___ too tight.","is","are",1,"'Trousers' = plural."],
  ["Economics ___ an interesting field.","is","are",0,"Subject name = singular."],
  ["Not only he but also they ___ happy.","is","are",1,"Nearest subject rule."],
  ["Ten dollars ___ too much for this.","is","are",0,"Amount = singular concept."],
  ["A large amount of money ___ spent.","was","were",0,"Amount of money is singular."],
  ["The CEO and the Manager ___ present.","is","are",1,"Two distinct people."],
  ["Some of the milk ___ spilled.","is","are",0,"Uncountable partitive."],
  ["Most of the books ___ interesting.","is","are",1,"Countable partitive plural."],
  ["None of the work ___ done.","was","were",0,"None of + uncountable = singular."],
  ["None of the students ___ finished.","has","have",1,"None of + plural = plural (informal/standard)."],
  ["Politics ___ a complex game.","is","are",0,"Plural-form singular nouns."],
  ["The crew ___ ready for takeoff.","is","are",0,"Collective noun unit."],
  ["There ___ a pen and a book.","is","are",1,"Compound subject after 'there'."],
  ["Half of the apple ___ eaten.","is","are",0,"Part of singular."],
  ["Half of the apples ___ rotten.","is","are",1,"Part of plural."],
  ["The quality of the fruits ___ good.","is","are",0,"Subject is 'quality'."],
  ["Neither the teacher nor the students ___ there.","was","were",1,"Nearest subject 'students'."],
  ["Both of my parents ___ here.","is","are",1,"'Both' is always plural."],
  ["Everything ___ going according to plan.","is","are",0,"Indefinite pronouns are singular."],
];
const subjectVerbAgreement = svaData.map(d => ({
  instruction: 'Choose the correct verb.',
  fields: {
    question: d[0], options: [d[1],d[2]], correctAnswerIndex: d[3], hint: d[4],
    sentence: d[0],
  }
}));

// ── clauseConnector ──
const ccData = [
  ["I was tired ___ I went to bed early.","so","but","because","although",0,"Cause → result."],
  ["She studied hard ___ she passed the exam.","but","and","although","so",1,"Addition/sequence."],
  ["___ it was raining, we went outside.","Because","Although","So","And",1,"Contrast/concession."],
  ["He is smart ___ hardworking.","but","and","or","so",1,"Adding qualities."],
  ["Would you like tea ___ coffee?","and","but","or","so",2,"Giving alternatives."],
  ["I'll wait ___ you come back.","until","although","because","but",0,"Time clause."],
  ["___ he apologized, she forgave him.","Although","After","But","Or",1,"Time sequence."],
  ["She sings ___ she dances beautifully.","but","and","or","because",1,"Adding two actions."],
  ["He failed ___ he didn't study enough.","although","and","so","because",3,"Reason/cause."],
  ["Take an umbrella ___ it rains.","although","in case","but","and",1,"Precaution."],
  ["___ arriving late, he apologized.","Although","Upon","But","Or",1,"Time/manner."],
  ["I like summer ___ I prefer winter.","and","but","so","because",1,"Contrast."],
  ["She left early ___ avoid the traffic.","in order to","although","because","but",0,"Purpose."],
  ["___ you finish, please call me.","Although","When","But","And",1,"Time clause."],
  ["He is rich ___ unhappy.","and","yet","so","because",1,"Contrast despite expectation."],
  ["I'll go ___ you go too.","unless","although","but","if",3,"Condition."],
  ["She smiled ___ she was sad inside.","because","even though","so","and",1,"Concession."],
  ["Finish your homework ___ go play.","but","then","although","because",1,"Sequence."],
  ["I stayed home ___ I was sick.","but","and","because","although",2,"Reason."],
  ["He ran fast ___ he missed the bus.","and","but","so","because",1,"Unexpected result."],
  ["___ the weather was bad, we went out.","Because","Despite","Although","So",2,"Concession."],
  ["Not only smart ___ also kind.","and","but","or","yet",1,"Correlative conjunction."],
  ["She ate lunch ___ going to work.","after","before","although","because",1,"Time order."],
  ["I trust him ___ he is honest.","but","although","because","yet",2,"Reason."],
  ["You must hurry ___ you'll be late.","and","or","but","because",1,"Warning/alternative."],
  ["___ studying all night, he failed.","Despite","Because","So","And",0,"Concession."],
  ["She's talented, ___ she's also modest.","but","and","or","so",1,"Addition."],
  ["Call me ___ you need help.","although","whenever","but","so",1,"Time/frequency."],
  ["He neither called ___ texted me.","and","or","nor","but",2,"Correlative: neither...nor."],
  ["Let's leave now ___ we miss the train.","lest","and","but","because",0,"Purpose/avoidance."],
];
const clauseConnector = ccData.map(d => ({
  instruction: 'Choose the correct connector.',
  fields: {
    question: d[0], options: [d[1],d[2],d[3],d[4]],
    correctAnswerIndex: d[5], hint: d[6],
    firstClause: d[0].split('___')[0].trim(),
    secondClause: d[0].split('___')[1]?.trim() || '',
  }
}));

// ── voiceSwap ──
const vsData = [
  ["The cat chased the mouse.","The mouse was chased by the cat.","Active → Passive"],
  ["A cake was baked by Mom.","Mom baked a cake.","Passive → Active"],
  ["She wrote a beautiful poem.","A beautiful poem was written by her.","Active → Passive"],
  ["The letter was sent by Tom.","Tom sent the letter.","Passive → Active"],
  ["They are building a new bridge.","A new bridge is being built by them.","Active → Passive"],
  ["The song was sung by the choir.","The choir sang the song.","Passive → Active"],
  ["He painted the fence white.","The fence was painted white by him.","Active → Passive"],
  ["The window was broken by the ball.","The ball broke the window.","Passive → Active"],
  ["She teaches English every day.","English is taught by her every day.","Active → Passive"],
  ["The book was read by thousands.","Thousands read the book.","Passive → Active"],
  ["We will complete the task soon.","The task will be completed by us soon.","Active → Passive"],
  ["The car was repaired by the mechanic.","The mechanic repaired the car.","Passive → Active"],
  ["He has finished the assignment.","The assignment has been finished by him.","Active → Passive"],
  ["The cake was eaten by the children.","The children ate the cake.","Passive → Active"],
  ["She is cooking dinner right now.","Dinner is being cooked by her right now.","Active → Passive"],
  ["The film was directed by Spielberg.","Spielberg directed the film.","Passive → Active"],
  ["I will send the package tomorrow.","The package will be sent by me tomorrow.","Active → Passive"],
  ["The painting was admired by everyone.","Everyone admired the painting.","Passive → Active"],
  ["They had already solved the problem.","The problem had already been solved by them.","Active → Passive"],
  ["The house was designed by an architect.","An architect designed the house.","Passive → Active"],
  ["She can speak four languages.","Four languages can be spoken by her.","Active → Passive"],
  ["The homework was completed by all students.","All students completed the homework.","Passive → Active"],
  ["People celebrate festivals with joy.","Festivals are celebrated with joy by people.","Active → Passive"],
  ["The novel was written by Dickens.","Dickens wrote the novel.","Passive → Active"],
  ["He must finish the report today.","The report must be finished by him today.","Active → Passive"],
  ["The tree was planted by volunteers.","Volunteers planted the tree.","Passive → Active"],
  ["She has been teaching for ten years.","Students have been taught by her for ten years.","Active → Passive"],
  ["The prize was won by our team.","Our team won the prize.","Passive → Active"],
  ["The children are flying kites.","Kites are being flown by the children.","Active → Passive"],
  ["A new policy was announced by the CEO.","The CEO announced a new policy.","Passive → Active"],
];
const voiceSwap = vsData.map(d => ({
  instruction: d[2],
  fields: {
    question: `Convert: "${d[0]}"`,
    options: [d[1], d[0], d[0]+' (no change)', d[1].replace(' by ',' from ')],
    correctAnswerIndex: 0,
    hint: d[2], passiveSentence: d[2].includes('Passive') ? d[0] : d[1],
    activeSentence: d[2].includes('Active') ? d[0] : d[1],
    explanation: d[1],
  }
}));

// ── questionFormatter ──
const qfData = [
  ["She likes ice cream.","Does she like ice cream?","Yes/No question"],
  ["They went to school.","Did they go to school?","Past tense question"],
  ["He is a doctor.","Is he a doctor?","Be-verb question"],
  ["She can swim well.","Can she swim well?","Modal question"],
  ["They have finished lunch.","Have they finished lunch?","Perfect tense question"],
  ["He lives in London.","Where does he live?","Wh-question"],
  ["She bought three books.","How many books did she buy?","Quantity question"],
  ["They arrived yesterday.","When did they arrive?","Time question"],
  ["He was reading a novel.","What was he reading?","Object question"],
  ["She studies because she loves learning.","Why does she study?","Reason question"],
  ["Tom broke the window.","Who broke the window?","Subject question"],
  ["She is cooking dinner.","Is she cooking dinner?","Present continuous"],
  ["They will come tomorrow.","Will they come tomorrow?","Future question"],
  ["He has been working here.","Has he been working here?","Perfect continuous"],
  ["She speaks French fluently.","Does she speak French fluently?","Yes/No question"],
  ["They were playing outside.","Were they playing outside?","Past continuous"],
  ["He should apologize.","Should he apologize?","Modal question"],
  ["She traveled by train.","How did she travel?","Manner question"],
  ["They live on Main Street.","Where do they live?","Place question"],
  ["He will have finished by then.","Will he have finished by then?","Future perfect"],
  ["I am going to the store.","Am I going to the store?","Be-verb question"],
  ["She must complete the form.","Must she complete the form?","Modal question"],
  ["They ate pizza for dinner.","What did they eat for dinner?","Object question"],
  ["He runs five miles daily.","How far does he run daily?","Distance question"],
  ["She was born in Paris.","Where was she born?","Place question"],
  ["They have been waiting long.","How long have they been waiting?","Duration question"],
  ["He could solve the problem.","Could he solve the problem?","Modal question"],
  ["She drives to work daily.","Does she drive to work daily?","Yes/No question"],
  ["They met at the cafe.","Where did they meet?","Place question"],
  ["He is reading Tom's book.","Whose book is he reading?","Possessive question"],
];
const questionFormatter = qfData.map(d => ({
  instruction: d[2],
  fields: {
    question: `Convert to a question: "${d[0]}"`,
    sentence: d[0],
    options: [d[1], d[0]+'?', 'Do '+d[0].toLowerCase(), d[0].replace('.','?')],
    correctAnswerIndex: 0,
    hint: d[2],
    explanation: d[1],
  }
}));

// ── articleInsertion ──
const aiData = [
  ["I saw ___ elephant at the zoo.","a","an","the","no article",1,"Vowel sound = 'an'."],
  ["___ sun rises in the east.","A","An","The","No article",2,"Unique object = 'the'."],
  ["She is ___ honest person.","a","an","the","no article",1,"Silent 'h' = vowel sound."],
  ["I need ___ glass of water.","a","an","the","no article",0,"Consonant sound = 'a'."],
  ["He plays ___ guitar beautifully.","a","an","the","no article",2,"Musical instruments use 'the'."],
  ["___ Mount Everest is very tall.","A","An","The","No article",3,"Proper noun of mountain."],
  ["She wants to be ___ engineer.","a","an","the","no article",1,"Vowel sound = 'an'."],
  ["___ milk is good for health.","A","An","The","No article",3,"General uncountable = no article."],
  ["I bought ___ umbrella yesterday.","a","an","the","no article",1,"Vowel sound = 'an'."],
  ["He is ___ tallest boy in class.","a","an","the","no article",2,"Superlative uses 'the'."],
  ["___ honesty is the best policy.","A","An","The","No article",3,"Abstract noun = no article."],
  ["She ate ___ apple for lunch.","a","an","the","no article",1,"Vowel sound = 'an'."],
  ["We visited ___ Eiffel Tower.","a","an","the","no article",2,"Famous landmark = 'the'."],
  ["___ water in this bottle is cold.","A","An","The","No article",2,"Specific water = 'the'."],
  ["He is ___ European tourist.","a","an","the","no article",0,"'European' starts with /j/ sound."],
  ["I have ___ dog and ___ cat.","a...a","an...an","the...the","a...an",0,"Consonant sounds = 'a'."],
  ["___ Pacific Ocean is vast.","A","An","The","No article",2,"Ocean names use 'the'."],
  ["She gave me ___ useful tip.","a","an","the","no article",0,"'Useful' starts with /j/ sound."],
  ["He wants ___ hour to rest.","a","an","the","no article",1,"Silent 'h' in 'hour'."],
  ["___ gold is a precious metal.","A","An","The","No article",3,"General material = no article."],
  ["Please pass me ___ salt.","a","an","the","no article",2,"Specific item = 'the'."],
  ["She is ___ university student.","a","an","the","no article",0,"'University' = /j/ sound."],
  ["___ Earth revolves around ___ Sun.","A...a","An...an","The...the","No article",2,"Unique objects = 'the'."],
  ["I need ___ new pair of shoes.","a","an","the","no article",0,"Consonant sound = 'a'."],
  ["___ Amazon is a long river.","A","An","The","No article",2,"River names use 'the'."],
  ["He is ___ one-year-old baby.","a","an","the","no article",0,"'One' starts with /w/ sound."],
  ["___ happiness cannot be bought.","A","An","The","No article",3,"Abstract noun = no article."],
  ["She lives in ___ United States.","a","an","the","no article",2,"Country with 'United' = 'the'."],
  ["I saw ___ owl in the garden.","a","an","the","no article",1,"Vowel sound = 'an'."],
  ["___ lunch is ready now.","A","An","The","No article",3,"Meal names = no article."],
];
const articleInsertion = aiData.map(d => ({
  instruction: 'Select the correct article.',
  fields: {
    question: d[0], options: [d[1],d[2],d[3],d[4]],
    correctAnswerIndex: d[5], hint: d[6],
    sentenceWithBlank: d[0], articleToInsert: [d[1],d[2],d[3],d[4]][d[5]],
  }
}));

// ── modifierPlacement ──
const mpData = [
  ["Choose the correct sentence.","The red car is fast.","The car red is fast.","Red the car is fast.","Fast the car red is.",0,"Adjectives come before nouns."],
  ["Choose the correct sentence.","She has a beautiful voice.","She has a voice beautiful.","Beautiful she has a voice.","She voice a beautiful has.",0,"Noun-adjective order."],
  ["Choose the correct sentence.","He runs quickly.","He quickly runs.","Both A and B are correct.","Quickly he runs.",2,"Adverb placement."],
  ["Which is correct?","A small wooden box.","A wooden small box.","A box small wooden.","Small a box wooden.",0,"Size before material."],
  ["Identify the correct order.","An expensive gold ring.","A gold expensive ring.","A ring expensive gold.","Expensive a ring gold.",0,"Opinion before material."],
  ["Choose the correct sentence.","She is always happy.","She always is happy.","Always she is happy.","She is happy always.",0,"Frequency adverb after 'be'."],
  ["Which sentence is correct?","He is old enough.","He is enough old.","Enough he is old.","He enough is old.",0,"'Enough' after adjective."],
  ["Choose the correct sentence.","We have enough time.","We have time enough.","Enough we have time.","We enough have time.",0,"'Enough' before noun."],
  ["Which avoids ambiguity?","While walking, I saw a bird.","While walking, the bird saw me.","Walking, the bird saw I.","I saw while walking bird.",0,"Dangling modifier fix."],
  ["Choose the correct sentence.","She only eats vegetables.","Only she eats vegetables.","She eats only vegetables.","All are correct depending on meaning.",3,"Placement of 'only'."],
  ["Identify the correct order.","A big round metal table.","A round big metal table.","A metal big round table.","A big metal round table.",0,"Size > Shape > Material."],
  ["Which is correct?","I almost finished my homework.","I finished almost my homework.","Almost I finished my homework.","I finished my homework almost.",0,"'Almost' modifies the verb."],
  ["Choose the correct sentence.","He rarely goes out.","He goes out rarely.","Rarely he goes out.","Both A and B.",3,"Frequency adverb placement."],
  ["Which is correct?","The person who is sitting there is my friend.","The person sitting there is my friend.","Both A and B.","Neither A nor B.",2,"Relative clause reduction."],
  ["Choose the correct sentence.","She specifically asked for you.","She asked specifically for you.","Specifically she asked for you.","All are correct.",3,"Specific adverb placement."],
  ["Choose the correct sentence.","I nearly missed the bus.","I missed nearly the bus.","Nearly I missed the bus.","I missed the bus nearly.",0,"Placement of degree adverb."],
  ["Which is correct?","He speaks English well.","He speaks well English.","Well he speaks English.","He well speaks English.",0,"Adverb of manner placement."],
  ["Identify the correct order.","A long interesting book.","An interesting long book.","A book long interesting.","Long an interesting book.",1,"Opinion before physical."],
  ["Choose the correct sentence.","She hardly ever complains.","She ever hardly complains.","Hardly she ever complains.","She complains hardly ever.",0,"Frequency adverb placement."],
  ["Which is correct?","Only I saw him.","I saw only him.","I only saw him.","All are correct (meanings vary).",3,"'Only' placement."],
  ["Choose the correct sentence.","He is too young.","He is young too.","Too he is young.","He too is young.",0,"'Too' before adjective."],
  ["Identify the correct order.","A cheap blue shirt.","A blue cheap shirt.","A shirt blue cheap.","Blue a cheap shirt.",0,"Opinion before color."],
  ["Choose the correct sentence.","I've already seen it.","I've seen it already.","Already I've seen it.","Both A and B.",3,"Adverb of time placement."],
  ["Which is correct?","She sang beautifully.","She beautifully sang.","Beautifully she sang.","All are correct.",3,"Manner adverb flexibility."],
  ["Identify the correct order.","A shiny new coin.","A new shiny coin.","A coin shiny new.","Shiny a new coin.",0,"Opinion before age."],
  ["Choose the correct sentence.","He almost always wins.","He always almost wins.","Almost he always wins.","He wins almost always.",0,"Modifying another adverb."],
  ["Which is correct?","It's very cold.","It's cold very.","Very it's cold.","It very is cold.",0,"Degree adverb before adjective."],
  ["Choose the correct sentence.","We usually go there.","Usually we go there.","We go there usually.","All are correct.",3,"Frequency adverb flexibility."],
  ["Identify the correct order.","An old Italian man.","An Italian old man.","A man old Italian.","Old an Italian man.",0,"Age before origin."],
  ["Choose the correct sentence.","I haven't seen him yet.","I haven't yet seen him.","Yet I haven't seen him.","Both A and B.",0,"'Yet' usually at the end."],
];
const modifierPlacement = mpData.map(d => S(d[0], d.slice(1,5), d[5], d[6]));

// ── conditionals ──
const clData = [
  ["If you heat ice, it ___.","melts","melted","will melt","melting",0,"Zero conditional: facts.","melts"],
  ["If it ___ tomorrow, we'll stay home.","rains","rain","will rain","rained",0,"First conditional: if + present.","rains"],
  ["If I ___ you, I would go.","were","was","am","be",0,"Second conditional: hypothetical.","were"],
  ["If she ___ harder, she would have passed.","had studied","studied","has studied","would study",0,"Third conditional: past.","had studied"],
  ["If you don't hurry, you ___ the bus.","will miss","miss","missed","missing",0,"First conditional consequence.","will miss"],
  ["If I won the lottery, I ___ travel.","would","will","shall","can",0,"Second conditional result.","would"],
  ["What ___ you do if you saw a ghost?","would","will","do","did",0,"Hypothetical question.","would"],
  ["If I ___ more time, I would help.","had","have","has","having",0,"Second conditional condition.","had"],
  ["If you ___ oil to water, it floats.","add","added","will add","adding",0,"Zero conditional: science.","add"],
  ["I ___ have come if I had known.","would","will","should","might",0,"Third conditional result.","would"],
  ["If she ___ busy, she would be here.","weren't","wasn't","isn't","not be",0,"Second conditional negative.","weren't"],
  ["Unless you ___ now, you'll be late.","leave","don't leave","will leave","left",0,"'Unless' means 'if not'.","leave"],
  ["If I ___ a bird, I would fly.","were","was","am","be",0,"Hypothetical state.","were"],
  ["I would have called if I ___ my phone.","hadn't lost","didn't lose","haven't lost","not lost",0,"Third conditional negative.","hadn't lost"],
  ["If you ___ hard, you will succeed.","work","worked","will work","working",0,"First conditional condition.","work"],
  ["If it ___ tonight, we can ski tomorrow.","snows","snow","will snow","snowed",0,"First conditional condition."],
  ["What would you do if you ___ your job?","lost","lose","will lose","had lost",0,"Second conditional hypotheticals."],
  ["If I ___ more, I would have known.","had read","read","has read","would read",0,"Third conditional past perfect."],
  ["Water ___ if the temperature falls below 0.","freezes","freeze","will freeze","frozen",0,"Zero conditional facts."],
  ["If she ___ the map, she wouldn't have got lost.","had followed","followed","follows","has followed",0,"Third conditional."],
  ["I ___ buy a house if I had the money.","would","will","could","can",0,"Second conditional consequence."],
  ["If you ___ red and blue, you get purple.","mix","mixed","will mix","mixing",0,"Zero conditional."],
  ["Unless he ___ now, he will miss the flight.","leaves","leave","doesn't leave","will leave",0,"Unless + present."],
  ["If I ___ a million dollars, I'd donate it.","had","have","has","will have",0,"Second conditional."],
  ["If they ___ sooner, they would have caught him.","had arrived","arrived","arrive","have arrived",0,"Third conditional."],
  ["If it ___ rain, we'll go for a walk.","doesn't","don't","won't","didn't",0,"First conditional negative."],
  ["I'd go out if I ___ so tired.","weren't","wasn't","isn't","not be",0,"Second conditional negative."],
  ["If you ___ a mistake, just correct it.","make","made","will make","making",0,"First conditional/imperative."],
  ["Had she ___ the truth, she would have been mad.","known","know","knows","knew",0,"Inverted third conditional."],
  ["If I ___ you, I wouldn't worry.","were","was","am","be",0,"Subjunctive mood."],
];
const conditionals = clData.map(d => S(d[0], d.slice(1,5), d[5], d[6]));

// ── directIndirectSpeech ──
const disData = [
  ["He said, \"I am tired.\" (Reported)","He said that he was tired.","He said that he is tired.","He said that I am tired.","He says that he was tired.",0,"Tense shift: am → was."],
  ["She asked, \"Where do you live?\"","She asked where I lived.","She asked where do I live.","She asked where did I live.","She asked where I live.",0,"Question shift in reported speech."],
  ["They said, \"We will come.\"","They said that they would come.","They said that they will come.","They said that we will come.","They said that they come.",0,"Will → would."],
  ["He said, \"I have finished.\"","He said that he had finished.","He said that he has finished.","He said that he finished.","He said that he finishes.",0,"Have → had."],
  ["She said, \"I saw him yesterday.\"","She said she had seen him the day before.","She said she saw him yesterday.","She said she seen him yesterday.","She said she has seen him.",0,"Past → Past Perfect + time shift."],
  ["He asked, \"Can you help me?\"","He asked if I could help him.","He asked if I can help him.","He asked to help him.","He asked if he can help me.",0,"Can → could + if/whether."],
  ["She said, \"Don't go!\"","She told me not to go.","She said me not to go.","She told me don't go.","She said to not go.",0,"Imperative: told + not + to."],
  ["They asked, \"Are you happy?\"","They asked if I was happy.","They asked if I am happy.","They asked were I happy.","They asked if you are happy.",0,"Yes/No question shift."],
  ["He said, \"I'll be there tomorrow.\"","He said he'd be there the next day.","He said he'll be there tomorrow.","He said he would be there tomorrow.","He said he is there tomorrow.",0,"Future shift + time shift."],
  ["She said, \"I must go.\"","She said she had to go.","She said she must go.","She said she has to go.","She said she going.",0,"Must → had to (usually)."],
  ["He said, \"I am learning English.\"","He said he was learning English.","He said he is learning English.","He said he has been learning English.","He said he learned English.",0,"Present continuous → Past continuous."],
  ["She said, \"I can swim.\"","She said she could swim.","She said she can swim.","She said she will swim.","She said she swam.",0,"Can → could."],
  ["They said, \"We have been here.\"","They said they had been there.","They said they have been here.","They said they were there.","They said they have were here.",0,"Have been → had been + here → there."],
  ["He asked, \"What are you doing?\"","He asked what I was doing.","He asked what was I doing.","He asked what I am doing.","He asked what did I do.",0,"Wh-question shift."],
  ["She said, \"I will call you.\"","She said she would call me.","She said she will call you.","She said she calls me.","She said she would called me.",0,"Will → would."],
  ["He said, \"I arrived late.\"","He said he had arrived late.","He said he arrived late.","He said he arrives late.","He said he has arrived late.",0,"Past simple → Past perfect."],
  ["They said, \"We may come.\"","They said they might come.","They said they may come.","They said they will come.","They said they came.",0,"May → might."],
  ["She asked, \"Do you like it?\"","She asked if I liked it.","She asked did I like it.","She asked if I like it.","She asked whether I like it.",0,"Yes/No question with if."],
  ["He said, \"Go home!\"","He told me to go home.","He said me to go home.","He told me go home.","He said to go home.",0,"Imperative reported."],
  ["She said, \"I've seen it twice.\"","She said she had seen it twice.","She said she saw it twice.","She said she has seen it twice.","She said she sees it twice.",0,"Present perfect → Past perfect."],
  ["They said, \"We are happy here.\"","They said they were happy there.","They said they are happy here.","They said they were happy here.","They said they are happy there.",0,"Tense and place shift."],
  ["He asked, \"Who is he?\"","He asked who he was.","He asked who was he.","He asked who is he.","He asked whom he was.",0,"Word order shift."],
  ["She said, \"I'll see you now.\"","She said she'd see me then.","She said she'll see me now.","She said she would see me now.","She said she sees me then.",0,"Time shift: now → then."],
  ["He said, \"I can't find it.\"","He said he couldn't find it.","He said he can't find it.","He said he wouldn't find it.","He said he hasn't find it.",0,"Can't → couldn't."],
  ["They asked, \"Can we leave?\"","They asked if they could leave.","They asked can they leave.","They asked whether they can leave.","They asked if they can leave.",0,"Permission shift."],
  ["She said, \"I was working.\"","She said she had been working.","She said she was working.","She said she has been working.","She said she worked.",0,"Past continuous → Past perfect continuous."],
  ["He said, \"I'll do it later.\"","He said he'd do it later.","He said he'll do it later.","He said he does it later.","He said he would did it later.",0,"Future shift."],
  ["She asked, \"Where is the station?\"","She asked where the station was.","She asked where was the station.","She asked where is the station.","She asked the station where.",0,"Noun-verb order in reported question."],
  ["They said, \"We must win.\"","They said they had to win.","They said they must win.","They said they win.","They said they should win.",0,"Must → had to."],
  ["He said, \"I've lost my keys.\"","He said he'd lost his keys.","He said he's lost my keys.","He said he lost his keys.","He said he has lost his keys.",0,"Possessive pronoun shift."],
];
const directIndirectSpeech = disData.map(d => S(d[0], d.slice(1,5), d[5], d[6]));

// ── pronounResolution ──
const prData = [
  ["Mary gave John his book. Who does 'his' refer to?","John","Mary","The book","Someone else",0,"Contextual reference."],
  ["The dog wagged its tail. What is 'its'?","The dog's","The tail's","John's","A person's",0,"Possessive pronoun for animals."],
  ["They love their parents. Who are 'they'?","The children","The parents","Someone else","No one",0,"Plural subject reference."],
  ["I saw Sarah and gave her the news. Who is 'her'?","Sarah","I","The news","Another girl",0,"Object pronoun reference."],
  ["The cake was delicious; it was sweet. What is 'it'?","The cake","The taste","The news","The table",0,"Subject pronoun for things."],
  ["Every student must bring his or her pen. Why 'his or her'?","To be gender-neutral","Because student is plural","It's an error","None of the above",0,"Singular gender-neutral reference."],
  ["Neither of the boys did his work. Why 'his'?","'Neither' is singular","'Boys' is plural","It's an error","None",0,"'Neither' takes singular pronoun."],
  ["The jury gave its verdict. Why 'its'?","Jury is a collective noun","Jury is plural","It's an error","None",0,"Collective nouns as a unit are singular."],
  ["Whose is this? It's mine. What is 'mine'?","Possessive pronoun","Personal pronoun","Adjective","Noun",0,"Self-possession."],
  ["Identify the pronoun: 'That is my house.'","That","my","house","is",0,"Demonstrative pronoun."],
  ["John and Peter are here; they are ready. Who are 'they'?","John and Peter","Only John","Only Peter","The books",0,"Plural antecedent."],
  ["Someone left their umbrella. Why 'their'?","Singular they (gender neutral)","Plural subject","It's an error","Someone is plural",0,"Singular they in common usage."],
  ["This is the house that Jack built. What is 'that'?","Relative pronoun","Demonstrative pronoun","Conjunction","Article",0,"Connects clause to noun."],
  ["He himself did the work. What is 'himself'?","Reflexive pronoun","Intensive pronoun","Subject pronoun","Object pronoun",1,"Emphasizes the subject."],
  ["She hurt herself. What is 'herself'?","Reflexive pronoun","Intensive pronoun","Subject pronoun","Object pronoun",0,"Subject and object are same."],
  ["Both of the girls found their way. Why 'their'?","'Both' is plural","'Girls' is singular","It's an error","None",0,"'Both' always plural."],
  ["Either of the books is fine; it's up to you. What is 'it'?","The choice","The book","The house","The girl",0,"Abstract situational it."],
  ["These are better than those. What are 'those'?","Demonstrative pronouns","Relative pronouns","Articles","Nouns",0,"Pointing to further things."],
  ["Who is there? What is 'who'?","Interrogative pronoun","Relative pronoun","Personal pronoun","Indefinite pronoun",0,"Used to ask a question."],
  ["Anyone can do it. What is 'anyone'?","Indefinite pronoun","Personal pronoun","Relative pronoun","Demonstrative pronoun",0,"Refers to unspecified person."],
  ["Each of us has a task. What is 'each'?","Distributive pronoun","Relative pronoun","Personal pronoun","Noun",0,"Refers to members individually."],
  ["The children enjoyed themselves. What is 'themselves'?","Reflexive pronoun","Personal pronoun","Intensive pronoun","Noun",0,"Subject plural reflexive."],
  ["Which do you prefer? What is 'which'?","Interrogative pronoun","Relative pronoun","Demonstrative pronoun","Article",0,"Choosing from options."],
  ["One should respect one's elders. What is 'one'?","Generic pronoun","Personal pronoun","Number","Adjective",0,"Refers to people in general."],
  ["I like your car; mine is old. What is 'mine'?","Possessive pronoun","Personal pronoun","Adjective","Noun",0,"Replaces 'my car'."],
  ["Everything is ready. What is 'everything'?","Indefinite pronoun","Personal pronoun","Noun","Adjective",0,"Unspecified things."],
  ["You should help each other. What is 'each other'?","Reciprocal pronoun","Reflexive pronoun","Indefinite pronoun","Noun",0,"Mutual action."],
  ["That's the man whose son won. What is 'whose'?","Relative pronoun","Interrogative pronoun","Adjective","Article",0,"Shows possession in clause."],
  ["Whom did you see? What is 'whom'?","Interrogative pronoun (object)","Relative pronoun","Subject pronoun","Noun",0,"Object of the question."],
  ["Many were called, but few were chosen. What is 'few'?","Indefinite pronoun","Adjective","Noun","Verb",0,"Unspecified small number."],
];
const pronounResolution = prData.map(d => S(d[0], d.slice(1,5), d[5], d[6]));

// ── punctuationMastery ──
const pmData = [
  ["Which is correctly punctuated?","I like apples, oranges, and bananas.","I like apples oranges and bananas.","I like apples, oranges and, bananas.","I like apples, oranges, and, bananas.",0,"Serial comma (Oxford comma)."],
  ["Choose the correct sentence.","He said, \"Hello!\"","He said \"Hello!\"","He said, Hello!","He said: Hello!",0,"Direct speech punctuation."],
  ["Which uses the apostrophe correctly?","The dog's bone.","The dogs' bone.","Both can be correct.","The dogs bone.",2,"Singular vs plural possessive."],
  ["Choose the correct sentence.","It's a beautiful day.","Its a beautiful day.","It is'a beautiful day.","Its' a beautiful day.",0,"Contraction of 'it is'."],
  ["Which is correct?","However, we must wait.","However we must wait.","However; we must wait.","However: we must wait.",0,"Introductory adverb comma."],
  ["Identify the correct one.","She lives in Paris, France.","She lives in Paris France.","She lives in Paris; France.","She lives in Paris: France.",0,"City-state/country punctuation."],
  ["Choose the correctly punctuated list.","We need: milk, bread, and eggs.","We need milk, bread, and eggs.","We need: milk bread and eggs.","We need, milk, bread, and eggs.",1,"Don't use colon after a verb unless list is long/complex."],
  ["Which is correct?","I am tired; therefore, I will sleep.","I am tired, therefore I will sleep.","I am tired therefore I will sleep.","I am tired: therefore I will sleep.",0,"Semicolon with conjunctive adverb."],
  ["Choose the correct one.","\"Where are you?\" she asked.","\"Where are you\"? she asked.","\"Where are you,\" she asked.","Where are you? she asked.",0,"Question mark inside quotes."],
  ["Which is correct?","The 1990s were great.","The 1990's were great.","The 1990s' were great.","The 90's were great.",0,"Decades usually don't need apostrophe for plural."],
  ["Which is correct?","It's a long way.","Its a long way.","It is a long way.","Both A and C are correct.",3,"Contraction vs possessive."],
  ["Choose the correct sentence.","She asked me, \"Why?\"","She asked me \"Why?\"","She asked me, Why?","She asked me: Why?",0,"Comma before quotes."],
  ["Which is correct?","Mr. Smith is here.","Mr Smith is here.","Both are correct.","Mister Smith is here.",2,"Period after abbreviation (US vs UK)."],
  ["Identify the correct one.","I'm going; are you?","I'm going, are you?","I'm going. Are you?","Both A and C.",3,"Semicolon vs Period."],
  ["Which uses hyphen correctly?","A well-known artist.","A well known artist.","A well-known-artist.","A well known-artist.",0,"Compound adjective."],
  ["Choose the correct sentence.","The boy's toys.","The boys' toys.","Both can be correct.","The boys toys.",2,"Singular vs plural possessive."],
  ["Which is correct?","It was 10:30 AM.","It was 10.30 AM.","It was 10;30 AM.","It was 10 30 AM.",0,"Time colon."],
  ["Which is correct?","\"Wait!\" he yelled.","\"Wait\", he yelled.","\"Wait!\", he yelled.","Wait! he yelled.",0,"Exclamation in quotes."],
  ["Identify the correct one.","I have three things: a pen, a map, and a hat.","I have three things a pen, a map, and a hat.","I have three things; a pen, a map, and a hat.","I have three things: a pen a map and a hat.",0,"List after colon."],
  ["Which is correct?","The children's play.","The childrens' play.","The childrens play.","The children play's.",0,"Plural irregular possessive."],
  ["Choose the correct one.","I visited London, UK.","I visited London UK.","I visited London; UK.","I visited London: UK.",0,"City, Country."],
  ["Which is correct?","Wait—what?","Wait, what?","Both are correct depending on tone.","Wait what?",2,"Dash vs comma for pause."],
  ["Which is correct?","He's a five-year-old boy.","He's a five year old boy.","He's a five-year old boy.","He's a five year-old boy.",0,"Compound age adjective."],
  ["Identify the correct one.","\"He said, 'No,'\" she replied.","\"He said, \"No,\"\" she replied.","He said, 'No,' she replied.","\"He said 'No'\" she replied.",0,"Nested quotes."],
  ["Which is correct?","The sun is hot; the moon is cold.","The sun is hot, the moon is cold.","The sun is hot. The moon is cold.","Both A and C.",3,"Semicolon between related sentences."],
  ["Which is correct?","Can you help?","Can you help.","Can you help!","Can you help:",0,"Question mark."],
  ["Identify the correct one.","Go! now!","Go! Now!","Go, now!","Both B and C.",3,"Exclamation capitalization."],
  ["Which is correct?","Its tail is long.","It's tail is long.","Its' tail is long.","Its tail's is long.",0,"Possessive 'its'."],
  ["Which is correct?","I like apples (the red ones).","I like apples (the red ones.)","I like apples (the red ones) .","I like apples (the red ones),",0,"Parentheses punctuation."],
  ["Which is correct?","etc.","etc","etc...","et cetera.",0,"Abbreviation period."],
];
const punctuationMastery = pmData.map(d => S(d[0], d.slice(1,5), d[5], d[6]));

// ── modalsSelection ──
const msData = [
  ["You ___ wear a helmet while riding.","must","can","might","will",0,"Obligation/Rule."],
  ["___ I borrow your pen?","Can","Must","Should","Will",0,"Permission."],
  ["It ___ rain later today.","might","must","should","can",0,"Possibility."],
  ["I ___ swim when I was five.","could","can","might","should",0,"Past ability."],
  ["You ___ see a doctor about that cough.","should","must","can","might",0,"Advice."],
  ["He ___ be at home; his car is there.","must","might","can","should",0,"Strong logical deduction."],
  ["___ you like some coffee?","Would","Will","Can","Should",0,"Polite offer."],
  ["I ___ finish this by tomorrow.","have to","might","can","could",0,"Necessity/Requirement."],
  ["You ___ not smoke here.","must","should","might","can",0,"Prohibition."],
  ["I ___ love to visit Japan.","would","will","can","might",0,"Desire."],
  ["We ___ to leave early because of the traffic.","had to","must","could","might",0,"Past necessity."],
  ["___ you please pass the salt?","Could","Should","Must","Might",0,"Polite request."],
  ["She ___ speak three languages fluently.","can","must","should","may",0,"Present ability."],
  ["You ___ not enter this area.","may","can","might","should",0,"Formal prohibition."],
  ["It ___ be true, but I doubt it.","might","must","should","will",0,"Weak possibility."],
  ["I ___ go if I had enough money.","would","will","can","shall",0,"Conditional desire."],
  ["___ I open the window?","Shall","Must","Will","Could",0,"Offer/Suggestion."],
  ["You ___ have told me earlier!","should","must","can","will",0,"Past regret/criticism."],
  ["He ___ have lost his way.","might","can","will","should",0,"Possibility about past."],
  ["We ___ as well go now.","might","must","should","can",0,"Idiomatic suggestion."],
  ["I ___ like to ask a question.","would","will","can","may",0,"Polite intention."],
  ["You ___ be joking!","must","can","should","will",0,"Strong deduction."],
  ["I ___ speak English better next year.","will be able to","can","could","may",0,"Future ability."],
  ["They ___ have arrived by now.","should","must","can","might",0,"Expectation."],
  ["___ you mind if I sit here?","Would","Should","Must","Can",0,"Polite inquiry."],
  ["I ___ rather stay at home.","would","will","should","can",0,"Preference."],
  ["You ___ better hurry up.","had","must","should","would",0,"Urgent advice."],
  ["She ___ not have seen him.","could","must","should","might",0,"Negative past deduction."],
  ["I ___ help you if you want.","can","must","should","may",0,"Offer of ability."],
  ["___ it be true?","Can","Must","Should","Will",0,"Skeptical inquiry."],
];
const modalsSelection = msData.map(d => S(d[0], d.slice(1,5), d[5], d[6]));

// ── prepositionChoice ──
const pcData = [
  ["I am interested ___ learning English.","in","on","at","for",0,"Preposition after 'interested'."],
  ["The keys are ___ the table.","on","in","at","to",0,"Surface location."],
  ["She is good ___ math.","at","in","on","for",0,"Ability preposition."],
  ["We arrived ___ the airport early.","at","in","to","on",0,"Specific location."],
  ["He is afraid ___ spiders.","of","from","for","with",0,"Emotion preposition."],
  ["I'll see you ___ Monday.","on","in","at","to",0,"Days of the week."],
  ["She lives ___ London.","in","at","on","to",0,"Cities/Countries."],
  ["Wait ___ me at the station.","for","to","at","on",0,"Verb-preposition pair."],
  ["The book was written ___ Dickens.","by","from","of","with",0,"Agency/Author."],
  ["Divide the cake ___ the three children.","among","between","with","to",0,"'Among' for more than two."],
  ["He jumped ___ the pool.","into","in","on","to",0,"Movement into."],
  ["The plane flew ___ the clouds.","above","on","at","to",0,"Relative position."],
  ["I am fond ___ chocolate.","of","for","at","in",0,"Adjective-preposition."],
  ["She is married ___ a doctor.","to","with","of","for",0,"Preposition with 'married'."],
  ["We went ___ the tunnel.","through","by","on","at",0,"Movement across."],
  ["The meeting is ___ 10 AM.","at","on","in","to",0,"Time point."],
  ["I met him ___ the weekend.","at","in","on","Both A and C are correct.",3,"British vs American."],
  ["He is proud ___ his son.","of","for","at","with",0,"Adjective-preposition."],
  ["Translate this ___ English.","into","to","at","for",0,"Change of state."],
  ["She is standing ___ the door.","at","by","on","Both A and B are correct.",3,"Proximity."],
  ["I'm looking ___ my keys.","for","at","to","of",0,"Phrasal verb."],
  ["He is different ___ his brother.","from","than","of","Both A and B.",3,"Preposition after 'different'."],
  ["We are ___ the train now.","on","in","at","by",0,"Public transport."],
  ["She came ___ car.","by","in","on","with",0,"Mode of transport."],
  ["It's a secret ___ you and me.","between","among","with","at",0,"Two parties."],
  ["I'll be back ___ ten minutes.","in","at","on","for",0,"Duration until end."],
  ["The cat is hiding ___ the bed.","under","below","beneath","All are correct.",3,"Location below."],
  ["I'm worried ___ the exam.","about","for","of","with",0,"Emotion preposition."],
  ["They are sitting ___ the table.","at","on","in","by",0,"Proximity for activity."],
  ["He walked ___ the street.","across","along","through","All can be correct.",3,"Movement relation."],
];
const prepositionChoice = pcData.map(d => S(d[0], d.slice(1,5), d[5], d[6]));

// ── relativeClauses ──
const rcData = [
  ["The man ___ lives next door is nice.","who","which","whose","whom",0,"Relative pronoun for people."],
  ["The book ___ I read was great.","which","who","whose","whom",0,"Relative pronoun for things."],
  ["This is the house ___ Jack built.","that","who","whose","whom",0,"'That' for things/defining."],
  ["The girl ___ father is a doctor.","whose","who","which","whom",0,"Possessive relative pronoun."],
  ["The city ___ I was born is beautiful.","where","which","who","that",0,"Relative adverb for place."],
  ["The year ___ we met was 2020.","when","where","which","who",0,"Relative adverb for time."],
  ["The students ___ passed the test were happy.","who","which","whose","whom",0,"Plural people."],
  ["I know a person ___ can help.","who","which","whose","whom",0,"Ability reference."],
  ["The car, ___ was red, was fast.","which","who","that","whose",0,"Non-defining clause."],
  ["Is this the person ___ you met?","whom","who","which","whose",0,"Object relative pronoun (formal)."],
  ["The reason ___ I called is a secret.","why","when","where","who",0,"Relative adverb for reason."],
  ["That's the lady ___ car was stolen.","whose","who","which","whom",0,"Possession."],
  ["The shop ___ I buy my bread is closed.","where","which","that","who",0,"Place."],
  ["The cake ___ she made was delicious.","that","who","whose","whom",0,"Thing."],
  ["He is the only one ___ knows the truth.","that","which","who","Both A and C are correct.",3,"Specific emphasis."],
  ["The movie, ___ lasted three hours, was boring.","which","that","who","whose",0,"Non-defining (which only)."],
  ["I met a man ___ name I forgot.","whose","who","which","that",0,"Possessive."],
  ["The time ___ we arrived was late.","when","where","why","who",0,"Time."],
  ["The tools ___ he used were old.","which","who","whose","whom",0,"Things."],
  ["This is all ___ I know.","that","which","what","who",0,"'That' after 'all'."],
  ["The woman ___ he married is lovely.","whom","who","which","whose",0,"Object of the verb."],
  ["London, ___ is the capital, is big.","which","that","who","where",0,"Non-defining place."],
  ["The box ___ contained the jewels was heavy.","that","who","whose","whom",0,"Thing."],
  ["A person ___ works hard will succeed.","who","which","that","Both A and C.",3,"Subject for people."],
  ["The day ___ it happened was a Tuesday.","when","where","which","who",0,"Time."],
  ["The friends ___ I went with were nice.","whom","who","which","whose",0,"Object after preposition."],
  ["I saw a movie ___ title I can't recall.","whose","which","that","who",0,"Possessive for things."],
  ["The park ___ we played was beautiful.","where","which","that","in which",0,"Place."],
  ["He is the person ___ we talked about.","that","who","whom","All are correct.",3,"Relative pronoun flexibility."],
  ["The house ___ windows are broken is empty.","whose","which","that","where",0,"Possessive."],
];
const relativeClauses = rcData.map(d => S(d[0], d.slice(1,5), d[5], d[6]));

// ── conjunctions ──
const cjData = [
  ["I like tea ___ coffee.","and","but","or","so",0,"Addition."],
  ["I wanted to go ___ it rained.","but","and","or","so",0,"Contrast."],
  ["Would you like tea ___ coffee?","or","and","but","so",0,"Alternative."],
  ["He was tired, ___ he went to bed.","so","but","and","or",0,"Result."],
  ["___ he is poor, he is happy.","Although","Because","Since","So",0,"Concession."],
  ["I'll wait ___ you arrive.","until","unless","if","so",0,"Time."],
  ["I study ___ I want to learn.","because","although","but","or",0,"Reason."],
  ["Neither Tom ___ Jerry came.","nor","or","and","but",0,"Correlative pair."],
  ["Not only is he smart, ___ also kind.","but","and","or","yet",0,"Correlative pair."],
  ["Either stay ___ leave.","or","nor","and","but",0,"Alternative pair."],
  ["___ it was raining, they played outside.","Even though","Because","Unless","Whether",0,"Concession."],
  ["I'll go ___ you go with me.","if","but","so","although",0,"Condition."],
  ["He is rich, ___ he is not happy.","yet","and","so","or",0,"Contrast."],
  ["She was late ___ the traffic was bad.","since","although","but","so",0,"Cause."],
  ["I'll call you ___ I get home.","as soon as","until","unless","whether",0,"Time."],
  ["He can sing ___ he can dance.","as well as","but","so","or",0,"Addition."],
  ["___ you like it or not, we're going.","Whether","If","Unless","Although",0,"Alternative condition."],
  ["He works hard ___ he can earn money.","so that","because","although","but",0,"Purpose."],
  ["I haven't seen him ___ last year.","since","because","until","unless",0,"Time."],
  ["She is both smart ___ beautiful.","and","but","or","yet",0,"Addition."],
  ["He is not only a doctor ___ also a musician.","but","and","or","so",0,"Correlative."],
  ["I will wait ___ 10 o'clock.","until","since","unless","whether",0,"Time limit."],
  ["___ it snows, we will stay in.","If","Although","Unless","But",0,"Condition."],
  ["He ran fast, ___ he missed the bus.","but","so","and","or",0,"Contrast."],
  ["She is tired ___ she worked all night.","because","although","so","yet",0,"Reason."],
  ["I'll go ___ it rains.","even if","as soon as","until","so",0,"Hypothetical condition."],
  ["Neither you ___ I am wrong.","nor","or","and","but",0,"Correlative."],
  ["___ he arrived, the meeting started.","Once","Unless","Whether","Although",0,"Time."],
  ["I study hard ___ I fail.","lest","so","because","and",0,"Negative purpose."],
  ["Either you're with us ___ against us.","or","nor","and","but",0,"Alternative."],
];
const conjunctions = cjData.map(d => S(d[0], d.slice(1,5), d[5], d[6]));

module.exports = {
  grammarQuest, sentenceCorrection, wordReorder, tenseMastery,
  partsOfSpeech, subjectVerbAgreement, clauseConnector, voiceSwap,
  questionFormatter, articleInsertion,
  modifierPlacement, conditionals, directIndirectSpeech, pronounResolution,
  punctuationMastery, modalsSelection, prepositionChoice, relativeClauses,
  conjunctions,
};
