// Listening question pools
// Each game targets 600 unique questions (200 levels × 3)

const S = (t, q, o, c, h, inst) => ({
  instruction: inst || 'Listen and choose.',
  fields: { transcript: t, question: q || t, options: o, correctAnswerIndex: c, hint: h, textToSpeak: t }
});

const P = (t, q, o, c, h, inst) => ({
  instruction: inst || 'Listen to the passage and answer.',
  fields: { transcript: t, question: q, options: o, correctAnswerIndex: c, hint: h, textToSpeak: t }
});

const FB = (t, q, o, c, h, mw, inst) => ({
  instruction: inst || 'Fill the blank based on what you hear.',
  fields: { transcript: t, textWithBlanks: t, question: q, options: o, correctAnswerIndex: c, hint: h, missingWord: mw, textToSpeak: t }
});

const SO = (t, sw, co, h, inst) => ({
  instruction: inst || 'Arrange the words in the correct order.',
  fields: { transcript: t, question: t, shuffledSentences: sw, correctOrder: co, hint: h, textToSpeak: t }
});

// ── audioFillBlanks ──
const afbData = [
  ["The weather is ___ today.", "Choose the missing word.", ["sunny", "rainy", "snowy", "windy"], 0, "Warm sun.", "sunny"],
  ["She went to the ___ to buy bread.", "Choose the missing word.", ["bakery", "gym", "bank", "pool"], 0, "Bread shop.", "bakery"],
  ["I need to ___ my car.", "Choose the missing word.", ["wash", "eat", "read", "sing"], 0, "Cleaning action.", "wash"],
  ["The cat is sleeping on the ___.", "Choose the missing word.", ["sofa", "roof", "tree", "car"], 0, "Living room furniture.", "sofa"],
  ["Please turn off the ___.", "Choose the missing word.", ["lights", "water", "shoes", "grass"], 0, "Save electricity.", "lights"],
  ["He is eating a green ___.", "Choose the missing word.", ["apple", "stone", "book", "cloud"], 0, "Healthy fruit.", "apple"],
  ["We are going to the ___.", "Choose the missing word.", ["cinema", "forest", "moon", "ceiling"], 0, "Movie place.", "cinema"],
  ["I lost my ___.", "Choose the missing word.", ["keys", "road", "sky", "smile"], 0, "Door openers.", "keys"],
  ["The dog is ___.", "Choose the missing word.", ["barking", "flying", "coding", "singing"], 0, "Dog sound.", "barking"],
  ["It is time for ___.", "Choose the missing word.", ["dinner", "winter", "yesterday", "blue"], 0, "Evening meal.", "dinner"],
  ["She is reading a ___.", "Choose the missing word.", ["book", "plate", "shoe", "wall"], 0, "Story material.", "book"],
  ["The baby is ___.", "Choose the missing word.", ["crying", "driving", "working", "typing"], 0, "Infant sound.", "crying"],
  ["We have a big ___.", "Choose the missing word.", ["house", "idea", "shoe", "pen"], 0, "Living space.", "house"],
  ["He plays the ___.", "Choose the missing word.", ["guitar", "table", "chair", "road"], 0, "Musical instrument.", "guitar"],
  ["It is very ___ outside.", "Choose the missing word.", ["cold", "long", "heavy", "sweet"], 0, "Temperature.", "cold"],
  ["I like to ___.", "Choose the missing word.", ["swim", "break", "lose", "fall"], 0, "Water activity.", "swim"],
  ["The sky is ___.", "Choose the missing word.", ["blue", "green", "red", "yellow"], 0, "Daytime color.", "blue"],
  ["She has long ___.", "Choose the missing word.", ["hair", "nose", "hand", "eye"], 0, "Head feature.", "hair"],
  ["The bird can ___.", "Choose the missing word.", ["fly", "talk", "swim", "drive"], 0, "Air movement.", "fly"],
  ["They are ___ a game.", "Choose the missing word.", ["playing", "eating", "sleeping", "reading"], 0, "Fun activity.", "playing"],
  ["He wears a ___.", "Choose the missing word.", ["hat", "bag", "pen", "desk"], 0, "Head wear.", "hat"],
  ["The water is ___.", "Choose the missing word.", ["hot", "dry", "solid", "loud"], 0, "Boiling.", "hot"],
  ["I drink ___.", "Choose the missing word.", ["milk", "sand", "wood", "paper"], 0, "White drink.", "milk"],
  ["The car is ___.", "Choose the missing word.", ["fast", "slow", "blue", "loud"], 0, "Speed.", "fast"],
  ["She is my ___.", "Choose the missing word.", ["mother", "car", "book", "pen"], 0, "Family member.", "mother"],
  ["We live in a ___.", "Choose the missing word.", ["city", "ocean", "cloud", "star"], 0, "Urban area.", "city"],
  ["He has a new ___.", "Choose the missing word.", ["phone", "road", "sky", "dream"], 0, "Mobile device.", "phone"],
  ["The flowers are ___.", "Choose the missing word.", ["pretty", "loud", "angry", "fast"], 0, "Beauty.", "pretty"],
  ["I am ___.", "Choose the missing word.", ["happy", "blue", "round", "heavy"], 0, "Emotion.", "happy"],
  ["The sun is ___.", "Choose the missing word.", ["bright", "cold", "dark", "wet"], 0, "Light intensity.", "bright"],
  ["She eats ___.", "Choose the missing word.", ["bread", "water", "air", "light"], 0, "Basic food.", "bread"],
  ["The door is ___.", "Choose the missing word.", ["open", "loud", "sweet", "fast"], 0, "State of entry.", "open"],
  ["I have a ___.", "Choose the missing word.", ["sister", "car", "house", "dream"], 0, "Sibling.", "sister"],
  ["The moon is ___.", "Choose the missing word.", ["round", "square", "green", "hot"], 0, "Shape.", "round"],
  ["He runs ___.", "Choose the missing word.", ["quickly", "slowly", "loudly", "sadly"], 0, "High speed.", "quickly"],
  ["The grass is ___.", "Choose the missing word.", ["green", "blue", "red", "purple"], 0, "Natural color.", "green"],
  ["She sings ___.", "Choose the missing word.", ["well", "fast", "heavy", "cold"], 0, "Musical quality.", "well"],
  ["We buy ___.", "Choose the missing word.", ["food", "air", "sleep", "dreams"], 0, "Grocery item.", "food"],
  ["The clock is ___.", "Choose the missing word.", ["ticking", "singing", "eating", "flying"], 0, "Clock sound.", "ticking"],
  ["I write with a ___.", "Choose the missing word.", ["pen", "shoe", "cup", "hat"], 0, "Writing tool.", "pen"],
  ["The coffee is ___.", "Choose the missing word.", ["bitter", "sweet", "hot", "cold"], 0, "Taste.", "bitter"],
  ["She drives a ___.", "Choose the missing word.", ["car", "bus", "train", "plane"], 0, "Vehicle.", "car"],
  ["The mountain is ___.", "Choose the missing word.", ["high", "low", "soft", "fast"], 0, "Altitude.", "high"],
  ["He wears ___.", "Choose the missing word.", ["shoes", "bags", "books", "pens"], 0, "Footwear.", "shoes"],
  ["The ocean is ___.", "Choose the missing word.", ["deep", "dry", "small", "hot"], 0, "Water depth.", "deep"],
  ["I love my ___.", "Choose the missing word.", ["family", "car", "job", "home"], 0, "People I love.", "family"],
  ["The fire is ___.", "Choose the missing word.", ["warm", "cold", "wet", "blue"], 0, "Heat.", "warm"],
  ["She has a ___.", "Choose the missing word.", ["smile", "tear", "frown", "laugh"], 0, "Happy face.", "smile"],
  ["The table is ___.", "Choose the missing word.", ["wood", "water", "air", "fire"], 0, "Material.", "wood"],
  ["I feel ___.", "Choose the missing word.", ["tired", "blue", "long", "wide"], 0, "Physical state.", "tired"],
];

// ── audioMultipleChoice ──
const amcData = [
  ["Where is the speaker going?", ["To the park", "To work", "To sleep", "To eat"], 0, "Mentioned 'jogging area'."],
  ["What did he buy?", ["A new laptop", "A book", "A car", "A phone"], 0, "Electronics store visit."],
  ["Who is calling?", ["His mother", "His boss", "The doctor", "A friend"], 0, "Mentioned 'family member'."],
  ["What time is the meeting?", ["9:00 AM", "10:30 AM", "2:00 PM", "5:00 PM"], 0, "Early morning."],
  ["How does she feel?", ["Excited", "Sad", "Tired", "Angry"], 0, "Winning a prize."],
  ["What color is the bag?", ["Blue", "Red", "Green", "Black"], 0, "Sky color."],
  ["Where are the keys?", ["On the table", "In the car", "Under the bed", "By the door"], 0, "Kitchen surface."],
  ["What is the weather like?", ["Rainy", "Sunny", "Cloudy", "Stormy"], 0, "Need an umbrella."],
  ["Which fruit does he want?", ["Banana", "Orange", "Grape", "Melon"], 0, "Yellow fruit."],
  ["Why is he late?", ["Traffic", "Alarm failed", "Lost keys", "Sick"], 0, "Car queue."],
  ["What is for dinner?", ["Pizza", "Sushi", "Pasta", "Steak"], 0, "Italian pie."],
  ["Where did she go?", ["London", "Paris", "New York", "Tokyo"], 0, "Eiffel Tower city."],
  ["What is he reading?", ["A novel", "A comic", "A newspaper", "A magazine"], 0, "Fiction book."],
  ["What sport does she play?", ["Tennis", "Soccer", "Golf", "Rugby"], 0, "Racket sport."],
  ["Which animal is it?", ["Elephant", "Lion", "Giraffe", "Zebra"], 0, "Trunk animal."],
  ["What is the goal?", ["Success", "Money", "Fame", "Happiness"], 0, "Positive outcome."],
  ["Who won?", ["Team A", "Team B", "Neither", "Both"], 0, "First group."],
  ["What is the problem?", ["No power", "No water", "No internet", "No food"], 0, "Connection issue."],
  ["When is the party?", ["Saturday", "Friday", "Sunday", "Monday"], 0, "Weekend start."],
  ["How much is it?", ["$10", "$20", "$50", "$100"], 0, "Ten dollars."],
  ["Where is the cat?", ["Garden", "Bedroom", "Kitchen", "Attic"], 0, "Outdoor area."],
  ["What did she see?", ["A rainbow", "A star", "A plane", "A bird"], 0, "Colorful arc."],
  ["Who is he?", ["Brother", "Uncle", "Father", "Friend"], 0, "Sibling."],
  ["What is the mood?", ["Calm", "Tense", "Happy", "Sad"], 0, "Quiet atmosphere."],
  ["Which room is it?", ["Kitchen", "Hall", "Dining", "Laundry"], 0, "Cooking area."],
  ["What is the color?", ["Purple", "Pink", "Orange", "Gray"], 0, "Grape color."],
  ["Why cry?", ["Pain", "Joy", "Boredom", "Hunger"], 0, "Physical hurt."],
  ["What is the news?", ["New job", "New car", "New house", "New dog"], 0, "Career change."],
  ["Where is the station?", ["North", "South", "East", "West"], 0, "Direction."],
  ["Who is the leader?", ["Mark", "John", "Sarah", "Jane"], 0, "First name."],
  ["What is the theme?", ["Space", "Sea", "Desert", "Jungle"], 0, "Outer world."],
  ["Why study?", ["To learn", "To play", "To sleep", "To eat"], 0, "Education."],
  ["What is the object?", ["Ring", "Watch", "Pen", "Bag"], 0, "Finger jewelry."],
  ["Which month?", ["April", "May", "June", "July"], 0, "Spring month."],
  ["What is the size?", ["Large", "Medium", "Small", "Tiny"], 0, "Big."],
  ["Where to park?", ["Slot A", "Slot B", "Slot C", "Slot D"], 0, "First option."],
  ["Who is the singer?", ["Adele", "Beyonce", "Taylor", "Rihanna"], 0, "British star."],
  ["What is the task?", ["Cleanup", "Writing", "Reading", "Speaking"], 0, "Cleaning."],
  ["How to travel?", ["Bus", "Train", "Plane", "Taxi"], 0, "Public road."],
  ["What is the sound?", ["Thunder", "Rain", "Wind", "Birds"], 0, "Storm sound."],
  ["Which year?", ["2021", "2022", "2023", "2024"], 0, "Current year."],
  ["Who is the guest?", ["Uncle", "Friend", "Boss", "Neighbor"], 0, "Relative."],
  ["What is the price?", ["Free", "$5", "$10", "$20"], 0, "Zero cost."],
  ["Where is the park?", ["City center", "Suburb", "Beach", "Mountain"], 0, "Urban heart."],
  ["Which team?", ["Blue", "Red", "Green", "Gold"], 0, "Sky color."],
  ["Who is calling?", ["Mom", "Dad", "Brother", "Sister"], 0, "Mother."],
  ["What is the hobby?", ["Chess", "Cards", "Video games", "Sports"], 0, "Board game."],
  ["Why run?", ["Late", "Exercise", "Fun", "Fear"], 0, "Tardy."],
  ["Where is the exit?", ["Left", "Right", "Straight", "Back"], 0, "First side."],
  ["Who is the teacher?", ["Mr. Smith", "Ms. Doe", "Mr. Brown", "Ms. White"], 0, "Male name."],
];

// ── audioSentenceOrder ──
const asoData = [
  ["I like to eat apples.", ["eat", "apples", "I", "like", "to"], [2, 3, 4, 0, 1], "Simple preference."],
  ["The cat is on the mat.", ["mat", "on", "The", "cat", "is", "the"], [2, 3, 4, 1, 5, 0], "Classic sentence."],
  ["She plays the piano well.", ["the", "piano", "She", "plays", "well"], [2, 3, 0, 1, 4], "Musical skill."],
  ["We are going to school.", ["to", "are", "We", "going", "school"], [2, 1, 3, 0, 4], "Daily routine."],
  ["He works in a big office.", ["in", "office", "big", "He", "works", "a"], [3, 4, 0, 5, 2, 1], "Job location."],
  ["It is a beautiful day.", ["day", "is", "It", "a", "beautiful"], [2, 1, 3, 4, 0], "Weather remark."],
  ["I forgot my phone home.", ["home", "forgot", "my", "I", "phone"], [3, 1, 2, 4, 0], "Common mistake."],
  ["Birds fly in the sky.", ["fly", "Birds", "sky", "in", "the"], [1, 0, 3, 4, 2], "Natural fact."],
  ["She is my best friend.", ["best", "She", "friend", "is", "my"], [1, 3, 4, 0, 2], "Relationship."],
  ["Water boils at hundred degrees.", ["at", "hundred", "boils", "degrees", "Water"], [4, 2, 0, 1, 3], "Science fact."],
  ["The sun sets in the west.", ["sets", "the", "sun", "in", "west"], [2, 0, 3, 1, 4], "Daily cycle."],
  ["I have a red car.", ["have", "a", "I", "red", "car"], [2, 0, 1, 3, 4], "Possession."],
  ["He reads a book everyday.", ["reads", "everyday", "He", "book", "a"], [2, 0, 4, 3, 1], "Habit."],
  ["She cooks dinner for us.", ["dinner", "for", "She", "cooks", "us"], [2, 3, 0, 1, 4], "Service."],
  ["We love to play soccer.", ["to", "soccer", "play", "We", "love"], [3, 4, 0, 2, 1], "Sport."],
  ["The dog barks at strangers.", ["at", "dog", "strangers", "barks", "The"], [4, 1, 3, 0, 2], "Animal behavior."],
  ["Flowers bloom in the spring.", ["in", "bloom", "Flowers", "the", "spring"], [2, 1, 0, 3, 4], "Season."],
  ["I drink tea every morning.", ["morning", "tea", "drink", "I", "every"], [3, 2, 1, 4, 0], "Morning routine."],
  ["The train leaves at ten.", ["leaves", "at", "The", "ten", "train"], [2, 4, 0, 1, 3], "Schedule."],
  ["She studies hard for exams.", ["for", "hard", "studies", "She", "exams"], [3, 2, 1, 0, 4], "Academic effort."],
  ["He swims in the pool.", ["the", "swims", "in", "pool", "He"], [4, 1, 2, 0, 3], "Exercise."],
  ["They watch movies on Friday.", ["Friday", "watch", "They", "on", "movies"], [2, 1, 4, 3, 0], "Entertainment."],
  ["The baby sleeps in crib.", ["in", "crib", "baby", "sleeps", "The"], [4, 2, 3, 0, 1], "Sleep."],
  ["I need a new laptop.", ["new", "a", "I", "laptop", "need"], [2, 4, 1, 0, 3], "Need."],
  ["She wears a blue dress.", ["dress", "a", "wears", "She", "blue"], [3, 2, 1, 4, 0], "Clothing."],
  ["He writes with his left hand.", ["hand", "writes", "with", "He", "his", "left"], [3, 1, 2, 4, 5, 0], "Physical trait."],
  ["We live in a small house.", ["house", "a", "in", "We", "live", "small"], [3, 4, 2, 1, 5, 0], "Residence."],
  ["The sky is full of stars.", ["stars", "full", "The", "sky", "is", "of"], [2, 3, 4, 1, 5, 0], "Night sky."],
  ["I want to travel more.", ["travel", "more", "I", "want", "to"], [2, 3, 4, 0, 1], "Desire."],
  ["She is a very kind person.", ["kind", "person", "a", "She", "is", "very"], [3, 4, 2, 5, 0, 1], "Character."],
  ["The pizza is very hot.", ["hot", "is", "The", "pizza", "very"], [2, 3, 1, 4, 0], "Food."],
  ["He lost his wallet yesterday.", ["yesterday", "his", "lost", "wallet", "He"], [4, 2, 1, 3, 0], "Loss."],
  ["We are happy to help.", ["happy", "are", "We", "to", "help"], [2, 1, 0, 3, 4], "Service."],
  ["The wind is blowing hard.", ["blowing", "hard", "The", "wind", "is"], [2, 3, 4, 0, 1], "Wind."],
  ["She has a beautiful smile.", ["smile", "a", "has", "She", "beautiful"], [3, 2, 1, 4, 0], "Trait."],
  ["I have two elder brothers.", ["brothers", "two", "I", "have", "elder"], [2, 3, 1, 4, 0], "Family."],
  ["He is working on project.", ["on", "project", "is", "He", "working"], [3, 2, 4, 0, 1], "Work."],
  ["The park is near here.", ["near", "is", "The", "park", "here"], [2, 3, 1, 0, 4], "Location."],
  ["She loves to read poetry.", ["poetry", "to", "She", "loves", "read"], [2, 3, 1, 4, 0], "Hobby."],
  ["We saw a huge elephant.", ["huge", "elephant", "We", "saw", "a"], [2, 3, 4, 0, 1], "Observation."],
  ["The coffee smells so good.", ["smells", "good", "The", "coffee", "so"], [2, 3, 0, 4, 1], "Scent."],
  ["I will call you later.", ["later", "call", "I", "will", "you"], [2, 3, 1, 4, 0], "Future."],
  ["She bought a new house.", ["house", "a", "bought", "She", "new"], [3, 2, 1, 4, 0], "Purchase."],
  ["The rain stopped at noon.", ["at", "stopped", "The", "rain", "noon"], [2, 3, 1, 0, 4], "Weather."],
  ["He is a great singer.", ["singer", "is", "He", "a", "great"], [2, 1, 3, 4, 0], "Talent."],
  ["We enjoyed the party much.", ["party", "enjoyed", "We", "the", "much"], [2, 1, 3, 0, 4], "Event."],
  ["The child is playing outside.", ["playing", "child", "The", "is", "outside"], [2, 1, 3, 0, 4], "Activity."],
  ["I forgot to bring keys.", ["bring", "forgot", "to", "I", "keys"], [3, 1, 2, 0, 4], "Mistake."],
  ["She wears glasses for reading.", ["reading", "glasses", "She", "wears", "for"], [2, 3, 1, 4, 0], "Vision."],
  ["He is the best player.", ["player", "the", "He", "is", "best"], [2, 3, 1, 4, 0], "Skill."],
];

// ── audioTrueFalse ──
const atfData = [
  ["The speaker is at the airport.", ["True", "False"], 0, "He mentioned checking in."],
  ["She hates Italian food.", ["True", "False"], 1, "She said she loves pasta."],
  ["It is currently midnight.", ["True", "False"], 1, "The sun is shining."],
  ["He has three brothers.", ["True", "False"], 0, "He listed Tom, Bob, and Ray."],
  ["The movie starts in five minutes.", ["True", "False"], 0, "Hurry up!"],
  ["They are traveling by train.", ["True", "False"], 1, "They are on a boat."],
  ["The store is closed on Sundays.", ["True", "False"], 0, "Check the sign."],
  ["He forgot his umbrella.", ["True", "False"], 0, "He is getting wet."],
  ["She is a professional dancer.", ["True", "False"], 0, "She won the competition."],
  ["The car needs more fuel.", ["True", "False"], 0, "Indicator is low."],
  ["The baby is crying loudly.", ["True", "False"], 0, "You can hear it."],
  ["He is a doctor.", ["True", "False"], 1, "He said he is an engineer."],
  ["The coffee is very hot.", ["True", "False"], 0, "Careful!"],
  ["They live in the city.", ["True", "False"], 0, "Urban sounds."],
  ["She is wearing a blue dress.", ["True", "False"], 0, "She mentioned the color."],
  ["The meeting was canceled.", ["True", "False"], 1, "It was moved to 2 PM."],
  ["He won the gold medal.", ["True", "False"], 0, "First place."],
  ["It is raining outside.", ["True", "False"], 1, "The birds are chirping."],
  ["The library is open.", ["True", "False"], 0, "Welcome in."],
  ["She is twenty years old.", ["True", "False"], 1, "She said she's eighteen."],
  ["They are eating pizza.", ["True", "False"], 0, "Cheesy sounds."],
  ["The cat is on the roof.", ["True", "False"], 0, "Meow from above."],
  ["He lost his phone.", ["True", "False"], 0, "He can't find it."],
  ["The movie was boring.", ["True", "False"], 1, "She said it was amazing."],
  ["The sun is setting.", ["True", "False"], 0, "Evening sky."],
  ["She has a red bag.", ["True", "False"], 0, "The color was mentioned."],
  ["They are going to Paris.", ["True", "False"], 0, "Flight booked."],
  ["The water is freezing.", ["True", "False"], 1, "It is lukewarm."],
  ["He is a fast runner.", ["True", "False"], 0, "He won the race."],
  ["The party is tomorrow.", ["True", "False"], 0, "Mark your calendar."],
  ["She forgot her homework.", ["True", "False"], 0, "Oops!"],
  ["The bank is closed.", ["True", "False"], 1, "It opens till 5."],
  ["He plays the guitar.", ["True", "False"], 0, "Strumming sounds."],
  ["It is a windy day.", ["True", "False"], 0, "Howling wind."],
  ["The cake is delicious.", ["True", "False"], 0, "Yum!"],
  ["She is a teacher.", ["True", "False"], 1, "She is a student."],
  ["They have a big dog.", ["True", "False"], 0, "Barking from a giant."],
  ["The mountain is high.", ["True", "False"], 0, "Tall peak."],
  ["He wears glasses.", ["True", "False"], 0, "For better vision."],
  ["The car is fast.", ["True", "False"], 0, "Vroom!"],
  ["She has long hair.", ["True", "False"], 0, "Down to her waist."],
  ["The sky is cloudy.", ["True", "False"], 1, "It is perfectly clear."],
  ["They are playing soccer.", ["True", "False"], 0, "Kicking sounds."],
  ["The library is quiet.", ["True", "False"], 0, "Shh!"],
  ["He is feeling happy.", ["True", "False"], 0, "Laughing sounds."],
  ["The pizza is cold.", ["True", "False"], 1, "It's steaming hot."],
  ["She is reading a book.", ["True", "False"], 0, "Page turning."],
  ["The store is empty.", ["True", "False"], 1, "It is very crowded."],
  ["He has a new car.", ["True", "False"], 0, "Shiny and new."],
  ["The exam was easy.", ["True", "False"], 1, "It was very hard."],
];

// ── soundImageMatch ──
const simData = [
  ["Apple", ["apple_img", "orange_img", "banana_img", "grape_img"], 0, "Red fruit."],
  ["Car", ["car_img", "bike_img", "bus_img", "plane_img"], 0, "Four wheels."],
  ["Dog", ["dog_img", "cat_img", "bird_img", "fish_img"], 0, "Barking animal."],
  ["Pizza", ["pizza_img", "burger_img", "salad_img", "pasta_img"], 0, "Italian dish."],
  ["Book", ["glasses_img", "book_img", "pen_img", "bag_img"], 1, "Reading material."],
  ["Phone", ["phone_img", "watch_img", "laptop_img", "tablet_img"], 0, "Mobile device."],
  ["Tree", ["tree_img", "flower_img", "grass_img", "leaf_img"], 0, "Tall plant."],
  ["Sun", ["sun_img", "moon_img", "star_img", "cloud_img"], 0, "Bright star."],
  ["House", ["house_img", "tent_img", "castle_img", "hut_img"], 0, "Residence."],
  ["Shirt", ["shirt_img", "pants_img", "hat_img", "shoes_img"], 0, "Clothing."],
  ["Milk", ["milk_img", "juice_img", "water_img", "soda_img"], 0, "White drink."],
  ["Clock", ["clock_img", "watch_img", "calendar_img", "timer_img"], 0, "Ticking item."],
  ["Bird", ["bird_img", "butterfly_img", "bee_img", "plane_img"], 0, "Flying animal."],
  ["Shoes", ["shoes_img", "socks_img", "boots_img", "sandals_img"], 0, "Footwear."],
  ["Fish", ["fish_img", "shark_img", "whale_img", "crab_img"], 0, "Swimming animal."],
  ["Cake", ["cake_img", "cookie_img", "pie_img", "bread_img"], 0, "Sweet dessert."],
  ["Chair", ["chair_img", "table_img", "sofa_img", "bed_img"], 0, "Seat."],
  ["Guitar", ["guitar_img", "piano_img", "drum_img", "violin_img"], 0, "Instrument."],
  ["Keys", ["keys_img", "lock_img", "door_img", "handle_img"], 0, "Metal items."],
  ["Smile", ["smile_img", "cry_img", "angry_img", "bored_img"], 0, "Happy face."],
  ["Rain", ["rain_img", "snow_img", "wind_img", "sun_img"], 0, "Wet weather."],
  ["Bread", ["bread_img", "cheese_img", "meat_img", "egg_img"], 0, "Bakery item."],
  ["Hat", ["hat_img", "cap_img", "crown_img", "helmet_img"], 0, "Headwear."],
  ["Bus", ["bus_img", "train_img", "car_img", "van_img"], 0, "Public transport."],
  ["Pencil", ["pencil_img", "pen_img", "marker_img", "eraser_img"], 0, "Writing tool."],
  ["Coffee", ["coffee_img", "tea_img", "milk_img", "water_img"], 0, "Hot caffeine."],
  ["Beach", ["beach_img", "forest_img", "desert_img", "city_img"], 0, "Sand and sea."],
  ["Airplane", ["plane_img", "rocket_img", "helicopter_img", "balloon_img"], 0, "Flying vehicle."],
  ["Flower", ["flower_img", "tree_img", "bush_img", "grass_img"], 0, "Pretty bloom."],
  ["Hammer", ["hammer_img", "saw_img", "drill_img", "wrench_img"], 0, "Building tool."],
  ["Glasses", ["glasses_img", "mask_img", "hat_img", "ring_img"], 0, "Eye wear."],
  ["Ring", ["ring_img", "necklace_img", "watch_img", "belt_img"], 0, "Finger jewelry."],
  ["Star", ["star_img", "moon_img", "planet_img", "sun_img"], 0, "Night light."],
  ["Banana", ["banana_img", "apple_img", "pear_img", "mango_img"], 0, "Yellow fruit."],
  ["Elephant", ["elephant_img", "lion_img", "tiger_img", "bear_img"], 0, "Large animal."],
  ["Window", ["window_img", "door_img", "wall_img", "roof_img"], 0, "Glass pane."],
  ["Candle", ["candle_img", "lamp_img", "torch_img", "match_img"], 0, "Wax light."],
  ["Dolphin", ["dolphin_img", "shark_img", "fish_img", "seal_img"], 0, "Smart swimmer."],
  ["Cloud", ["cloud_img", "sun_img", "moon_img", "rain_img"], 0, "White sky object."],
  ["Moon", ["moon_img", "sun_img", "star_img", "earth_img"], 0, "Night orb."],
  ["Bag", ["bag_img", "wallet_img", "pouch_img", "box_img"], 0, "Carrying item."],
  ["Socks", ["socks_img", "shoes_img", "gloves_img", "scarf_img"], 0, "Foot wear."],
  ["Bed", ["bed_img", "sofa_img", "chair_img", "pillow_img"], 0, "Sleeping place."],
  ["Juice", ["juice_img", "milk_img", "water_img", "coffee_img"], 0, "Fruit drink."],
  ["Park", ["park_img", "street_img", "mall_img", "gym_img"], 0, "Green space."],
  ["Truck", ["truck_img", "car_img", "van_img", "jeep_img"], 0, "Heavy vehicle."],
  ["Egg", ["egg_img", "nest_img", "bird_img", "chicken_img"], 0, "Shell food."],
  ["Butterfly", ["butterfly_img", "bee_img", "fly_img", "moth_img"], 0, "Winged insect."],
  ["Ice", ["ice_img", "water_img", "steam_img", "snow_img"], 0, "Frozen water."],
  ["Hand", ["hand_img", "foot_img", "arm_img", "leg_img"], 0, "Part of arm."],
];

// ── fastSpeechDecoder ──
const fsdData = [
  ["I'm gonna go now.", ["I am going to go now", "I go now", "I'm go now", "I gonna go"], 0, "Gonna = Going to."],
  ["Whatcha doin'?", ["What are you doing?", "What you do?", "What's you doing?", "Watch you doing?"], 0, "Whatcha = What are you."],
  ["Gimme a sec.", ["Give me a second", "Give me a sec", "Get me a sec", "Gimme sec"], 0, "Gimme = Give me."],
  ["Dunno what happened.", ["I don't know what happened", "Do know what happened", "Done know what happened", "Dunno what happened"], 0, "Dunno = Don't know."],
  ["Shoulda told me.", ["You should have told me", "Should tell me", "Shoulda tell me", "Should have tell me"], 0, "Shoulda = Should have."],
  ["Coulda been worse.", ["It could have been worse", "Could be worse", "Coulda be worse", "Could have be worse"], 0, "Coulda = Could have."],
  ["Gotcha covered.", ["I have got you covered", "Got you covered", "Gotcha cover", "Got cover"], 0, "Gotcha = Got you."],
  ["Lemme see that.", ["Let me see that", "Let me saw that", "Lemme saw that", "Let see that"], 0, "Lemme = Let me."],
  ["Outta time.", ["We are out of time", "Out of time", "Outta time", "Out time"], 0, "Outta = Out of."],
  ["Kindda hungry.", ["I am kind of hungry", "Kind of hungry", "Kindda hungry", "Kind hungry"], 0, "Kindda = Kind of."],
  ["Wanna join us?", ["Do you want to join us?", "Wanna join?", "Want join us?", "You wanna join?"], 0, "Wanna = Want to."],
  ["Ha f'ta leave.", ["I have to leave", "I has to leave", "Have to left", "I have leave"], 0, "Ha f'ta = Have to."],
  ["Needta finish this.", ["I need to finish this", "Need finish this", "Needta finish", "Needed finish"], 0, "Needta = Need to."],
  ["Tryna help ya.", ["I am trying to help you", "Try to help you", "Tryna help you", "Trying help"], 0, "Tryna = Trying to."],
  ["Usedta live there.", ["I used to live there", "Use to live", "Usedta live", "Used to lived"], 0, "Usedta = Used to."],
  ["C'mon, let's go.", ["Come on, let us go", "Come on, lets go", "Cmon lets go", "Come go"], 0, "C'mon = Come on."],
  ["S'up man?", ["What is up, man?", "Sup man?", "Is up man?", "What up man?"], 0, "S'up = What's up."],
  ["Ya think so?", ["Do you think so?", "You think so?", "Ya think?", "You think?"], 0, "Ya = You."],
  ["'S cool.", ["It is cool", "Is cool", "S cool", "It cool"], 0, "'S = It is."],
  ["D'ya want some?", ["Do you want some?", "Do you wanted?", "Dya want?", "Do want?"], 0, "D'ya = Do you."],
  ["'Bye for now.", ["Goodbye for now", "Bye for now", "Bye now", "Good bye"], 0, "'Bye = Goodbye."],
  ["See ya later.", ["See you later", "See ya", "Seen ya", "Seeing you"], 0, "Ya = You."],
  ["Hava nice day.", ["Have a nice day", "Have nice day", "Hava nice", "Have a day"], 0, "Hava = Have a."],
  ["I'ma do it.", ["I am going to do it", "I'ma do", "I am do it", "I go do it"], 0, "I'ma = I am going to."],
  ["'Zat right?", ["Is that right?", "That right?", "Zat right?", "Is that"], 0, "'Zat = Is that."],
  ["'Lo there.", ["Hello there", "Lo there", "Hello", "There"], 0, "'Lo = Hello."],
  ["'T's mine.", ["It is mine", "T's mine", "It mine", "Mine"], 0, "'T's = It is."],
  ["I'd've gone.", ["I would have gone", "I'd have gone", "I would gone", "I'd've go"], 0, "I'd've = I would have."],
  ["'R ya ready?", ["Are you ready?", "R ya ready?", "Are ready?", "You ready?"], 0, "'R = Are."],
  ["'M hungry.", ["I am hungry", "M hungry", "I hungry", "Hungry"], 0, "'M = I am."],
  ["'Ve a look.", ["Have a look", "Ve a look", "Have look", "Look"], 0, "'Ve = Have."],
  ["'S okay.", ["It is okay", "S okay", "It okay", "Okay"], 0, "'S = It is."],
  ["'Ll be there.", ["I will be there", "Ll be there", "I'll be there", "Be there"], 0, "'Ll = Will."],
  ["'D like that.", ["I would like that", "D like that", "I'd like that", "Like that"], 0, "'D = Would."],
  ["'N' you?", ["And you?", "N you?", "And your?", "You?"], 0, "'N' = And."],
  ["'Cos I said so.", ["Because I said so", "Cos I said so", "Because said so", "Cause I said"], 0, "'Cos = Because."],
  ["'Kay, let's go.", ["Okay, let us go", "Kay lets go", "Okay lets go", "Go"], 0, "'Kay = Okay."],
  ["'Twas fun.", ["It was fun", "Twas fun", "It fun", "Fun"], 0, "'Twas = It was."],
  ["'R'n'B music.", ["Rhythm and Blues music", "RnB music", "R and B", "Music"], 0, "'n' = and."],
  ["'T'is the season.", ["It is the season", "Tis the season", "It season", "Season"], 0, "'T'is = It is."],
  ["'Bout time.", ["About time", "Bout time", "Time", "It's time"], 0, "'Bout = About."],
  ["'Scuse me.", ["Excuse me", "Scuse me", "Excuse", "Me"], 0, "'Scuse = Excuse."],
  ["'Round the corner.", ["Around the corner", "Round the corner", "Around corner", "Corner"], 0, "'Round = Around."],
  ["'Sides that.", ["Besides that", "Sides that", "Besides", "That"], 0, "'Sides = Besides."],
  ["'Cept for him.", ["Except for him", "Cept for him", "Except him", "Him"], 0, "'Cept = Except."],
  ["'Stablish it.", ["Establish it", "Stablish it", "Establish", "It"], 0, "'Stablish = Establish."],
  ["'Fore long.", ["Before long", "Fore long", "Before", "Long"], 0, "'Fore = Before."],
  ["'Tween them.", ["Between them", "Tween them", "Between", "Them"], 0, "'Tween = Between."],
  ["'Neath the sun.", ["Beneath the sun", "Neath the sun", "Beneath", "Sun"], 0, "'Neath = Beneath."],
  ["'Midst the chaos.", ["Amidst the chaos", "Midst the chaos", "Amidst", "Chaos"], 0, "'Midst = Amidst."],
];

// ── emotionRecognition ──
const erData = [
  ["I can't believe I won!", ["Excited", "Sad", "Angry", "Bored"], 0, "Victory exclamation."],
  ["It's just... I lost my cat.", ["Sad", "Happy", "Surprised", "Calm"], 0, "Loss of a pet."],
  ["How many times do I have to tell you?!", ["Angry", "Happy", "Tired", "Fearful"], 0, "Frustrated repetition."],
  ["Whoa! What is that?!", ["Surprised", "Sad", "Bored", "Angry"], 0, "Unexpected discovery."],
  ["Whatever, I don't care.", ["Bored", "Excited", "Happy", "Fearful"], 0, "Indifference."],
  ["I hope I pass the test...", ["Anxious", "Happy", "Angry", "Bored"], 0, "Worry about future."],
  ["This is so peaceful.", ["Calm", "Angry", "Surprised", "Excited"], 0, "Quiet and relaxation."],
  ["Is someone there? Hello?", ["Fearful", "Happy", "Bored", "Calm"], 0, "Dark room suspicion."],
  ["I'm so proud of you!", ["Happy", "Sad", "Angry", "Bored"], 0, "Achievement praise."],
  ["I just want to go home.", ["Tired", "Excited", "Surprised", "Happy"], 0, "Exhaustion."],
  ["I'm so lonely tonight.", ["Lonely", "Excited", "Angry", "Calm"], 0, "Lack of company."],
  ["That's so funny, haha!", ["Amused", "Sad", "Fearful", "Tired"], 0, "Laughter."],
  ["I'm really worried about her.", ["Concerned", "Happy", "Bored", "Surprised"], 0, "Thinking of others."],
  ["Get out of here now!", ["Furious", "Calm", "Happy", "Bored"], 0, "Extreme anger."],
  ["Wow, this view is amazing.", ["Awestruck", "Sad", "Angry", "Tired"], 0, "Beautiful scenery."],
  ["I'm not sure what to do.", ["Confused", "Happy", "Excited", "Bored"], 0, "Uncertainty."],
  ["I feel so guilty.", ["Remorseful", "Happy", "Angry", "Excited"], 0, "Regret for actions."],
  ["I'm so jealous of him.", ["Envious", "Calm", "Sad", "Bored"], 0, "Wanting what others have."],
  ["I'm so relieved it's over.", ["Relieved", "Angry", "Fearful", "Tired"], 0, "End of stress."],
  ["I'm so disgusted by this.", ["Disgusted", "Happy", "Excited", "Calm"], 0, "Revulsion."],
  ["I'm so embarrassed right now.", ["Embarrassed", "Angry", "Bored", "Calm"], 0, "Social awkwardness."],
  ["I'm so grateful for your help.", ["Grateful", "Sad", "Fearful", "Tired"], 0, "Thanks."],
  ["I'm so optimistic about this.", ["Hopeful", "Sad", "Angry", "Bored"], 0, "Positive future."],
  ["I'm so pessimistic today.", ["Gloomy", "Happy", "Excited", "Calm"], 0, "Negative future."],
  ["I'm so bored of this song.", ["Bored", "Excited", "Happy", "Angry"], 0, "Lack of interest."],
  ["I'm so curious about that.", ["Inquisitive", "Sad", "Fearful", "Tired"], 0, "Wanting to know."],
  ["I'm so satisfied with my meal.", ["Content", "Angry", "Bored", "Calm"], 0, "Full and happy."],
  ["I'm so frustrated with this.", ["Irritated", "Happy", "Excited", "Calm"], 0, "Blockage in goals."],
  ["I'm so surprised to see you!", ["Shocked", "Sad", "Angry", "Tired"], 0, "Unexpected guest."],
  ["I'm so nervous for the stage.", ["Apprehensive", "Happy", "Bored", "Calm"], 0, "Performance anxiety."],
  ["I'm so ashamed of myself.", ["Ashamed", "Excited", "Happy", "Calm"], 0, "Moral failure."],
  ["I'm so brave to do this.", ["Confident", "Sad", "Fearful", "Tired"], 0, "Courage."],
  ["I'm so shy in groups.", ["Timid", "Angry", "Bored", "Calm"], 0, "Social withdrawal."],
  ["I'm so stubborn about it.", ["Determined", "Happy", "Excited", "Calm"], 0, "Refusal to change."],
  ["I'm so humble today.", ["Modest", "Angry", "Bored", "Calm"], 0, "Lack of pride."],
  ["I'm so arrogant sometimes.", ["Conceited", "Sad", "Fearful", "Tired"], 0, "Excessive pride."],
  ["I'm so cruel to them.", ["Mean", "Happy", "Excited", "Calm"], 0, "Lack of empathy."],
  ["I'm so kind to animals.", ["Compassionate", "Angry", "Bored", "Calm"], 0, "Empathy."],
  ["I'm so lazy today.", ["Sluggish", "Excited", "Happy", "Calm"], 0, "Lack of energy."],
  ["I'm so energetic now!", ["Vibrant", "Sad", "Fearful", "Tired"], 0, "High energy."],
  ["I'm so peaceful here.", ["Serene", "Angry", "Bored", "Calm"], 0, "Inner peace."],
  ["I'm so stressed out.", ["Overwhelmed", "Happy", "Excited", "Calm"], 0, "High pressure."],
  ["I'm so relaxed now.", ["Mellow", "Angry", "Fearful", "Tired"], 0, "Low pressure."],
  ["I'm so curious why.", ["Interested", "Sad", "Bored", "Calm"], 0, "Investigation."],
  ["I'm so suspicious of him.", ["Skeptical", "Happy", "Excited", "Calm"], 0, "Lack of trust."],
  ["I'm so trustworthy.", ["Reliable", "Angry", "Bored", "Calm"], 0, "Dependability."],
  ["I'm so impatient!", ["Restless", "Sad", "Fearful", "Tired"], 0, "Lack of patience."],
  ["I'm so patient with you.", ["Tolerant", "Angry", "Excited", "Calm"], 0, "Endurance."],
  ["I'm so creative today.", ["Inspired", "Sad", "Bored", "Calm"], 0, "New ideas."],
  ["I'm so dull today.", ["Uninspired", "Happy", "Excited", "Calm"], 0, "Lack of ideas."],
];

// ── detailSpotlight ──
const dsData = [
  ["The blue bird flew over the red house.", "What color was the house?", ["Red", "Blue", "Green", "White"], 0, "Check the second adjective."],
  ["John bought three apples and two bananas.", "How many apples did John buy?", ["Three", "Two", "Five", "Zero"], 0, "First fruit mentioned."],
  ["The meeting is at 10 AM in Room 402.", "Where is the meeting?", ["Room 402", "Room 10", "At home", "At 10 AM"], 0, "Room number."],
  ["Mary has a cat named Luna.", "What is the cat's name?", ["Luna", "Mary", "Sol", "Stella"], 0, "Pet's name."],
  ["He arrived at the station at 8 PM.", "When did he arrive?", ["8 PM", "8 AM", "Morning", "Midnight"], 0, "Time of day."],
  ["The cake cost fifteen dollars.", "How much was the cake?", ["$15", "$50", "$5", "$10"], 0, "Number fifteen."],
  ["I am wearing a yellow shirt.", "What is the speaker wearing?", ["Yellow shirt", "Red hat", "Blue jeans", "Green dress"], 0, "Color and item."],
  ["The library is next to the bank.", "Where is the library?", ["Next to the bank", "Inside the bank", "Far from the bank", "Across the park"], 0, "Relative location."],
  ["They traveled to Japan in July.", "When did they go to Japan?", ["July", "June", "January", "August"], 0, "Month name."],
  ["The password is 'BlueSky7'.", "What is the password?", ["BlueSky7", "SkyBlue7", "BlueSky", "7BlueSky"], 0, "Exact string."],
  ["The flight number is UA892.", "What is the flight number?", ["UA892", "UA829", "AU892", "UA982"], 0, "Letters and numbers."],
  ["Lunch is served from 12:30 to 1:30.", "When does lunch start?", ["12:30", "1:30", "12:00", "1:00"], 0, "Start time."],
  ["The code for the gate is 5591.", "What is the gate code?", ["5591", "5519", "5951", "5195"], 0, "Four digits."],
  ["She bought a blue car with leather seats.", "What color is the car?", ["Blue", "Red", "Black", "White"], 0, "Color."],
  ["The shop closes at 9 PM on weekdays.", "When does the shop close?", ["9 PM", "10 PM", "8 PM", "11 PM"], 0, "Closing time."],
  ["He lives on the 5th floor of the building.", "Which floor does he live on?", ["5th", "4th", "6th", "7th"], 0, "Ordinal number."],
  ["The book has 320 pages.", "How many pages are in the book?", ["320", "302", "230", "312"], 0, "Page count."],
  ["The temperature today is 25 degrees.", "What is the temperature?", ["25", "15", "35", "20"], 0, "Number."],
  ["The dog's name is Rex.", "What is the dog's name?", ["Rex", "Max", "Buddy", "Rocky"], 0, "Name."],
  ["They are staying at the Hilton Hotel.", "Where are they staying?", ["Hilton Hotel", "Marriott", "Hyatt", "Holiday Inn"], 0, "Hotel name."],
  ["The train platform is 9B.", "Which platform is the train on?", ["9B", "9A", "8B", "10B"], 0, "Platform number."],
  ["The movie is 2 hours long.", "How long is the movie?", ["2 hours", "1 hour", "3 hours", "90 mins"], 0, "Duration."],
  ["The address is 42 Wallaby Way.", "What is the house number?", ["42", "24", "44", "22"], 0, "Street number."],
  ["She has two brothers and one sister.", "How many sisters does she have?", ["One", "Two", "Three", "Zero"], 0, "Sibling count."],
  ["The concert starts at 7:45 PM.", "What time does the concert start?", ["7:45 PM", "7:15 PM", "8:15 PM", "7:30 PM"], 0, "Start time."],
  ["The box is 10kg heavy.", "How heavy is the box?", ["10kg", "5kg", "20kg", "15kg"], 0, "Weight."],
  ["He is a 2nd year student.", "Which year is he in?", ["2nd", "1st", "3rd", "4th"], 0, "Academic year."],
  ["The cat is 5 years old.", "How old is the cat?", ["5", "3", "7", "2"], 0, "Age."],
  ["The car plate is ABC 123.", "What is the plate number?", ["ABC 123", "CBA 321", "BCA 213", "ABC 321"], 0, "License plate."],
  ["The meeting room is 'Emerald'.", "What is the room name?", ["Emerald", "Ruby", "Sapphire", "Diamond"], 0, "Gemstone name."],
  ["The discount is 20 percent.", "How much is the discount?", ["20%", "10%", "30%", "15%"], 0, "Percentage."],
  ["The population is 5 million.", "What is the population?", ["5 million", "1 million", "10 million", "2 million"], 0, "Population."],
  ["The river is 200km long.", "How long is the river?", ["200km", "100km", "300km", "400km"], 0, "Length."],
  ["The speed limit is 60 mph.", "What is the speed limit?", ["60 mph", "50 mph", "70 mph", "80 mph"], 0, "Speed."],
  ["The score was 3 to 1.", "What was the winning score?", ["3", "1", "2", "4"], 0, "Points."],
  ["The battery is at 15 percent.", "What is the battery level?", ["15%", "50%", "10%", "5%"], 0, "Battery."],
  ["The flight is 12 hours long.", "How long is the flight?", ["12 hours", "10 hours", "14 hours", "8 hours"], 0, "Time."],
  ["The date is October 5th.", "What is the day?", ["5th", "15th", "25th", "1st"], 0, "Date."],
  ["The hotel room is 1204.", "What is the room number?", ["1204", "1024", "1240", "1420"], 0, "Number."],
  ["The book cost $24.99.", "How much was the book?", ["$24.99", "$29.99", "$19.99", "$25.00"], 0, "Price."],
  ["The team has 11 players.", "How many players are in the team?", ["11", "10", "12", "9"], 0, "Team size."],
  ["The park is 2 miles away.", "How far is the park?", ["2 miles", "1 mile", "3 miles", "5 miles"], 0, "Distance."],
  ["The baby weighs 3.5kg.", "How much does the baby weigh?", ["3.5kg", "3kg", "4kg", "2.5kg"], 0, "Weight."],
  ["The train stops at 5 stations.", "How many stations are there?", ["5", "3", "7", "4"], 0, "Count."],
  ["The coffee has 2 sugars.", "How many sugars are in the coffee?", ["2", "1", "3", "0"], 0, "Sweetness."],
  ["The laptop has a 15-inch screen.", "What is the screen size?", ["15-inch", "13-inch", "17-inch", "14-inch"], 0, "Inches."],
  ["The movie was rated 4 stars.", "What was the rating?", ["4 stars", "3 stars", "5 stars", "2 stars"], 0, "Stars."],
  ["The building has 20 floors.", "How many floors are there?", ["20", "10", "30", "15"], 0, "Floors."],
  ["The shirt is 100 percent cotton.", "What is the material?", ["Cotton", "Silk", "Wool", "Linen"], 0, "Fabric."],
  ["The bus arrives every 15 minutes.", "How often does the bus arrive?", ["15 mins", "10 mins", "20 mins", "30 mins"], 0, "Frequency."],
];

// ── listeningInference ──
const liData = [
  ["The ground is wet and everyone has umbrellas.", "What recently happened?", ["It rained", "It snowed", "A fire happened", "It was sunny"], 0, "Wet ground + umbrellas."],
  ["He is wearing a white coat and has a stethoscope.", "What is his job?", ["Doctor", "Chef", "Pilot", "Artist"], 0, "Stethoscope usage."],
  ["The lights are out and people are holding candles.", "What happened?", ["Power outage", "A party", "Morning", "Summer"], 0, "No lights + candles."],
  ["She is carrying a suitcase and looking at a gate number.", "Where is she?", ["Airport", "Library", "Gym", "Office"], 0, "Suitcase + gate."],
  ["People are clapping and the actors are bowing.", "Where are they?", ["Theater", "Park", "Hospital", "School"], 0, "Actors bowing."],
  ["The oven is on and there is a sweet smell.", "What is she doing?", ["Baking", "Cleaning", "Sleeping", "Painting"], 0, "Oven + sweet smell."],
  ["He is shivering and wearing three jackets.", "How is the weather?", ["Cold", "Hot", "Rainy", "Sunny"], 0, "Shivering + layers."],
  ["The bell rang and students are running outside.", "What time is it?", ["Recess/End of school", "Midnight", "Lunch", "Exam time"], 0, "Bell + running students."],
  ["She has a camera and is taking photos of the Eiffel Tower.", "Where is she?", ["Paris", "London", "New York", "Tokyo"], 0, "Eiffel Tower location."],
  ["The referee blew the whistle and the crowd cheered.", "What is happening?", ["A sports game", "A concert", "A movie", "A class"], 0, "Referee whistle."],
  ["There are many animals in cages and children with balloons.", "Where are they?", ["Zoo", "Park", "Museum", "Cinema"], 0, "Animals + cages."],
  ["The waiter is bringing a menu and some water.", "Where are they?", ["Restaurant", "Office", "Gym", "School"], 0, "Waiter + menu."],
  ["He is sitting in a cockpit and checking the fuel levels.", "What is his job?", ["Pilot", "Driver", "Captain", "Doctor"], 0, "Cockpit + fuel."],
  ["The leaves are turning yellow and falling to the ground.", "What season is it?", ["Autumn", "Spring", "Summer", "Winter"], 0, "Falling leaves."],
  ["Everyone is wearing black and it is very quiet and sad.", "Where are they?", ["Funeral", "Wedding", "Birthday", "Concert"], 0, "Black clothes + sad."],
  ["She is standing on a podium with a medal around her neck.", "What happened?", ["She won a race", "She lost a game", "She is tired", "She is sleeping"], 0, "Podium + medal."],
  ["The siren is loud and red lights are flashing.", "What is passing by?", ["Fire truck", "Taxi", "Bus", "Bicycle"], 0, "Siren + flashing lights."],
  ["He is holding a leash and the animal is barking.", "What is he doing?", ["Walking his dog", "Eating lunch", "Reading a book", "Sleeping"], 0, "Leash + barking."],
  ["The car has a flat tire and they are standing by the road.", "What is the problem?", ["Vehicle breakdown", "Out of fuel", "Lost way", "Traffic jam"], 0, "Flat tire."],
  ["There is popcorn everywhere and the big screen is on.", "Where are they?", ["Cinema", "Library", "Kitchen", "Gym"], 0, "Popcorn + big screen."],
  ["He is wearing a helmet and riding on two wheels.", "What is he doing?", ["Riding a bike", "Driving a car", "Flying a plane", "Walking"], 0, "Helmet + two wheels."],
  ["The grass is covered in white and children are making a man.", "What happened?", ["It snowed", "It rained", "It was sunny", "It was windy"], 0, "White grass + snow man."],
  ["She is wearing a swimsuit and has a towel.", "Where is she going?", ["Swimming pool", "Office", "Cinema", "Library"], 0, "Swimsuit + towel."],
  ["The crowd is screaming and the singer is on stage.", "Where are they?", ["Concert", "Museum", "Church", "Bank"], 0, "Crowd + singer."],
  ["He is holding a fishing rod by the lake.", "What is he doing?", ["Fishing", "Swimming", "Running", "Eating"], 0, "Fishing rod + lake."],
  ["The airplane is tilting and the 'fasten seatbelt' sign is on.", "What is happening?", ["Turbulence", "Landing", "Takeoff", "Parking"], 0, "Tilt + seatbelt sign."],
  ["She is wearing a white dress and walking towards a man in a suit.", "Where is she?", ["Wedding", "Office", "Hospital", "School"], 0, "White dress + man in suit."],
  ["The building is shaking and items are falling from shelves.", "What is happening?", ["Earthquake", "Wind", "Rain", "Snow"], 0, "Shaking building."],
  ["He is holding a magnifying glass and looking at a footprint.", "What is his job?", ["Detective", "Chef", "Pilot", "Artist"], 0, "Magnifying glass + footprint."],
  ["The sky is dark at 12 PM and the wind is very strong.", "What is happening?", ["Solar eclipse/Storm", "Night time", "Morning", "Summer"], 0, "Dark sky at noon."],
  ["She is putting on a pair of running shoes and a headband.", "What is she about to do?", ["Exercise", "Sleep", "Eat", "Read"], 0, "Running shoes + headband."],
  ["There is a lot of dust and the sounds of heavy machines.", "Where are they?", ["Construction site", "Library", "Hospital", "Garden"], 0, "Dust + heavy machines."],
  ["He is holding a menu and looking at his watch.", "What is he doing?", ["Waiting for food", "Sleeping", "Running", "Painting"], 0, "Menu + watch."],
  ["The ship is swaying and people are feeling sick.", "Where are they?", ["At sea", "On a bus", "In a plane", "At home"], 0, "Swaying ship + sickness."],
  ["She is carrying a basket and picking up colorful eggs.", "What holiday is it?", ["Easter", "Christmas", "Halloween", "New Year"], 0, "Basket + colorful eggs."],
  ["There is a lot of smoke and people are running out of the building.", "What is happening?", ["Fire", "Party", "Meeting", "Class"], 0, "Smoke + running out."],
  ["He is wearing a suit and holding a briefcase.", "Where is he likely going?", ["Work/Office", "Gym", "Beach", "Park"], 0, "Suit + briefcase."],
  ["The room is decorated with balloons and there is a cake.", "What is happening?", ["Birthday party", "Meeting", "Exam", "Cleaning"], 0, "Balloons + cake."],
  ["She is holding a map and looking at a tall building.", "What is she likely doing?", ["Sightseeing", "Working", "Sleeping", "Eating"], 0, "Map + tall building."],
  ["The car is stopped at a red light.", "What is the driver doing?", ["Waiting", "Speeding", "Turning", "Parking"], 0, "Red light."],
  ["He is wearing a uniform and delivering a package.", "What is his job?", ["Delivery person", "Doctor", "Pilot", "Chef"], 0, "Uniform + package."],
  ["The baby is crawling towards a toy.", "How old is the baby likely?", ["A few months/Infant", "Five years", "Ten years", "Adult"], 0, "Crawling behavior."],
  ["She is holding an ice cream cone and it is melting fast.", "How is the weather?", ["Hot", "Cold", "Rainy", "Windy"], 0, "Melting ice cream."],
  ["The players are shaking hands after the game.", "What is happening?", ["Sportsmanship/Game end", "Game start", "A fight", "A timeout"], 0, "Shaking hands."],
  ["He is sitting in a library with a pile of books.", "What is he likely doing?", ["Studying", "Eating", "Running", "Singing"], 0, "Library + books."],
  ["The cat is staring at a mouse hole.", "What is the cat doing?", ["Hunting", "Sleeping", "Playing", "Eating"], 0, "Staring at hole."],
  ["She is wearing a lab coat and using a microscope.", "What is her job?", ["Scientist", "Artist", "Driver", "Chef"], 0, "Lab coat + microscope."],
  ["The bus is crowded and people are holding onto handles.", "What time is it likely?", ["Rush hour", "Midnight", "Morning", "Sunday"], 0, "Crowded bus."],
  ["He is holding a leash and a plastic bag.", "What is he doing?", ["Walking his dog", "Buying groceries", "Going to gym", "Sleeping"], 0, "Leash + bag."],
  ["The plane has landed and people are standing up.", "Where are they?", ["Destination reached", "Mid-air", "Takeoff", "Waiting"], 0, "Landed + standing."],
];

// ── ambientId ──
const aiData = [
  ["A loud siren is heard passing by.", "What made this sound?", ["Ambulance", "Ice cream truck", "Bicycle", "Bird"], 0, "Emergency sound."],
  ["The sound of birds chirping and leaves rustling.", "Where are you?", ["Park/Forest", "Factory", "Subway", "Library"], 0, "Nature sounds."],
  ["Water splashing and people laughing.", "Where are you?", ["Swimming pool", "Office", "Desert", "Cinema"], 0, "Water sounds."],
  ["The sound of typing and phones ringing.", "Where are you?", ["Office", "Kitchen", "Street", "Gym"], 0, "Typing + phones."],
  ["A loud roar followed by heavy rain.", "What is happening?", ["Thunderstorm", "Sunshine", "Wind", "Snow"], 0, "Roar = Thunder."],
  ["The sound of a bell and a door opening.", "Where are you?", ["Shop/Store", "Forest", "Ocean", "Airplane"], 0, "Customer arrival."],
  ["Waves crashing and seagulls calling.", "Where are you?", ["Beach", "Mountain", "City", "Tunnel"], 0, "Ocean sounds."],
  ["The sound of an engine starting and tires screeching.", "What is it?", ["Car", "Clock", "Radio", "Pen"], 0, "Automobile sounds."],
  ["Loud music and a crowd shouting.", "Where are you?", ["Concert", "Library", "Church", "Elevator"], 0, "Music + crowd."],
  ["The sound of wind howling through a crack.", "How is the weather?", ["Windy", "Sunny", "Hot", "Calm"], 0, "Howling sound."],
  ["Clinking of glasses and low chatter.", "Where are you?", ["Restaurant/Cafe", "Library", "Gym", "Subway"], 0, "Dining sounds."],
  ["Heavy breathing and the sound of a treadmill.", "Where are you?", ["Gym", "Office", "Park", "Kitchen"], 0, "Exercise sounds."],
  ["Beeping of a barcode scanner.", "Where are you?", ["Supermarket", "Forest", "Church", "Cinema"], 0, "Checkout sound."],
  ["The sound of a train horn and tracks rattling.", "What is it?", ["Train", "Car", "Bike", "Plane"], 0, "Rail transport."],
  ["Page turning and quiet whispers.", "Where are you?", ["Library", "Concert", "Market", "Street"], 0, "Reading sounds."],
  ["Dripping faucet and echo in the room.", "Where are you?", ["Bathroom", "Park", "Office", "Library"], 0, "Water echo."],
  ["Sound of a lawnmower.", "What is happening?", ["Gardening", "Cooking", "Driving", "Sleeping"], 0, "Cutting grass."],
  ["Crackling of wood and fire popping.", "What is it?", ["Campfire", "Rain", "Traffic", "Wind"], 0, "Burning wood."],
  ["The sound of a whistle blowing.", "Where are you?", ["Sports field", "Library", "Church", "Cinema"], 0, "Game start/end."],
  ["Barking and whining sounds.", "What is nearby?", ["Dog", "Cat", "Bird", "Car"], 0, "Canine."],
  ["Sizzling sound and a fan whirring.", "Where are you?", ["Kitchen", "Bedroom", "Office", "Park"], 0, "Cooking."],
  ["Heavy rain hitting a tin roof.", "How is the weather?", ["Stormy", "Sunny", "Windy", "Snowy"], 0, "Pattering sound."],
  ["Sound of a toilet flushing.", "Where are you?", ["Restroom", "Kitchen", "Living room", "Garden"], 0, "Water flush."],
  ["Beeping of a microwave.", "What is happening?", ["Food is ready", "Someone is calling", "Door is open", "Rain is coming"], 0, "End of timer."],
  ["Keyboard clicks and a mouse scroll.", "What is being used?", ["Computer", "Radio", "Oven", "Clock"], 0, "IT hardware."],
  ["Sound of a door being locked with a key.", "What is happening?", ["Securing the house", "Opening the door", "Painting the door", "Eating lunch"], 0, "Locking action."],
  ["Crunching of snow under boots.", "What season is it?", ["Winter", "Summer", "Autumn", "Spring"], 0, "Frozen ground."],
  ["The sound of a bell ringing in a tower.", "Where are you near?", ["Church/Town Hall", "Park", "River", "Airport"], 0, "Clock tower."],
  ["Whirring of a blender.", "What is being made?", ["Smoothie/Soup", "Cake", "Steak", "Salad"], 0, "Blending action."],
  ["Sound of a basketball bouncing.", "Where are you?", ["Court", "Field", "Office", "Library"], 0, "Sporting sound."],
  ["High-pitched scream of a tea kettle.", "What is ready?", ["Boiling water/Tea", "Coffee", "Soup", "Milk"], 0, "Steam pressure."],
  ["Sound of a zipper closing.", "What is being done?", ["Closing a bag/jacket", "Opening a box", "Writing a letter", "Eating"], 0, "Zip sound."],
  ["Heavy footsteps on a wooden floor.", "What is happening?", ["Someone is walking", "Someone is flying", "Someone is swimming", "Someone is sleeping"], 0, "Walking echo."],
  ["Sound of a camera shutter clicking.", "What is happening?", ["Photo being taken", "Video being played", "Song being sung", "Door being closed"], 0, "Photography."],
  ["Purring and soft scratching.", "What animal is it?", ["Cat", "Dog", "Bird", "Fish"], 0, "Feline."],
  ["Sound of a vacuum cleaner.", "What is happening?", ["Cleaning", "Cooking", "Sleeping", "Driving"], 0, "Suction sound."],
  ["Distant thunder rumble.", "What is coming?", ["Storm", "Sun", "Wind", "Snow"], 0, "Atmospheric sound."],
  ["Sound of a hairdryer.", "What is being done?", ["Drying hair", "Washing face", "Eating", "Reading"], 0, "Air flow."],
  ["Clatter of dishes being stacked.", "Where are you?", ["Kitchen/Dining", "Office", "Gym", "Park"], 0, "Plates."],
  ["Sound of a stapler.", "Where are you?", ["Office", "Garden", "Beach", "Kitchen"], 0, "Binding papers."],
  ["Distant hum of an airplane engine.", "Where are you?", ["Outside/In a plane", "In a basement", "In a library", "In a car"], 0, "Aviation sound."],
  ["Sound of scissors cutting paper.", "What is happening?", ["Crafting/Cutting", "Writing", "Painting", "Glueing"], 0, "Snipping sound."],
  ["Ringing of a bicycle bell.", "What is nearby?", ["Bicycle", "Car", "Bus", "Train"], 0, "Ding-ding."],
  ["Sound of a spoon stirring in a cup.", "What is being done?", ["Mixing a drink", "Eating soup", "Cutting meat", "Reading"], 0, "Stirring."],
  ["Humming of a refrigerator.", "Where are you?", ["Kitchen", "Bathroom", "Garden", "Attic"], 0, "Appliance sound."],
  ["Sound of a match being struck.", "What is being lit?", ["Candle/Fire", "Light bulb", "Radio", "TV"], 0, "Ignition."],
  ["Rustling of a candy wrapper.", "What is being opened?", ["Candy/Snack", "Book", "Letter", "Window"], 0, "Crinkling sound."],
  ["Sound of a car indicator (ticking).", "What is the car doing?", ["Turning", "Speeding", "Braking", "Stopping"], 0, "Signaling."],
  ["Echoing footsteps in a tunnel.", "Where are you?", ["Underground/Tunnel", "Open field", "Small room", "On a cloud"], 0, "Echo."],
  ["Sound of a coin falling into a slot.", "What is happening?", ["Vending machine/Payment", "Eating", "Sleeping", "Running"], 0, "Payment sound."],
];

const audioFillBlanks = afbData.map(d => FB(d[0], d[1], d[2], d[3], d[4], d[5]));
const audioMultipleChoice = amcData.map(d => S(d[0], d[0], d[1], d[2], d[3]));
const audioSentenceOrder = asoData.map(d => SO(d[0], d[1], d[2], d[3]));
const audioTrueFalse = atfData.map(d => S(d[0], d[0], d[1], d[2], d[3], 'Is the statement true or false?'));
const soundImageMatch = simData.map(d => S(d[0], d[0], d[1], d[2], d[3], 'Match the sound to the image.'));
const fastSpeechDecoder = fsdData.map(d => S(d[0], d[0], d[1], d[2], d[3], 'What did the speaker say?'));
const emotionRecognition = erData.map(d => S(d[0], d[0], d[1], d[2], d[3], 'Identify the emotion.'));
const detailSpotlight = dsData.map(d => P(d[0], d[1], d[2], d[3], d[4]));
const listeningInference = liData.map(d => P(d[0], d[1], d[2], d[3], d[4], 'Infer the situation.'));
const ambientId = aiData.map(d => S(d[0], d[1], d[2], d[3], d[4], 'Identify the sound source.'));

module.exports = {
  audioFillBlanks,
  audioMultipleChoice,
  audioSentenceOrder,
  audioTrueFalse,
  soundImageMatch,
  fastSpeechDecoder,
  emotionRecognition,
  detailSpotlight,
  listeningInference,
  ambientId,
};
