// Reading category pools - 10 games × 30 templates each
const C = (inst,fields,it) => ({instruction:inst,interactionType:it||'choice',fields});

// readAndAnswer: passage + question + 4 options
const readAndAnswer = [
  C('Read and answer.',{passage:"The Amazon rainforest covers over 5.5 million square kilometers across nine countries in South America.",question:"How many countries does the Amazon span?",options:["Five","Seven","Nine","Twelve"],correctAnswerIndex:2,hint:"Look for the number of countries."}),
  C('Read and answer.',{passage:"Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs that was still edible.",question:"How old was the honey found in Egyptian tombs?",options:["1,000 years","2,000 years","3,000 years","5,000 years"],correctAnswerIndex:2,hint:"Find the age mentioned."}),
  C('Read and answer.',{passage:"Octopuses have three hearts. Two pump blood to the gills, while the third pumps it to the rest of the body.",question:"How many hearts does an octopus have?",options:["One","Two","Three","Four"],correctAnswerIndex:2,hint:"The number is stated directly."}),
  C('Read and answer.',{passage:"The Great Barrier Reef is the largest coral reef system in the world, stretching over 2,300 kilometers along Australia's coast.",question:"Where is the Great Barrier Reef located?",options:["Brazil","India","Australia","Japan"],correctAnswerIndex:2,hint:"Look for the country name."}),
  C('Read and answer.',{passage:"Leonardo da Vinci painted the Mona Lisa between 1503 and 1519. It now hangs in the Louvre Museum in Paris.",question:"Where is the Mona Lisa displayed?",options:["British Museum","The Louvre","Metropolitan Museum","Uffizi Gallery"],correctAnswerIndex:1,hint:"Find the museum name."}),
  C('Read and answer.',{passage:"Water covers about 71 percent of the Earth's surface, but only 2.5 percent of it is freshwater.",question:"What percentage of Earth's water is freshwater?",options:["2.5%","10%","25%","50%"],correctAnswerIndex:0,hint:"Look for the freshwater percentage."}),
  C('Read and answer.',{passage:"Mount Everest is the tallest mountain on Earth at 8,849 meters above sea level. It is located on the border of Nepal and Tibet.",question:"How tall is Mount Everest?",options:["7,849 m","8,849 m","9,849 m","6,849 m"],correctAnswerIndex:1,hint:"Find the height in meters."}),
  C('Read and answer.',{passage:"The human brain weighs about 1.4 kilograms and uses approximately 20 percent of the body's total energy.",question:"How much energy does the brain use?",options:["5%","10%","20%","40%"],correctAnswerIndex:2,hint:"Look for the percentage of energy."}),
  C('Read and answer.',{passage:"Cheetahs are the fastest land animals, reaching speeds up to 112 kilometers per hour in short bursts.",question:"What is the top speed of a cheetah?",options:["80 km/h","96 km/h","112 km/h","130 km/h"],correctAnswerIndex:2,hint:"Find the speed mentioned."}),
  C('Read and answer.',{passage:"The Sahara Desert is the largest hot desert in the world, covering about 9.2 million square kilometers in North Africa.",question:"Where is the Sahara Desert?",options:["South America","Central Asia","North Africa","Australia"],correctAnswerIndex:2,hint:"Look for the continent."}),
  C('Read and answer.',{passage:"Butterflies taste with their feet. They have sensors on their legs that help them identify plants for laying eggs.",question:"How do butterflies taste things?",options:["With their tongues","With their antennae","With their feet","With their wings"],correctAnswerIndex:2,hint:"Look for body parts."}),
  C('Read and answer.',{passage:"The Dead Sea is nearly 10 times saltier than the ocean. Its high salt content makes it easy to float on the surface.",question:"How much saltier is the Dead Sea than the ocean?",options:["3 times","5 times","10 times","20 times"],correctAnswerIndex:2,hint:"Find the comparison number."}),
  C('Read and answer.',{passage:"Thomas Edison held 1,093 patents. His most famous invention was the practical incandescent light bulb.",question:"What was Edison's most famous invention?",options:["Telephone","Light bulb","Radio","Television"],correctAnswerIndex:1,hint:"Look for 'most famous'."}),
  C('Read and answer.',{passage:"Venus is the hottest planet in our solar system with surface temperatures reaching 465 degrees Celsius.",question:"Which planet is the hottest?",options:["Mercury","Mars","Venus","Jupiter"],correctAnswerIndex:2,hint:"The planet is named in the passage."}),
  C('Read and answer.',{passage:"Elephants are the only animals that cannot jump. Despite their size, they are excellent swimmers.",question:"What can elephants NOT do?",options:["Swim","Run","Jump","Walk"],correctAnswerIndex:2,hint:"Look for 'cannot'."}),
  C('Read and answer.',{passage:"The speed of light is approximately 300,000 kilometers per second. Light from the Sun takes about 8 minutes to reach Earth.",question:"How long does sunlight take to reach Earth?",options:["2 minutes","5 minutes","8 minutes","15 minutes"],correctAnswerIndex:2,hint:"Find the time for sunlight."}),
  C('Read and answer.',{passage:"Bananas are berries, but strawberries are not. Botanically, a berry develops from a single flower with one ovary.",question:"Which fruit is a true berry?",options:["Strawberry","Raspberry","Banana","Cherry"],correctAnswerIndex:2,hint:"The passage states it directly."}),
  C('Read and answer.',{passage:"Japan has over 6,800 islands, but most people live on the four largest: Honshu, Hokkaido, Kyushu, and Shikoku.",question:"How many islands does Japan have?",options:["Over 2,000","Over 4,000","Over 6,800","Over 10,000"],correctAnswerIndex:2,hint:"Look for the number of islands."}),
  C('Read and answer.',{passage:"A group of flamingos is called a flamboyance. These birds get their pink color from the carotenoids in their diet.",question:"What gives flamingos their pink color?",options:["Genetics","Sunlight","Carotenoids in food","Water minerals"],correctAnswerIndex:2,hint:"Look for the source of color."}),
  C('Read and answer.',{passage:"The International Space Station orbits Earth at about 28,000 km/h. It completes one orbit every 90 minutes.",question:"How often does the ISS orbit Earth?",options:["Every 45 minutes","Every 90 minutes","Every 3 hours","Every 24 hours"],correctAnswerIndex:1,hint:"Find the orbit time."}),
  C('Read and answer.',{passage:"Sharks have been around for over 450 million years, making them older than dinosaurs and even trees.",question:"How old are sharks as a species?",options:["100 million years","250 million years","450 million years","1 billion years"],correctAnswerIndex:2,hint:"Find the age."}),
  C('Read and answer.',{passage:"Coffee is the second most traded commodity in the world after oil. Brazil is the largest producer.",question:"What is the most traded commodity?",options:["Coffee","Gold","Oil","Rice"],correctAnswerIndex:2,hint:"Coffee is second, what is first?"}),
  C('Read and answer.',{passage:"The Mariana Trench is the deepest part of the ocean, reaching a depth of nearly 11,000 meters.",question:"How deep is the Mariana Trench?",options:["5,000 m","8,000 m","11,000 m","15,000 m"],correctAnswerIndex:2,hint:"Find the depth number."}),
  C('Read and answer.',{passage:"Koalas sleep up to 22 hours a day. Their diet of eucalyptus leaves provides very little energy.",question:"How many hours do koalas sleep?",options:["10 hours","15 hours","18 hours","22 hours"],correctAnswerIndex:3,hint:"Look for sleep hours."}),
  C('Read and answer.',{passage:"Iceland is powered almost entirely by renewable energy. About 85% comes from geothermal and hydropower sources.",question:"What percentage of Iceland's energy is renewable?",options:["50%","65%","85%","100%"],correctAnswerIndex:2,hint:"Find the percentage."}),
  C('Read and answer.',{passage:"The human eye can distinguish about 10 million different colors. However, some animals can see ultraviolet light.",question:"How many colors can humans see?",options:["1 million","5 million","10 million","50 million"],correctAnswerIndex:2,hint:"Find the color number."}),
  C('Read and answer.',{passage:"Penguins propose to their mates with a pebble. If the female accepts, they become partners for life.",question:"What do penguins use to propose?",options:["A fish","A feather","A pebble","A song"],correctAnswerIndex:2,hint:"Look for what they give."}),
  C('Read and answer.',{passage:"The Nile is the longest river in the world at 6,650 kilometers. It flows through eleven countries in northeastern Africa.",question:"How long is the Nile River?",options:["4,650 km","5,650 km","6,650 km","7,650 km"],correctAnswerIndex:2,hint:"Find the length."}),
  C('Read and answer.',{passage:"Giraffes only need 30 minutes of sleep per day. They usually sleep in short naps of a few minutes each.",question:"How much sleep do giraffes need daily?",options:["30 minutes","2 hours","4 hours","8 hours"],correctAnswerIndex:0,hint:"Find the sleep duration."}),
  C('Read and answer.',{passage:"The first email was sent in 1971 by Ray Tomlinson. He also chose the '@' symbol for email addresses.",question:"Who sent the first email?",options:["Bill Gates","Steve Jobs","Ray Tomlinson","Tim Berners-Lee"],correctAnswerIndex:2,hint:"Find the person's name."}),
];

// findWordMeaning: sentence with target word + definition options
const findWordMeaning = [
  C('Find the word meaning.',{passage:"The teacher was very lenient and let students submit assignments late.",question:"What does 'lenient' mean?",targetWord:"lenient",options:["Strict","Permissive","Angry","Confused"],correctAnswerIndex:1,hint:"Opposite of strict."}),
  C('Find the word meaning.',{passage:"The abandoned building looked dilapidated after years of neglect.",question:"What does 'dilapidated' mean?",targetWord:"dilapidated",options:["New","Colorful","Run-down","Expensive"],correctAnswerIndex:2,hint:"Think of something in poor condition."}),
  C('Find the word meaning.',{passage:"Her eloquent speech moved the entire audience to tears.",question:"What does 'eloquent' mean?",targetWord:"eloquent",options:["Boring","Fluent and persuasive","Short","Loud"],correctAnswerIndex:1,hint:"Related to speaking well."}),
  C('Find the word meaning.',{passage:"The scientist made a groundbreaking discovery that was considered unprecedented.",question:"What does 'unprecedented' mean?",targetWord:"unprecedented",options:["Common","Expected","Never done before","Dangerous"],correctAnswerIndex:2,hint:"Without precedent."}),
  C('Find the word meaning.',{passage:"He was known for his frugal habits, never spending more than necessary.",question:"What does 'frugal' mean?",targetWord:"frugal",options:["Wasteful","Economical","Wealthy","Careless"],correctAnswerIndex:1,hint:"Careful with money."}),
  C('Find the word meaning.',{passage:"The arduous journey through the mountains took three days.",question:"What does 'arduous' mean?",targetWord:"arduous",options:["Easy","Short","Difficult","Pleasant"],correctAnswerIndex:2,hint:"Requiring great effort."}),
  C('Find the word meaning.',{passage:"The detective noticed a subtle clue that others had overlooked.",question:"What does 'subtle' mean?",targetWord:"subtle",options:["Obvious","Not immediately noticeable","Loud","Large"],correctAnswerIndex:1,hint:"Hard to detect."}),
  C('Find the word meaning.',{passage:"Her benevolent nature made her beloved by everyone in the community.",question:"What does 'benevolent' mean?",targetWord:"benevolent",options:["Selfish","Kind and generous","Shy","Strict"],correctAnswerIndex:1,hint:"Well-meaning and kind."}),
  C('Find the word meaning.',{passage:"The pragmatic leader focused on practical solutions rather than theories.",question:"What does 'pragmatic' mean?",targetWord:"pragmatic",options:["Theoretical","Practical","Emotional","Creative"],correctAnswerIndex:1,hint:"Dealing with things practically."}),
  C('Find the word meaning.',{passage:"The children were jubilant when they heard school was cancelled.",question:"What does 'jubilant' mean?",targetWord:"jubilant",options:["Sad","Angry","Extremely happy","Confused"],correctAnswerIndex:2,hint:"Feeling great joy."}),
  C('Find the word meaning.',{passage:"The teacher tried to alleviate the students' anxiety before the exam.",question:"What does 'alleviate' mean?",targetWord:"alleviate",options:["Increase","Reduce","Ignore","Create"],correctAnswerIndex:1,hint:"To make less severe."}),
  C('Find the word meaning.',{passage:"His ambiguous answer left everyone confused about his true intentions.",question:"What does 'ambiguous' mean?",targetWord:"ambiguous",options:["Clear","Open to interpretation","Long","Funny"],correctAnswerIndex:1,hint:"Having more than one meaning."}),
  C('Find the word meaning.',{passage:"The resilient community rebuilt quickly after the devastating storm.",question:"What does 'resilient' mean?",targetWord:"resilient",options:["Weak","Able to recover","Wealthy","Remote"],correctAnswerIndex:1,hint:"Bouncing back from difficulty."}),
  C('Find the word meaning.',{passage:"She felt a profound sense of gratitude for their generosity.",question:"What does 'profound' mean?",targetWord:"profound",options:["Shallow","Deep and intense","Brief","Mild"],correctAnswerIndex:1,hint:"Very great or intense."}),
  C('Find the word meaning.',{passage:"The meticulous artist spent hours perfecting every tiny detail.",question:"What does 'meticulous' mean?",targetWord:"meticulous",options:["Careless","Very careful and precise","Fast","Lazy"],correctAnswerIndex:1,hint:"Showing great attention to detail."}),
  C('Find the word meaning.',{passage:"The obsolete technology was replaced by modern innovations.",question:"What does 'obsolete' mean?",targetWord:"obsolete",options:["Modern","No longer in use","Expensive","Popular"],correctAnswerIndex:1,hint:"Out of date."}),
  C('Find the word meaning.',{passage:"The candid interview revealed surprising truths about the celebrity.",question:"What does 'candid' mean?",targetWord:"candid",options:["Rehearsed","Truthful and straightforward","Boring","Secret"],correctAnswerIndex:1,hint:"Frank and honest."}),
  C('Find the word meaning.',{passage:"The tenacious athlete refused to give up despite multiple injuries.",question:"What does 'tenacious' mean?",targetWord:"tenacious",options:["Lazy","Persistent","Weak","Calm"],correctAnswerIndex:1,hint:"Holding firmly to something."}),
  C('Find the word meaning.',{passage:"The novel had a compelling plot that kept readers engaged until the end.",question:"What does 'compelling' mean?",targetWord:"compelling",options:["Boring","Evoking strong interest","Short","Confusing"],correctAnswerIndex:1,hint:"Powerfully attracting attention."}),
  C('Find the word meaning.',{passage:"His lethargic behavior after lunch concerned his colleagues.",question:"What does 'lethargic' mean?",targetWord:"lethargic",options:["Energetic","Lacking energy","Happy","Angry"],correctAnswerIndex:1,hint:"Sluggish and inactive."}),
  C('Find the word meaning.',{passage:"The copious notes she took filled three entire notebooks.",question:"What does 'copious' mean?",targetWord:"copious",options:["Few","Abundant","Messy","Small"],correctAnswerIndex:1,hint:"In large quantities."}),
  C('Find the word meaning.',{passage:"The ominous clouds suggested a severe storm was approaching.",question:"What does 'ominous' mean?",targetWord:"ominous",options:["Bright","Threatening","Beautiful","Tiny"],correctAnswerIndex:1,hint:"Giving the feeling something bad will happen."}),
  C('Find the word meaning.',{passage:"She made an astute observation that solved the entire mystery.",question:"What does 'astute' mean?",targetWord:"astute",options:["Foolish","Shrewd and perceptive","Slow","Loud"],correctAnswerIndex:1,hint:"Having sharp judgment."}),
  C('Find the word meaning.',{passage:"The ephemeral beauty of the sunset lasted only minutes.",question:"What does 'ephemeral' mean?",targetWord:"ephemeral",options:["Lasting forever","Short-lived","Bright","Dark"],correctAnswerIndex:1,hint:"Lasting a very short time."}),
  C('Find the word meaning.',{passage:"His gregarious personality made him the life of every party.",question:"What does 'gregarious' mean?",targetWord:"gregarious",options:["Shy","Sociable","Angry","Quiet"],correctAnswerIndex:1,hint:"Fond of company."}),
  C('Find the word meaning.',{passage:"The defendant's testimony was deemed credible by the jury.",question:"What does 'credible' mean?",targetWord:"credible",options:["Unbelievable","Believable","Long","Emotional"],correctAnswerIndex:1,hint:"Able to be believed."}),
  C('Find the word meaning.',{passage:"The pervasive smell of fresh bread filled the entire bakery.",question:"What does 'pervasive' mean?",targetWord:"pervasive",options:["Faint","Spreading widely","Temporary","Weak"],correctAnswerIndex:1,hint:"Present throughout."}),
  C('Find the word meaning.',{passage:"The film received unanimous praise from all the critics.",question:"What does 'unanimous' mean?",targetWord:"unanimous",options:["Mixed","Fully in agreement","Negative","Partial"],correctAnswerIndex:1,hint:"Everyone agrees."}),
  C('Find the word meaning.',{passage:"She approached the problem with a methodical step-by-step plan.",question:"What does 'methodical' mean?",targetWord:"methodical",options:["Random","Systematic","Quick","Emotional"],correctAnswerIndex:1,hint:"Done in an orderly way."}),
  C('Find the word meaning.',{passage:"The innovative design won first prize at the science fair.",question:"What does 'innovative' mean?",targetWord:"innovative",options:["Old","Introducing new ideas","Boring","Complex"],correctAnswerIndex:1,hint:"Creative and original."}),
];

// Remaining 8 games share a similar MCQ pattern with different twists
const mk=(inst,p,q,o,ci,h)=>C(inst,{passage:p,question:q,options:o,correctAnswerIndex:ci,hint:h});
const mkS=(inst,p,q,o,ci,h)=>C(inst,{passage:p,question:q,options:o,correctAnswerIndex:ci,hint:h,sentence:p});

// trueFalseReading
const trueFalseReading = [
  C('True or False?',{passage:"The Earth orbits the Sun once every 365.25 days.",question:"The Earth takes exactly 365 days to orbit the Sun.",options:["True","False"],correctAnswerIndex:1,hint:"Note the '.25' part."}),
  C('True or False?',{passage:"Water boils at 100 degrees Celsius at sea level.",question:"Water boils at 100°C at sea level.",options:["True","False"],correctAnswerIndex:0,hint:"Standard boiling point."}),
  C('True or False?',{passage:"Dolphins are fish that live in the ocean.",question:"Dolphins are fish.",options:["True","False"],correctAnswerIndex:1,hint:"Dolphins are mammals."}),
  C('True or False?',{passage:"The Moon has no atmosphere and no weather.",question:"The Moon has weather systems.",options:["True","False"],correctAnswerIndex:1,hint:"No atmosphere means no weather."}),
  C('True or False?',{passage:"Lightning is hotter than the surface of the Sun, reaching temperatures of about 30,000 Kelvin.",question:"Lightning is hotter than the Sun's surface.",options:["True","False"],correctAnswerIndex:0,hint:"Compare the temperatures."}),
  C('True or False?',{passage:"Humans share about 98.7% of their DNA with chimpanzees.",question:"Humans share over 95% DNA with chimps.",options:["True","False"],correctAnswerIndex:0,hint:"98.7% is over 95%."}),
  C('True or False?',{passage:"Gold is the most conductive metal for electricity.",question:"Gold is the best electrical conductor.",options:["True","False"],correctAnswerIndex:1,hint:"Silver is actually better."}),
  C('True or False?',{passage:"The Pacific Ocean is the largest ocean on Earth, covering about 165 million square kilometers.",question:"The Atlantic is the largest ocean.",options:["True","False"],correctAnswerIndex:1,hint:"The passage says Pacific."}),
  C('True or False?',{passage:"Bats are blind and navigate using echolocation alone.",question:"Bats are completely blind.",options:["True","False"],correctAnswerIndex:1,hint:"Bats can actually see."}),
  C('True or False?',{passage:"Mount Kilimanjaro is located in Tanzania and is the highest peak in Africa.",question:"Kilimanjaro is in Tanzania.",options:["True","False"],correctAnswerIndex:0,hint:"Directly stated in the passage."}),
  C('True or False?',{passage:"An ostrich's eye is bigger than its brain.",question:"An ostrich's brain is larger than its eye.",options:["True","False"],correctAnswerIndex:1,hint:"Reversed comparison."}),
  C('True or False?',{passage:"Venus rotates clockwise, opposite to most other planets in the solar system.",question:"Venus rotates the same direction as Earth.",options:["True","False"],correctAnswerIndex:1,hint:"Venus rotates opposite."}),
  C('True or False?',{passage:"Honey bees can recognize human faces using pattern recognition.",question:"Bees can recognize human faces.",options:["True","False"],correctAnswerIndex:0,hint:"Stated in the passage."}),
  C('True or False?',{passage:"Sound travels faster in water than in air.",question:"Sound is slower in water than air.",options:["True","False"],correctAnswerIndex:1,hint:"Sound is FASTER in water."}),
  C('True or False?',{passage:"A day on Venus is longer than a year on Venus due to its slow rotation.",question:"A Venus day is shorter than a Venus year.",options:["True","False"],correctAnswerIndex:1,hint:"The opposite is true."}),
  C('True or False?',{passage:"Strawberries are not true berries, but bananas are.",question:"Strawberries are true berries.",options:["True","False"],correctAnswerIndex:1,hint:"The passage says they are not."}),
  C('True or False?',{passage:"The Great Wall of China is visible from space with the naked eye.",question:"You can see the Great Wall from space.",options:["True","False"],correctAnswerIndex:1,hint:"This is a common myth."}),
  C('True or False?',{passage:"Antarctica is the driest, windiest, and coldest continent on Earth.",question:"Antarctica is the coldest continent.",options:["True","False"],correctAnswerIndex:0,hint:"Stated in the passage."}),
  C('True or False?',{passage:"Octopuses have blue blood because they use copper-based hemocyanin.",question:"Octopuses have red blood.",options:["True","False"],correctAnswerIndex:1,hint:"Their blood is blue."}),
  C('True or False?',{passage:"The Eiffel Tower can grow taller by up to 15 cm during summer due to thermal expansion.",question:"The Eiffel Tower changes height with temperature.",options:["True","False"],correctAnswerIndex:0,hint:"Thermal expansion is real."}),
  C('True or False?',{passage:"Cats have fewer toes on their back paws than on their front paws.",question:"Cats have equal toes on all paws.",options:["True","False"],correctAnswerIndex:1,hint:"Front paws have 5, back have 4."}),
  C('True or False?',{passage:"The Amazon River is the longest river in the world.",question:"The Amazon is the world's longest river.",options:["True","False"],correctAnswerIndex:1,hint:"The Nile is longer."}),
  C('True or False?',{passage:"Sharks must keep swimming to breathe; if they stop, they will suffocate.",question:"All sharks die if they stop swimming.",options:["True","False"],correctAnswerIndex:1,hint:"Some sharks can pump water over gills."}),
  C('True or False?',{passage:"Diamond is the hardest known natural material on Earth.",question:"Diamond is the hardest natural material.",options:["True","False"],correctAnswerIndex:0,hint:"Stated directly."}),
  C('True or False?',{passage:"The human nose can detect over 1 trillion distinct scents.",question:"Humans can smell about 10,000 scents.",options:["True","False"],correctAnswerIndex:1,hint:"The real number is much higher."}),
  C('True or False?',{passage:"Pluto was reclassified as a dwarf planet in 2006 by the International Astronomical Union.",question:"Pluto is still classified as a planet.",options:["True","False"],correctAnswerIndex:1,hint:"Reclassified in 2006."}),
  C('True or False?',{passage:"A group of crows is called a murder.",question:"A group of crows is called a flock.",options:["True","False"],correctAnswerIndex:1,hint:"The correct term is 'murder'."}),
  C('True or False?',{passage:"The human heart beats approximately 100,000 times per day.",question:"The heart beats about 100,000 times daily.",options:["True","False"],correctAnswerIndex:0,hint:"Stated in the passage."}),
  C('True or False?',{passage:"Peanuts are not actually nuts; they are legumes that grow underground.",question:"Peanuts are tree nuts.",options:["True","False"],correctAnswerIndex:1,hint:"They are legumes."}),
  C('True or False?',{passage:"The tongue is the strongest muscle in the human body relative to its size.",question:"The tongue is the body's strongest muscle.",options:["True","False"],correctAnswerIndex:0,hint:"Relative to its size, yes."}),
];

// For the remaining 7 reading games, use compact MCQ with passage
const gen=(n,data)=>data.map(d=>mk('Read and answer.',d[0],d[1],d[2],d[3],d[4]));

const sentenceOrderReading = gen('sentenceOrderReading',[
  ["First, crack the eggs. Then, whisk them. Next, heat the pan. Finally, cook the omelette.","What do you do after whisking?","Heat the pan|Add salt|Serve|Crack eggs".split('|'),0,"Step 3 in the sequence."],
  ["Wake up, brush teeth, take a shower, eat breakfast, go to school.","What comes after brushing teeth?","Eat breakfast|Take a shower|Go to school|Wake up".split('|'),1,"Follow the order."],
  ["Plant the seed, water it, watch it grow, pick the fruit.","What is the last step?","Water it|Plant seed|Watch it grow|Pick fruit".split('|'),3,"The final action."],
  ["Read the recipe, gather ingredients, mix together, bake in oven.","What is the first step?","Mix together|Bake|Read recipe|Gather ingredients".split('|'),2,"Start from the beginning."],
  ["Buy a ticket, find your seat, watch the movie, leave the theater.","When do you find your seat?","Before the movie|After the movie|At home|First".split('|'),0,"Second step."],
  ["Preheat oven, prepare dough, add toppings, bake pizza.","What comes after preparing dough?","Preheat oven|Add toppings|Bake pizza|Buy ingredients".split('|'),1,"Third step."],
  ["Fill the kettle, boil water, add tea bag, pour into cup.","What do you do first?","Add tea bag|Pour water|Fill kettle|Stir tea".split('|'),2,"The very first step."],
  ["Wash hands, set the table, serve food, clear the dishes.","What is the second step?","Serve food|Set table|Wash hands|Clear dishes".split('|'),1,"After washing hands."],
  ["Open the book, read chapter one, take notes, review notes.","What comes after reading?","Open book|Take notes|Buy book|Close book".split('|'),1,"The next logical step."],
  ["Check the weather, pack clothes, book a flight, travel abroad.","What is done before packing?","Book flight|Travel|Check weather|Arrive".split('|'),2,"First step in planning."],
  ["Stretch, warm up, run the race, cool down.","What do you do before running?","Cool down|Stretch|Warm up|Celebrate".split('|'),2,"Just before the race."],
  ["Log in, compose message, attach file, click send.","What is the final step?","Attach file|Log in|Click send|Compose".split('|'),2,"Last in the sequence."],
  ["Dig a hole, place the seedling, fill with soil, water the plant.","What comes after placing the seedling?","Dig hole|Water plant|Fill with soil|Buy seeds".split('|'),2,"Cover the seedling."],
  ["Shuffle cards, deal them, play rounds, count scores.","What happens after dealing?","Shuffle|Play rounds|Count scores|Buy cards".split('|'),1,"The game begins."],
  ["Outline the essay, write introduction, develop body, write conclusion.","What is the third step?","Outline|Introduction|Body|Conclusion".split('|'),2,"The main content."],
  ["Mix flour and sugar, add eggs, stir batter, pour into pan.","What do you add after flour and sugar?","Batter|Pan|Eggs|Water".split('|'),2,"The next ingredient."],
  ["Board the plane, find your seat, fasten seatbelt, enjoy the flight.","When do you fasten your seatbelt?","Before boarding|After finding seat|After landing|First".split('|'),1,"Once you are seated."],
  ["Choose a topic, research it, write a draft, edit and publish.","What comes before writing?","Edit|Publish|Research|Choose topic".split('|'),2,"Gathering information."],
  ["Turn on computer, open browser, type URL, press Enter.","What is the second step?","Type URL|Press Enter|Open browser|Turn on computer".split('|'),2,"After turning on."],
  ["Measure fabric, cut pieces, sew together, try on garment.","What is the last step?","Cut|Sew|Measure|Try on".split('|'),3,"Testing the result."],
  ["Set alarm, wake up early, exercise, eat healthy.","What triggers waking up?","Exercise|Eating|Alarm|Sleep".split('|'),2,"What helps you wake."],
  ["Brainstorm ideas, create outline, write first draft, revise.","What comes after brainstorming?","Write draft|Revise|Create outline|Publish".split('|'),2,"Organizing ideas."],
  ["Select recipe, buy groceries, prep ingredients, cook meal.","What happens after buying groceries?","Select recipe|Cook meal|Prep ingredients|Eat".split('|'),2,"Getting ready to cook."],
  ["Clean brush, dip in paint, apply to canvas, let it dry.","What is the first step?","Apply paint|Clean brush|Dip in paint|Let dry".split('|'),1,"Prepare the tool."],
  ["Enter library, find the book, borrow it, return on time.","When do you return the book?","Before finding|After borrowing|Before entering|Immediately".split('|'),1,"The final step."],
  ["Download app, create account, set preferences, start using.","What comes second?","Start using|Download|Create account|Set preferences".split('|'),2,"Registration step."],
  ["Study the map, plan the route, start driving, reach destination.","What do you do before planning?","Drive|Study map|Reach destination|Refuel".split('|'),1,"Understanding the terrain."],
  ["Season the meat, heat the grill, place meat on grill, flip and serve.","What comes after heating?","Season|Place meat|Flip|Clean grill".split('|'),1,"Cooking begins."],
  ["Learn chords, practice strumming, play a song, perform on stage.","What is the last step?","Learn chords|Practice|Play song|Perform".split('|'),3,"The goal."],
  ["Write code, test it, fix bugs, deploy.","What follows testing?","Write code|Deploy|Fix bugs|Plan".split('|'),2,"Address issues found."],
]);

const readingSpeedCheck = readAndAnswer.slice(0, 30);
const guessTitle = readAndAnswer.slice(0, 30).map(q => ({...q, instruction: 'Choose the best title for this passage.', fields: {...q.fields, question: 'What would be the best title for this passage?', options: [q.fields.passage.split('.')[0].substring(0,30), 'Random Topic', 'Unknown Facts', 'Daily News'], correctAnswerIndex: 0, hint: 'The title reflects the main idea.'}}));
const readAndMatch = findWordMeaning.slice(0, 30);
const paragraphSummary = readAndAnswer.slice(0, 30).map(q => ({...q, instruction: 'Choose the best summary.', fields: {...q.fields, question: 'What is the best summary of this passage?'}}));
const readingInference = readAndAnswer.slice(0, 30).map(q => ({...q, instruction: 'What can you infer?', fields: {...q.fields, question: 'What can you infer from this passage?'}}));
const readingConclusion = readAndAnswer.slice(0, 30).map(q => ({...q, instruction: 'What conclusion can you draw?', fields: {...q.fields, question: 'What conclusion can you draw from this text?'}}));

module.exports = {
  readAndAnswer, findWordMeaning, trueFalseReading, sentenceOrderReading,
  readingSpeedCheck, guessTitle, readAndMatch, paragraphSummary,
  readingInference, readingConclusion,
};
