// Vocabulary category pools - 10 games × 30 templates each
const C = (inst,fields,it) => ({instruction:inst,interactionType:it||'choice',fields});

// flashcards: word + definition + example
const words = [
  ["Melancholy","A feeling of pensive sadness","He felt a wave of melancholy after the movie."],
  ["Ephemeral","Lasting a very short time","The beauty of cherry blossoms is ephemeral."],
  ["Ubiquitous","Present everywhere","Smartphones have become ubiquitous."],
  ["Resilient","Able to recover quickly","She proved to be remarkably resilient."],
  ["Pragmatic","Dealing with things practically","He took a pragmatic approach to the problem."],
  ["Eloquent","Fluent and persuasive in speaking","She gave an eloquent speech at the ceremony."],
  ["Tenacious","Holding firmly; persistent","The tenacious climber reached the summit."],
  ["Meticulous","Showing great attention to detail","Her meticulous planning ensured success."],
  ["Candid","Truthful and straightforward","His candid remarks surprised everyone."],
  ["Benevolent","Kind and generous","The benevolent donor funded the school."],
  ["Ambiguous","Open to more than one interpretation","The ambiguous message confused us all."],
  ["Diligent","Showing careful persistent effort","The diligent student earned top marks."],
  ["Lucid","Clear and easy to understand","Her lucid explanation helped everyone."],
  ["Vivacious","Lively and attractive","Her vivacious personality lit up the room."],
  ["Astute","Shrewd and perceptive","An astute investor spots trends early."],
  ["Gregarious","Fond of company; sociable","His gregarious nature won many friends."],
  ["Arduous","Involving great effort; difficult","The arduous trek lasted five days."],
  ["Copious","Abundant in supply","She took copious notes during the lecture."],
  ["Jubilant","Feeling or expressing great happiness","The crowd was jubilant after the victory."],
  ["Profound","Very deep or intense","The book had a profound impact on me."],
  ["Obsolete","No longer produced or used","Typewriters have become obsolete."],
  ["Innovative","Introducing new ideas; creative","The innovative design won many awards."],
  ["Frugal","Sparing or economical with money","Her frugal habits helped her save a fortune."],
  ["Lethargic","Lacking energy; sluggish","The heat made everyone feel lethargic."],
  ["Ominous","Giving the feeling something bad will happen","The ominous clouds signaled a storm."],
  ["Pervasive","Spreading widely throughout","Music has a pervasive influence on culture."],
  ["Credible","Able to be believed; convincing","The witness gave a credible account."],
  ["Whimsical","Playfully quaint or fanciful","The garden had a whimsical fairy-tale feel."],
  ["Nonchalant","Casually calm and relaxed","He gave a nonchalant shrug."],
  ["Versatile","Able to adapt to many functions","She is a versatile musician."],
];
const flashcards = words.map(w => C('Match the word to its definition.',{word:w[0],definition:w[1],example:w[2]},'match'));

// synonymSearch
const synData = [
  ["Happy","Joyful","Sad","Angry","Tired",0],["Big","Enormous","Tiny","Slow","Dark",0],
  ["Fast","Quick","Heavy","Dull","Rough",0],["Smart","Intelligent","Lazy","Tall","Wide",0],
  ["Pretty","Beautiful","Ugly","Short","Loud",0],["Start","Begin","End","Break","Fall",0],
  ["Brave","Courageous","Scared","Weak","Small",0],["Angry","Furious","Calm","Happy","Shy",0],
  ["Quiet","Silent","Loud","Fast","Hard",0],["Rich","Wealthy","Poor","Thin","Cold",0],
  ["Strange","Peculiar","Normal","Big","Flat",0],["Old","Ancient","New","Wet","Soft",0],
  ["Hard","Difficult","Easy","Light","Hot",0],["Small","Tiny","Huge","Wide","Deep",0],
  ["Kind","Generous","Mean","Tall","Dark",0],["Scared","Frightened","Brave","Strong","Loud",0],
  ["Tired","Exhausted","Energetic","Fast","Cold",0],["Honest","Truthful","Deceitful","Slow","Big",0],
  ["Rude","Impolite","Polite","Quiet","Soft",0],["Create","Invent","Destroy","Hide","Sleep",0],
  ["Fix","Repair","Break","Lose","Drop",0],["Gather","Collect","Scatter","Push","Burn",0],
  ["Keep","Retain","Discard","Throw","Run",0],["Leave","Depart","Arrive","Stay","Sit",0],
  ["Look","Observe","Ignore","Sleep","Talk",0],["End","Conclude","Start","Jump","Fly",0],
  ["Calm","Serene","Anxious","Fast","Rough",0],["Harm","Damage","Help","Build","Grow",0],
  ["Allow","Permit","Forbid","Run","Eat",0],["Show","Display","Hide","Cook","Drive",0],
];
const synonymSearch = synData.map(d => C('Find the synonym.',{question:`What is a synonym for "${d[0]}"?`,targetWord:d[0],options:[d[1],d[2],d[3],d[4]],correctAnswerIndex:d[5],hint:`Similar meaning to "${d[0]}".`}));

// antonymSearch
const antData = [
  ["Hot","Cold","Warm","Dry","Wet",0],["Happy","Sad","Glad","Calm","Shy",0],
  ["Fast","Slow","Quick","Hard","Deep",0],["Big","Small","Wide","Tall","Long",0],
  ["Light","Dark","Bright","Soft","Thin",0],["Old","Young","Ancient","Wise","Tall",0],
  ["Hard","Soft","Strong","Tough","Firm",0],["Love","Hate","Like","Want","Need",0],
  ["Rich","Poor","Wealthy","Lucky","Bold",0],["Open","Closed","Wide","Free","New",0],
  ["Clean","Dirty","Fresh","Pure","Clear",0],["Brave","Cowardly","Strong","Bold","Wise",0],
  ["Calm","Anxious","Still","Quiet","Cool",0],["Early","Late","Soon","Quick","Fast",0],
  ["Simple","Complex","Easy","Plain","Clear",0],["Loud","Quiet","Noisy","Bold","Sharp",0],
  ["True","False","Real","Honest","Sure",0],["Win","Lose","Gain","Score","Beat",0],
  ["Full","Empty","Complete","Total","Round",0],["Strong","Weak","Tough","Hard","Firm",0],
  ["War","Peace","Fight","Battle","Clash",0],["Accept","Reject","Take","Want","Agree",0],
  ["Rise","Fall","Grow","Climb","Jump",0],["Buy","Sell","Shop","Pay","Get",0],
  ["Awake","Asleep","Alert","Active","Alive",0],["Begin","End","Start","Open","Try",0],
  ["Safe","Dangerous","Secure","Sure","Good",0],["Polite","Rude","Kind","Nice","Gentle",0],
  ["Wet","Dry","Damp","Moist","Soaked",0],["Success","Failure","Win","Gain","Pride",0],
];
const antonymSearch = antData.map(d => C('Find the antonym.',{question:`What is the opposite of "${d[0]}"?`,targetWord:d[0],options:[d[1],d[2],d[3],d[4]],correctAnswerIndex:d[5],hint:`Opposite meaning of "${d[0]}".`}));

// contextClues
const contextClues = words.map(w => C('Use context clues.',{passage:`The situation was ${w[0].toLowerCase()}. ${w[2]}`,question:`Based on context, "${w[0].toLowerCase()}" most likely means:`,targetWord:w[0].toLowerCase(),options:[w[1],"Something bright","A type of food","A musical term"],correctAnswerIndex:0,hint:"Use the surrounding words."}));

// phrasalVerbs
const pvData = [
  ["break down","stop functioning","My car broke down on the highway."],
  ["bring up","mention a topic","She brought up an interesting point."],
  ["call off","cancel","They called off the meeting."],
  ["carry on","continue","Please carry on with your work."],
  ["come across","find by chance","I came across an old photo."],
  ["cut down","reduce","We need to cut down on expenses."],
  ["figure out","understand or solve","Can you figure out this puzzle?"],
  ["get along","have a good relationship","They get along very well."],
  ["give up","stop trying","Never give up on your dreams."],
  ["go over","review","Let's go over the plan once more."],
  ["hold on","wait","Hold on, I'll be right back."],
  ["keep up","maintain pace","Try to keep up with the class."],
  ["look after","take care of","She looks after her grandmother."],
  ["look into","investigate","The police are looking into the case."],
  ["look forward to","anticipate with pleasure","I look forward to the holiday."],
  ["make up","invent or reconcile","They made up after the argument."],
  ["pass away","die","Her grandfather passed away last year."],
  ["pick up","collect or learn","I picked up some Spanish abroad."],
  ["put off","postpone","Don't put off your homework."],
  ["run out of","exhaust supply","We ran out of milk."],
  ["set up","arrange or establish","She set up her own business."],
  ["show up","arrive","He didn't show up for the interview."],
  ["take off","leave the ground or remove","The plane took off on time."],
  ["turn down","reject","She turned down the job offer."],
  ["turn up","arrive or increase volume","He turned up unexpectedly."],
  ["work out","exercise or solve","I work out three times a week."],
  ["point out","indicate","He pointed out the mistake."],
  ["put up with","tolerate","I can't put up with the noise."],
  ["run into","meet by chance","I ran into an old friend."],
  ["take over","assume control","The new manager took over today."],
];
const phrasalVerbs = pvData.map(d => C('What does this phrasal verb mean?',{question:`"${d[0]}" means:`,targetWord:d[0],example:d[2],options:[d[1],"to eat quickly","to sleep well","to sing loudly"],correctAnswerIndex:0,hint:`Think about "${d[0]}" in context.`}));

// idioms
const idData = [
  ["Break the ice","Start a conversation in an awkward situation","His joke helped break the ice."],
  ["Hit the nail on the head","Be exactly right","You hit the nail on the head with that answer."],
  ["Under the weather","Feeling ill","She's been under the weather all week."],
  ["Piece of cake","Very easy","The test was a piece of cake."],
  ["Spill the beans","Reveal a secret","Don't spill the beans about the surprise."],
  ["Bite the bullet","Endure something painful","He had to bite the bullet and apologize."],
  ["Cost an arm and a leg","Very expensive","That car costs an arm and a leg."],
  ["Kill two birds with one stone","Achieve two things at once","Shopping there kills two birds with one stone."],
  ["Let the cat out of the bag","Reveal a secret accidentally","She let the cat out of the bag."],
  ["On cloud nine","Extremely happy","He's been on cloud nine since the promotion."],
  ["Barking up the wrong tree","Looking in the wrong place","You're barking up the wrong tree."],
  ["Burn the midnight oil","Work late into the night","Students burn the midnight oil before exams."],
  ["The ball is in your court","It's your decision now","I've made my offer; the ball is in your court."],
  ["A blessing in disguise","Something good from something bad","Losing that job was a blessing in disguise."],
  ["Once in a blue moon","Very rarely","We eat out once in a blue moon."],
  ["When pigs fly","Something that will never happen","He'll clean his room when pigs fly."],
  ["Sit on the fence","Not make a decision","Stop sitting on the fence and choose."],
  ["The last straw","The final problem in a series","That comment was the last straw."],
  ["Add fuel to the fire","Make a bad situation worse","His words just added fuel to the fire."],
  ["Go the extra mile","Do more than expected","She always goes the extra mile for clients."],
  ["Actions speak louder than words","What you do matters more","Show me; actions speak louder than words."],
  ["Beat around the bush","Avoid the main topic","Stop beating around the bush and tell me."],
  ["Better late than never","It's better to do something late than not at all","You finally arrived! Better late than never."],
  ["Cry over spilt milk","Worry about what's done","No use crying over spilt milk."],
  ["Every cloud has a silver lining","Something positive in bad situations","She believes every cloud has a silver lining."],
  ["Get out of hand","Get out of control","The party got out of hand quickly."],
  ["Hit the books","Start studying","Time to hit the books for finals."],
  ["In hot water","In trouble","He's in hot water with his boss."],
  ["Jump on the bandwagon","Follow a popular trend","Everyone jumped on the bandwagon."],
  ["Keep your chin up","Stay positive","Keep your chin up; things will improve."],
];
const idioms = idData.map(d => C('What does this idiom mean?',{question:`"${d[0]}" means:`,targetWord:d[0],example:d[2],options:[d[1],"To run very fast","To cook dinner","To read a book"],correctAnswerIndex:0,hint:`Think about "${d[0]}" figuratively.`}));

// academicWord - reuse words pool with academic twist
const academicWord = words.map(w => C('Choose the correct definition.',{question:`What does "${w[0]}" mean?`,word:w[0],options:[w[1],"A type of animal","A cooking method","A sport"],correctAnswerIndex:0,hint:w[2]}));

// topicVocab
const tvData = [
  ["Medicine","Prescription","A doctor's order for medicine","Take the prescription to the pharmacy."],
  ["Technology","Algorithm","A set of rules for solving problems","Search engines use complex algorithms."],
  ["Law","Verdict","The decision of a jury","The jury reached a guilty verdict."],
  ["Finance","Dividend","A share of profits paid to shareholders","The company paid quarterly dividends."],
  ["Science","Hypothesis","A proposed explanation for a phenomenon","She tested her hypothesis in the lab."],
  ["Education","Curriculum","The subjects in a course of study","The new curriculum includes coding."],
  ["Environment","Biodiversity","Variety of life in a habitat","Rainforests have incredible biodiversity."],
  ["Politics","Democracy","Government by the people","They fought for democracy."],
  ["Sports","Endurance","The ability to sustain effort","Marathon running requires great endurance."],
  ["Art","Aesthetic","Concerned with beauty","The building has great aesthetic appeal."],
  ["Music","Tempo","The speed of a musical piece","The tempo of the song increased gradually."],
  ["Geography","Peninsula","Land surrounded by water on three sides","Florida is a peninsula."],
  ["History","Renaissance","A period of cultural rebirth in Europe","The Renaissance began in Italy."],
  ["Psychology","Cognitive","Related to mental processes","Cognitive therapy helps change thought patterns."],
  ["Astronomy","Constellation","A group of stars forming a pattern","Orion is a well-known constellation."],
  ["Cooking","Simmer","Cook just below boiling point","Let the sauce simmer for 20 minutes."],
  ["Architecture","Facade","The front face of a building","The facade was beautifully decorated."],
  ["Literature","Metaphor","A figure of speech comparing unlike things","Life is a journey is a metaphor."],
  ["Economics","Inflation","A general increase in prices","Inflation erodes purchasing power."],
  ["Biology","Photosynthesis","Plants converting light to energy","Photosynthesis requires sunlight."],
  ["Chemistry","Catalyst","A substance that speeds up a reaction","Enzymes act as biological catalysts."],
  ["Physics","Velocity","Speed in a given direction","The car's velocity was 60 km/h north."],
  ["Sociology","Demographic","A section of the population","The survey targeted a young demographic."],
  ["Marine","Coral","Marine organisms forming reefs","Coral reefs support diverse ecosystems."],
  ["Weather","Precipitation","Rain, snow, sleet, or hail","The forecast predicts heavy precipitation."],
  ["Math","Equation","A mathematical statement of equality","Solve the equation for x."],
  ["Philosophy","Ethics","Moral principles governing behavior","Business ethics are increasingly important."],
  ["Journalism","Headline","The title of a news article","The headline grabbed everyone's attention."],
  ["Agriculture","Irrigation","Supplying water to crops","Irrigation transformed the desert farm."],
  ["Aviation","Turbulence","Irregular air movement","The flight encountered severe turbulence."],
];
const topicVocab = tvData.map(d => C(`Topic: ${d[0]}`,{question:`What does "${d[1]}" mean?`,word:d[1],topic:d[0],options:[d[2],"A type of dance","A kitchen tool","A board game"],correctAnswerIndex:0,hint:d[3]}));

// wordFormation
const wfData = [
  ["happy","happiness","noun","What is the noun form of 'happy'?",["happiness","happily","happier","happiest"],0],
  ["create","creative","adjective","What is the adjective form of 'create'?",["creation","creative","creator","created"],1],
  ["beauty","beautiful","adjective","What is the adjective form of 'beauty'?",["beautiful","beautify","beautifully","beauteous"],0],
  ["success","successful","adjective","What is the adjective form of 'success'?",["successful","succeed","succession","successively"],0],
  ["decide","decision","noun","What is the noun form of 'decide'?",["decision","decisive","decidedly","decider"],0],
  ["move","movement","noun","What is the noun form of 'move'?",["movement","movable","mover","moving"],0],
  ["strong","strengthen","verb","What is the verb form of 'strong'?",["strength","strengthen","strongly","stronger"],1],
  ["real","reality","noun","What is the noun form of 'real'?",["reality","realize","really","realistic"],0],
  ["friend","friendship","noun","What is the noun form of 'friend'?",["friendly","friendship","friendless","befriend"],1],
  ["act","action","noun","What is the noun form of 'act'?",["action","active","actor","actually"],0],
  ["educate","education","noun","What is the noun form of 'educate'?",["education","educated","educator","educational"],0],
  ["differ","different","adjective","What is the adjective form of 'differ'?",["difference","different","differently","differentiate"],1],
  ["care","careful","adjective","What is the adjective form of 'care'?",["careful","careless","carer","caring"],0],
  ["wonder","wonderful","adjective","What is the adjective form of 'wonder'?",["wonderful","wondering","wonderment","wondrous"],0],
  ["inform","information","noun","What is the noun form of 'inform'?",["information","informative","informed","informer"],0],
  ["enjoy","enjoyment","noun","What is the noun form of 'enjoy'?",["enjoyable","enjoyment","enjoying","enjoyed"],1],
  ["construct","construction","noun","What is the noun form of 'construct'?",["construction","constructive","constructor","constructed"],0],
  ["develop","development","noun","What is the noun form of 'develop'?",["development","developing","developer","developed"],0],
  ["danger","dangerous","adjective","What is the adjective form of 'danger'?",["dangerous","endanger","dangerously","endangered"],0],
  ["power","powerful","adjective","What is the adjective form of 'power'?",["powerful","powerless","empower","powered"],0],
  ["rely","reliable","adjective","What is the adjective form of 'rely'?",["reliable","reliance","reliably","relied"],0],
  ["sense","sensitive","adjective","What is the adjective form of 'sense'?",["sensible","sensitive","sensation","sensory"],1],
  ["produce","production","noun","What is the noun form of 'produce'?",["production","productive","producer","producing"],0],
  ["imagine","imagination","noun","What is the noun form of 'imagine'?",["imagination","imaginative","imaginary","imagined"],0],
  ["compete","competition","noun","What is the noun form of 'compete'?",["competition","competitive","competitor","competing"],0],
  ["invest","investment","noun","What is the noun form of 'invest'?",["investment","investor","invested","investing"],0],
  ["employ","employment","noun","What is the noun form of 'employ'?",["employment","employee","employer","employed"],0],
  ["achieve","achievement","noun","What is the noun form of 'achieve'?",["achievement","achiever","achievable","achieving"],0],
  ["communicate","communication","noun","What is the noun form of 'communicate'?",["communication","communicative","communicator","communicated"],0],
  ["organize","organization","noun","What is the noun form of 'organize'?",["organization","organized","organizer","organizing"],0],
];
const wordFormation = wfData.map(d => C(d[3],{question:d[3],baseWord:d[0],targetForm:d[2],options:d[4],correctAnswerIndex:d[5],hint:`Change "${d[0]}" to its ${d[2]} form.`}));

// prefixSuffix
const psData = [
  ["un-","not","What does the prefix 'un-' mean?",["not","again","before","after"],0,"'Unhappy' means not happy."],
  ["re-","again","What does the prefix 're-' mean?",["not","again","under","over"],1,"'Redo' means do again."],
  ["pre-","before","What does the prefix 'pre-' mean?",["after","not","before","with"],2,"'Preview' means view before."],
  ["mis-","wrongly","What does the prefix 'mis-' mean?",["correctly","under","wrongly","over"],2,"'Misunderstand' means understand wrongly."],
  ["over-","too much","What does the prefix 'over-' mean?",["under","too much","not","again"],1,"'Overeat' means eat too much."],
  ["dis-","not or opposite","What does the prefix 'dis-' mean?",["not","again","before","with"],0,"'Disagree' means not agree."],
  ["sub-","under","What does the prefix 'sub-' mean?",["over","with","under","again"],2,"'Submarine' means under the sea."],
  ["inter-","between","What does the prefix 'inter-' mean?",["within","between","above","below"],1,"'International' means between nations."],
  ["-ful","full of","What does the suffix '-ful' mean?",["without","full of","like","able to"],1,"'Hopeful' means full of hope."],
  ["-less","without","What does the suffix '-less' mean?",["full of","without","able to","like"],1,"'Careless' means without care."],
  ["-tion","makes a noun","What does the suffix '-tion' do?",["Makes verb","Makes adjective","Makes noun","Makes adverb"],2,"'Education' is a noun form."],
  ["-able","can be done","What does the suffix '-able' mean?",["without","full of","can be done","makes noun"],2,"'Readable' means can be read."],
  ["-ly","in the manner of","What does the suffix '-ly' do?",["Makes noun","Makes verb","Makes adjective","Makes adverb"],3,"'Quickly' is an adverb."],
  ["-ment","result or action","What does the suffix '-ment' do?",["Makes verb","Makes noun","Makes adjective","Makes adverb"],1,"'Enjoyment' is a noun."],
  ["-ness","state or quality","What does the suffix '-ness' mean?",["State or quality","Action","Full of","Without"],0,"'Kindness' is a state."],
  ["anti-","against","What does the prefix 'anti-' mean?",["for","with","against","under"],2,"'Antibody' fights against."],
  ["auto-","self","What does the prefix 'auto-' mean?",["other","self","many","few"],1,"'Autobiography' is about self."],
  ["bi-","two","What does the prefix 'bi-' mean?",["one","two","three","many"],1,"'Bicycle' has two wheels."],
  ["tri-","three","What does the prefix 'tri-' mean?",["one","two","three","four"],2,"'Triangle' has three sides."],
  ["mono-","one","What does the prefix 'mono-' mean?",["one","two","many","none"],0,"'Monologue' is one person speaking."],
  ["multi-","many","What does the prefix 'multi-' mean?",["one","few","none","many"],3,"'Multilingual' means many languages."],
  ["-ize","to make","What does the suffix '-ize' mean?",["without","to make","full of","state of"],1,"'Modernize' means to make modern."],
  ["-er","one who does","What does the suffix '-er' mean?",["place","one who does","without","action"],1,"'Teacher' is one who teaches."],
  ["-ist","one who practices","What does the suffix '-ist' mean?",["place","action","one who practices","without"],2,"'Artist' practices art."],
  ["-ous","having the quality of","What does '-ous' mean?",["without","having quality of","action","place"],1,"'Dangerous' has quality of danger."],
  ["-ive","having tendency to","What does '-ive' mean?",["without","place","having tendency to","one who"],2,"'Active' tends to act."],
  ["super-","above or beyond","What does 'super-' mean?",["below","above/beyond","beside","within"],1,"'Superhero' is beyond a hero."],
  ["micro-","very small","What does 'micro-' mean?",["very large","very small","very fast","very old"],1,"'Microscope' sees small things."],
  ["semi-","half","What does 'semi-' mean?",["full","double","half","quarter"],2,"'Semicircle' is half a circle."],
  ["trans-","across","What does 'trans-' mean?",["within","under","across","above"],2,"'Transport' carries across."],
];
const prefixSuffix = psData.map(d => C(d[2],{question:d[2],affix:d[0],meaning:d[1],options:d[3],correctAnswerIndex:d[4],hint:d[5]}));

module.exports = {
  flashcards, synonymSearch, antonymSearch, contextClues,
  phrasalVerbs, idioms, academicWord, topicVocab,
  wordFormation, prefixSuffix,
};
